DROP TABLE IF EXISTS `USERS`;
CREATE TABLE USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(100),
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
    UPDATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
    INDEX IDX_USER_USERNAME (USERNAME),
    INDEX IDX_USER_PASSWORD (PASSWORD)
);
INSERT INTO USERS (USERNAME,PASSWORD) VALUE ('haidh8','$2a$10$ImmpRSLlf.WNugroQhaWTe3libE7.UrNeZpcDQxvgssOthhe1I0J6');


-- Bảng chính: CATEGORIES
DROP TABLE IF EXISTS `CATEGORIES`;
CREATE TABLE CATEGORIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(100) NOT NULL,
	SLUG VARCHAR(100),
    ENG VARCHAR(255) NOT NULL,
    VI VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
    UPDATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
	NUMBER INT,
    INDEX IDX_CATEGORIES_ENG (ENG),
    INDEX IDX_CATEGORIES_VI (VI)
);


-- Bảng danh mục con: SUBCATEGORIES
DROP TABLE IF EXISTS `SUBCATEGORIES`;
CREATE TABLE SUBCATEGORIES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(100) NOT NULL,
	SLUG VARCHAR(100),
    ENG VARCHAR(255) NOT NULL,
    VI VARCHAR(255) NOT NULL,
	CATEGORY_SLUG VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
    UPDATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
	NUMBER INT,
	INDEX IDX_SUBCATEGORIES_ENG (ENG),
    INDEX IDX_SUBCATEGORIES_VI (VI)
);

-- Bảng tựa đề: TITLES
DROP TABLE IF EXISTS `BOOKS`;
CREATE TABLE BOOKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(100) NOT NULL,
	SLUG VARCHAR(100),
    ENG VARCHAR(500) NOT NULL,
	VI VARCHAR(500) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
	IMG VARCHAR(255),
    SUBCATEGORY_SLUG VARCHAR(100) NOT NULL,
	CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
    UPDATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
	NUMBER INT,
	LEVEL INT,
	INDEX IDX_BOOKS_ENG (ENG),
	INDEX IDX_BOOKS_VI (VI)
);

-- Bảng tập: Volumes
DROP TABLE IF EXISTS `VOLUMES`;
CREATE TABLE VOLUMES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(100) NOT NULL,
	SLUG VARCHAR(100),
    ENG VARCHAR(500) NOT NULL,
    VI VARCHAR(500) NOT NULL,
	AUDIO VARCHAR(255) NULL DEFAULT NULL,
	IMG VARCHAR(255),
	START_TIME VARCHAR(100) NULL DEFAULT NULL,
    END_TIME VARCHAR(100) NULL DEFAULT NULL,
    BOOK_SLUG VARCHAR(100) NOT NULL,
    CHECKED VARCHAR(100) NOT NULL,
	CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
    UPDATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
	NUMBER INT,
	INDEX IDX_VOLUMES_ENG (ENG),
    INDEX IDX_VOLUMES_VI (VI),
    INDEX IDX_VOLUMES_CHECKED (CHECKED),
	INDEX IDX_VOLUMES_SLUG (SLUG),
	INDEX IDX_VOLUMES_BOOK_SLUG (BOOK_SLUG)
);

DROP TABLE IF EXISTS `CONTENTS`;
CREATE TABLE `CONTENTS`  (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENG VARCHAR(1000) NOT NULL,
    VI VARCHAR(1000) NOT NULL,
    START_TIME varchar(100) NULL DEFAULT NULL,
    END_TIME varchar(100) NULL DEFAULT NULL,
    VOLUME_SLUG VARCHAR(100) NOT NULL,
	CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
    CREATED_BY VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI NULL DEFAULT NULL,
	INDEX IDX_CONTENTS_ENG (ENG),
    INDEX IDX_CONTENTS_VI (VI),
	INDEX IDX_CONTENTS_VOLUME_SLUG (VOLUME_SLUG)
);
DROP TABLE IF EXISTS `WORDS`;
CREATE TABLE `WORDS` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENG VARCHAR(200) NOT NULL,
    VI VARCHAR(200) NOT NULL,
    CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
	INDEX `IDX_WORD_ENG`(`ENG`) USING BTREE,
	INDEX `IDX_WORD_VI`(`VI`) USING BTREE
);


DROP TABLE IF EXISTS `GOLD_INVESTMENTS`;
CREATE TABLE GOLD_INVESTMENTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	INITIAL_CAPITAL DECIMAL(15,2), -- SỐ VỐN ĐẦU TƯ BAN ĐẦU
    GOLD_PRICE DECIMAL(15,2), -- GIÁ MUA VÀO MỖI CÂY VÀNG
    GOLD_QUANTITY DECIMAL(4,1), -- SỐ LƯỢNG CÂY VÀNG MUA
    GOLD_TYPE ENUM('Miếng', 'Nhẫn') NOT NULL, -- LOẠI VÀNG (MIẾNG HOẶC NHẪN)
    PURCHASE_DATE DATE,
	COMMENT VARCHAR(500)
);


INSERT INTO GOLD_INVESTMENTS (INITIAL_CAPITAL, GOLD_PRICE, GOLD_QUANTITY, GOLD_TYPE, PURCHASE_DATE, COMMENT)
VALUES 
(1150800000, 82200000, 14, 'Miếng', '2024-07-20', 'Giá vàng lúc đó là 78 triệu thấp hơn mua ở quán là 82.2 triệu'),
(170000000, 85000000, 2, 'Nhẫn', '2024-11-04', 'Giá nhẫn lúc đó là 87 triệu cao hơn mua ở quán là 85 triệu'),
(102200000, 102200000, 1, 'Nhẫn', '2025-04-03','Giá vàng lúc đó là 102.2 triệu cao hơn mua ở quán thực ra là 99.2 triệu'),
(58200000, 58200000, 0.5, 'Nhẫn', '2025-05-16','Giá vàng lúc đó là 116.4 triệu'),
(117750000, 117750000, 1, 'Miếng', '2025-06-02', 'Giá vàng lúc đó là 117.75 triệu'),
(10000000, 10000000, 0.1, 'Nhẫn', '2025-06-02', 'Giá vàng lúc đó là 113.7 triệu'),
(514400000, 128600000, 4, 'Miếng', '2025-08-24', 'Giá vàng lúc đó là 126.6 nhưng ngoài tiệm là 128.6 triệu'),
(132500000, 132500000, 1, 'Miếng', '2025-09-14', 'Giá vàng lúc đó là 131.1 nhưng ngoài tiệm là 132.5 triệu');

