DROP TABLE IF EXISTS `MISSING_WORDS`;
CREATE TABLE `MISSING_WORDS`  (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `ENG` varchar(200) NOT NULL, 
  `CREATED_AT` datetime(6) NULL DEFAULT NULL,
  `UPDATED_AT` datetime(6) NULL DEFAULT NULL,
  INDEX `IDX_WORD_ENG`(`ENG`) USING BTREE
);
TRUNCATE TABLE `MISSING_WORDS`;

INSERT INTO `MISSING_WORDS` (`ENG`) VALUES 
    ('the'),
    ('this'),
    ('he'),
    ('she'),
    ('it'),
    ('is'),
    ('are'),
    ('of'),
    ('their'),
    ('his'),
    ('her'),
    ('a'),
    ('an'),
    ('was'),
    ('were'),
    ('am'),
    ('will'),
    ('would'),
    ('shall'),
    ('should'),
    ('can'),
    ('could'),
    ('may'),
    ('might'),
    ('must'),
    ('have'),
    ('has'),
    ('had'),
    ('do'),
    ('does'),
    ('did'),
    ('to'),
    ('in'),
    ('on'),
    ('at'),
    ('with'),
    ('for'),
    ('from'),
    ('by'),
    ('as'),
    ('about'),
    ('into'),
    ('over'),
    ('under'),
    ('up'),
    ('down'),
    ('out'),
    ('and'),
    ('or'),
    ('but'),
    ('if'),
    ('because'),
    ('so'),
    ('that'),
    ('these'),
    ('those'),
    ('we'),
    ('you'),
    ('they'),
    ('our'),
    ('us'),
    ('them'),
    ('its'),
    ('my'),
    ('your'),
    ('mine'),
    ('yours'),
    ('ours'),
    ('theirs'),
	('him'),
	('hers'),
	('itself'),
	('ourselves'),
	('themselves'),
	('yourself'),
	('yourselves'),
	('oh'),
	('ah'),
	('be'),
	('been'),
	('ones'),
	('huh');
	