INSERT INTO QUESTIONS (QUESTION_CODE, VOLUME_SLUG, QUESTION_TEXT, QUESTION_TEXT_VI, STATUS, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES
	/* (UUID(),'esl-fast-beginner-1-1','Going to the Zoo','Đi tới sở thú','BEGINNER_01_ESL_FAST_CHILDREN_001.mp3',NULL,'00:00:00.000','00:00:37.000','esl-fast-children-1',1,1,1,1), */
    ('Q-esl-fast-beginner-1-1-001', 'esl-fast-beginner-1-1', 'Where does she go?', 'Cô bé đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-002', 'esl-fast-beginner-1-1', 'What does she see at the zoo?', 'Cô bé nhìn thấy gì ở sở thú?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-003', 'esl-fast-beginner-1-1', 'What animal does she see first?', 'Cô bé nhìn thấy con vật nào đầu tiên?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-004', 'esl-fast-beginner-1-1', 'What does the lion do?', 'Con sư tử làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-005', 'esl-fast-beginner-1-1', 'What animal does she see after the lion?', 'Sau con sư tử, cô bé nhìn thấy con vật nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-006', 'esl-fast-beginner-1-1', 'What does the elephant have?', 'Con voi có gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-007', 'esl-fast-beginner-1-1', 'How is the elephant''s trunk?', 'Chiếc vòi của con voi như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-008', 'esl-fast-beginner-1-1', 'What animal does she see after the elephant?', 'Sau con voi, cô bé nhìn thấy con vật nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-009', 'esl-fast-beginner-1-1', 'How is the turtle?', 'Con rùa như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-010', 'esl-fast-beginner-1-1', 'What animal does she see after the turtle?', 'Sau con rùa, cô bé nhìn thấy con vật nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-011', 'esl-fast-beginner-1-1', 'What does the rabbit have?', 'Con thỏ có gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-012', 'esl-fast-beginner-1-1', 'How is the rabbit''s fur?', 'Bộ lông của con thỏ như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-013', 'esl-fast-beginner-1-1', 'What animal does she see last?', 'Cô bé nhìn thấy con vật nào cuối cùng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-014', 'esl-fast-beginner-1-1', 'What is the gorilla doing?', 'Con khỉ đột đang làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-015', 'esl-fast-beginner-1-1', 'What is the gorilla eating?', 'Con khỉ đột đang ăn gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-016', 'esl-fast-beginner-1-1', 'Where does she see the lion?', 'Cô bé nhìn thấy con sư tử ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-017', 'esl-fast-beginner-1-1', 'Where does she see the elephant?', 'Cô bé nhìn thấy con voi ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-018', 'esl-fast-beginner-1-1', 'Where does she see the turtle?', 'Cô bé nhìn thấy con rùa ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-019', 'esl-fast-beginner-1-1', 'Where does she see the rabbit?', 'Cô bé nhìn thấy con thỏ ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-020', 'esl-fast-beginner-1-1', 'Where does she see the gorilla?', 'Cô bé nhìn thấy con khỉ đột ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-021', 'esl-fast-beginner-1-1', 'Which animal roars?', 'Con vật nào gầm lên?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-022', 'esl-fast-beginner-1-1', 'Which animal has a long trunk?', 'Con vật nào có chiếc vòi dài?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-023', 'esl-fast-beginner-1-1', 'Which animal is slow?', 'Con vật nào chậm chạp?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-024', 'esl-fast-beginner-1-1', 'Which animal has soft fur?', 'Con vật nào có bộ lông mềm mại?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-025', 'esl-fast-beginner-1-1', 'Which animal is eating a banana?', 'Con vật nào đang ăn một quả chuối?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-026', 'esl-fast-beginner-1-1', 'How many animals does she see?', 'Cô bé nhìn thấy bao nhiêu con vật?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-027', 'esl-fast-beginner-1-1', 'What does she see after the lion roars?', 'Sau khi con sư tử gầm lên, cô bé nhìn thấy gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-028', 'esl-fast-beginner-1-1', 'What does she see before the gorilla?', 'Trước khi nhìn thấy con khỉ đột, cô bé nhìn thấy con gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-029', 'esl-fast-beginner-1-1', 'What does the rabbit''s fur feel like?', 'Bộ lông của con thỏ như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-1-030', 'esl-fast-beginner-1-1', 'What does the girl see at the zoo?', 'Cô bé nhìn thấy gì ở sở thú?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-2','Christmas Time','Giáng sinh','BEGINNER_01_ESL_FAST_CHILDREN_002.mp3',NULL,'00:00:00.000','00:00:35.000','esl-fast-children-1',1,1,1,2), */
	('Q-esl-fast-beginner-1-2-001', 'esl-fast-beginner-1-2', 'What holiday is it?', 'Đó là ngày lễ gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-002', 'esl-fast-beginner-1-2', 'Who gives Tim a toy?', 'Ai tặng Tim một món đồ chơi?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-003', 'esl-fast-beginner-1-2', 'What does Dad give Tim?', 'Bố tặng Tim cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-004', 'esl-fast-beginner-1-2', 'Where is the toy?', 'Món đồ chơi ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-005', 'esl-fast-beginner-1-2', 'What does Tim take off?', 'Tim mở cái gì ra?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-006', 'esl-fast-beginner-1-2', 'What does Tim see?', 'Tim nhìn thấy gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-007', 'esl-fast-beginner-1-2', 'What is the toy?', 'Món đồ chơi là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-008', 'esl-fast-beginner-1-2', 'What color is the car?', 'Chiếc xe có màu gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-009', 'esl-fast-beginner-1-2', 'What does the car make?', 'Chiếc xe phát ra gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-010', 'esl-fast-beginner-1-2', 'How does the car move?', 'Chiếc xe chạy như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-011', 'esl-fast-beginner-1-2', 'Does Tim like the gift?', 'Tim có thích món quà không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-012', 'esl-fast-beginner-1-2', 'Who does Tim hug?', 'Tim ôm ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-013', 'esl-fast-beginner-1-2', 'Who smiles at the end?', 'Ai mỉm cười ở cuối câu chuyện?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-014', 'esl-fast-beginner-1-2', 'When does Dad give Tim a toy?', 'Khi nào bố tặng Tim một món đồ chơi?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-015', 'esl-fast-beginner-1-2', 'What is inside the box?', 'Có gì bên trong hộp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-016', 'esl-fast-beginner-1-2', 'What does Tim do with the lid?', 'Tim làm gì với nắp hộp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-017', 'esl-fast-beginner-1-2', 'What does Tim see after he takes off the lid?', 'Tim nhìn thấy gì sau khi mở nắp hộp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-018', 'esl-fast-beginner-1-2', 'Is the toy a car?', 'Món đồ chơi có phải là một chiếc xe không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-019', 'esl-fast-beginner-1-2', 'Is the car red?', 'Chiếc xe có màu đỏ không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-020', 'esl-fast-beginner-1-2', 'Does the car make noises?', 'Chiếc xe có phát ra tiếng ồn không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-021', 'esl-fast-beginner-1-2', 'Does the car move fast?', 'Chiếc xe có chạy nhanh không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-022', 'esl-fast-beginner-1-2', 'How does Tim feel about the gift?', 'Tim cảm thấy thế nào về món quà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-023', 'esl-fast-beginner-1-2', 'What does Tim do when he likes the gift?', 'Tim làm gì khi cậu bé thích món quà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-024', 'esl-fast-beginner-1-2', 'Who does Tim hug after receiving the gift?', 'Tim ôm ai sau khi nhận món quà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-025', 'esl-fast-beginner-1-2', 'What does Dad do after Tim hugs him?', 'Bố làm gì sau khi Tim ôm bố?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-026', 'esl-fast-beginner-1-2', 'What kind of toy does Tim get?', 'Tim nhận được loại đồ chơi gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-027', 'esl-fast-beginner-1-2', 'Where does Tim find the car?', 'Tim tìm thấy chiếc xe ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-028', 'esl-fast-beginner-1-2', 'What happens when Tim takes off the lid?', 'Điều gì xảy ra khi Tim mở nắp hộp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-029', 'esl-fast-beginner-1-2', 'Why does Tim hug Dad?', 'Tại sao Tim ôm bố?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-2-030', 'esl-fast-beginner-1-2', 'What does Dad do at the end of the story?', 'Bố làm gì ở cuối câu chuyện?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-3','She Goes to the Nurse','Cô ấy đến gặp y tá','BEGINNER_01_ESL_FAST_CHILDREN_003.mp3',NULL,'00:00:00.000','00:00:35.000','esl-fast-children-1',1,1,1,3), */
	('Q-esl-fast-beginner-1-3-001', 'esl-fast-beginner-1-3', 'Where does she go?', 'Cô bé đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-002', 'esl-fast-beginner-1-3', 'What does she go out to do?', 'Cô bé ra ngoài để làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-003', 'esl-fast-beginner-1-3', 'What does she do outside?', 'Cô bé làm gì ở bên ngoài?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-004', 'esl-fast-beginner-1-3', 'What happens to her?', 'Điều gì xảy ra với cô bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-005', 'esl-fast-beginner-1-3', 'Does she fall down?', 'Cô bé có bị ngã không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-006', 'esl-fast-beginner-1-3', 'How does she feel after she falls?', 'Cô bé cảm thấy thế nào sau khi ngã?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-007', 'esl-fast-beginner-1-3', 'What does she do when it hurts?', 'Cô bé làm gì khi bị đau?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-008', 'esl-fast-beginner-1-3', 'Does she cry?', 'Cô bé có khóc không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-009', 'esl-fast-beginner-1-3', 'What does she do after crying?', 'Cô bé làm gì sau khi khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-010', 'esl-fast-beginner-1-3', 'Who does she go to see?', 'Cô bé đi gặp ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-011', 'esl-fast-beginner-1-3', 'Where does she go after she falls?', 'Cô bé đi đâu sau khi bị ngã?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-012', 'esl-fast-beginner-1-3', 'Is the nurse nice?', 'Y tá có tốt bụng không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-013', 'esl-fast-beginner-1-3', 'How does the nurse look?', 'Y tá trông như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-014', 'esl-fast-beginner-1-3', 'Is the nurse friendly?', 'Y tá có thân thiện không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-015', 'esl-fast-beginner-1-3', 'What does the nurse give her?', 'Y tá cho cô bé cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-016', 'esl-fast-beginner-1-3', 'What kind of candy does the nurse give her?', 'Y tá cho cô bé loại kẹo gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-017', 'esl-fast-beginner-1-3', 'Does the lollipop taste good?', 'Cây kẹo mút có ngon không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-018', 'esl-fast-beginner-1-3', 'What does the nurse give her for the wound?', 'Y tá cho cô bé gì để băng vết thương?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-019', 'esl-fast-beginner-1-3', 'Does the nurse give her a bandage?', 'Y tá có băng vết thương cho cô bé không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-020', 'esl-fast-beginner-1-3', 'How does she feel after seeing the nurse?', 'Cô bé cảm thấy thế nào sau khi gặp y tá?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-021', 'esl-fast-beginner-1-3', 'Is she okay now?', 'Bây giờ cô bé đã ổn chưa?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-022', 'esl-fast-beginner-1-3', 'Where does she walk back to?', 'Cô bé đi bộ trở lại đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-023', 'esl-fast-beginner-1-3', 'What does she do at the end?', 'Cuối cùng cô bé làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-024', 'esl-fast-beginner-1-3', 'Why does she go to the nurse?', 'Tại sao cô bé đi gặp y tá?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-025', 'esl-fast-beginner-1-3', 'Why does she cry?', 'Tại sao cô bé khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-026', 'esl-fast-beginner-1-3', 'What happens before she goes to the nurse?', 'Điều gì xảy ra trước khi cô bé đi gặp y tá?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-027', 'esl-fast-beginner-1-3', 'What happens after she gets up?', 'Điều gì xảy ra sau khi cô bé đứng dậy?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-028', 'esl-fast-beginner-1-3', 'Who gives her a lollipop?', 'Ai cho cô bé một cây kẹo mút?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-029', 'esl-fast-beginner-1-3', 'Who gives her a bandage?', 'Ai băng vết thương cho cô bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-3-030', 'esl-fast-beginner-1-3', 'What does she do after she is okay?', 'Cô bé làm gì sau khi đã ổn?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-4','Waiting','Chờ đợi','BEGINNER_01_ESL_FAST_CHILDREN_004.mp3',NULL,'00:00:00.000','00:00:33.000','esl-fast-children-1',1,1,1,4), */
	('Q-esl-fast-beginner-1-4-001', 'esl-fast-beginner-1-4', 'Where are the kids?', 'Bọn trẻ đang ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-002', 'esl-fast-beginner-1-4', 'Who is teaching the kids?', 'Ai đang dạy bọn trẻ?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-003', 'esl-fast-beginner-1-4', 'What is the teacher teaching?', 'Giáo viên đang dạy môn gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-004', 'esl-fast-beginner-1-4', 'How do the kids feel?', 'Bọn trẻ cảm thấy thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-005', 'esl-fast-beginner-1-4', 'Are the kids tired?', 'Bọn trẻ có mệt không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-006', 'esl-fast-beginner-1-4', 'What do the kids want to do?', 'Bọn trẻ muốn làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-007', 'esl-fast-beginner-1-4', 'What do they want to see?', 'Chúng muốn nhìn thấy gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-008', 'esl-fast-beginner-1-4', 'Do they want to see the sun?', 'Chúng có muốn nhìn thấy mặt trời không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-009', 'esl-fast-beginner-1-4', 'What do they like?', 'Chúng thích gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-010', 'esl-fast-beginner-1-4', 'Do they like slides?', 'Chúng có thích cầu trượt không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-011', 'esl-fast-beginner-1-4', 'Do they like swings?', 'Chúng có thích xích đu không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-012', 'esl-fast-beginner-1-4', 'What do they not like?', 'Chúng không thích gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-013', 'esl-fast-beginner-1-4', 'Do they like math?', 'Chúng có thích môn toán không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-014', 'esl-fast-beginner-1-4', 'What do they stare at?', 'Chúng nhìn chằm chằm vào cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-015', 'esl-fast-beginner-1-4', 'What moves slowly?', 'Cái gì chuyển động chậm?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-016', 'esl-fast-beginner-1-4', 'How does the clock move?', 'Đồng hồ chuyển động như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-017', 'esl-fast-beginner-1-4', 'What are the kids waiting for?', 'Bọn trẻ đang chờ điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-018', 'esl-fast-beginner-1-4', 'Do the kids continue to wait?', 'Bọn trẻ có tiếp tục chờ không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-019', 'esl-fast-beginner-1-4', 'Where do the kids want to play?', 'Bọn trẻ muốn chơi ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-020', 'esl-fast-beginner-1-4', 'Why do the kids want to go outside?', 'Tại sao bọn trẻ muốn ra ngoài?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-021', 'esl-fast-beginner-1-4', 'Why are the kids tired?', 'Tại sao bọn trẻ mệt mỏi?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-022', 'esl-fast-beginner-1-4', 'What subject are they learning?', 'Chúng đang học môn gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-023', 'esl-fast-beginner-1-4', 'What do they want to do instead of math?', 'Chúng muốn làm gì thay vì học toán?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-024', 'esl-fast-beginner-1-4', 'What playground equipment do they like?', 'Chúng thích những thiết bị vui chơi nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-025', 'esl-fast-beginner-1-4', 'What are they looking at while they wait?', 'Chúng nhìn vào đâu trong khi chờ đợi?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-026', 'esl-fast-beginner-1-4', 'Does the clock move quickly?', 'Đồng hồ có chạy nhanh không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-027', 'esl-fast-beginner-1-4', 'Who does not like math?', 'Ai không thích môn toán?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-028', 'esl-fast-beginner-1-4', 'What do the kids want to see outside?', 'Bọn trẻ muốn nhìn thấy gì ở bên ngoài?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-029', 'esl-fast-beginner-1-4', 'What do the kids do while the clock moves slowly?', 'Bọn trẻ làm gì khi đồng hồ chạy chậm?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-4-030', 'esl-fast-beginner-1-4', 'What do the kids continue to do?', 'Bọn trẻ tiếp tục làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-5','Chores','Việc nhà','BEGINNER_01_ESL_FAST_CHILDREN_005.mp3',NULL,'00:00:00.000','00:00:31.000','esl-fast-children-1',1,1,1,5) */
	('Q-esl-fast-beginner-1-5-001','esl-fast-beginner-1-5','What is he playing?','Cậu bé đang chơi gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-002','esl-fast-beginner-1-5','What is Mom doing?','Mẹ đang làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-003','esl-fast-beginner-1-5','Who gets mad?','Ai tức giận?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-004','esl-fast-beginner-1-5','How does Mom feel?','Mẹ cảm thấy thế nào?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-005','esl-fast-beginner-1-5','What does Mom think about him?','Mẹ nghĩ gì về cậu bé?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-006','esl-fast-beginner-1-5','What does Mom think he is?','Mẹ nghĩ cậu bé là người như thế nào?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-007','esl-fast-beginner-1-5','What does she give him?','Mẹ đưa cho cậu bé cái gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-008','esl-fast-beginner-1-5','What is on the list?','Có gì trên danh sách?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-009','esl-fast-beginner-1-5','How does he react to the list?','Cậu bé phản ứng thế nào với danh sách?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-010','esl-fast-beginner-1-5','What does he do when he sees the list?','Cậu bé làm gì khi nhìn thấy danh sách?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-011','esl-fast-beginner-1-5','What does he have to clean?','Cậu bé phải lau gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-012','esl-fast-beginner-1-5','Does he have to clean the floors?','Cậu bé có phải lau sàn nhà không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-013','esl-fast-beginner-1-5','What does he have to wash?','Cậu bé phải rửa gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-014','esl-fast-beginner-1-5','When does he wash the dishes?','Khi nào cậu bé rửa bát đĩa?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-015','esl-fast-beginner-1-5','What does he have to feed?','Cậu bé phải cho con gì ăn?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-016','esl-fast-beginner-1-5','Who does he feed?','Cậu bé cho ai ăn?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-017','esl-fast-beginner-1-5','What does he do finally?','Cuối cùng cậu bé làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-018','esl-fast-beginner-1-5','Does he feed the dog?','Cậu bé có cho chó ăn không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-019','esl-fast-beginner-1-5','What does he start doing?','Cậu bé bắt đầu làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-020','esl-fast-beginner-1-5','Does he start doing his chores?','Cậu bé có bắt đầu làm việc nhà không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-021','esl-fast-beginner-1-5','What is he doing at the beginning?','Lúc đầu cậu bé đang làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-022','esl-fast-beginner-1-5','Who thinks he is lazy?','Ai nghĩ cậu bé lười biếng?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-023','esl-fast-beginner-1-5','What does Mom give him to do?','Mẹ đưa cho cậu bé những việc gì để làm?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-024','esl-fast-beginner-1-5','What does he look at?','Cậu bé nhìn vào cái gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-025','esl-fast-beginner-1-5','What chore comes first?','Việc nhà nào được làm đầu tiên?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-026','esl-fast-beginner-1-5','What chore comes next?','Việc nhà nào tiếp theo?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-027','esl-fast-beginner-1-5','What chore comes last?','Việc nhà nào cuối cùng?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-028','esl-fast-beginner-1-5','What does he have to do with the floors?','Cậu bé phải làm gì với sàn nhà?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-029','esl-fast-beginner-1-5','What does he have to do with the dishes?','Cậu bé phải làm gì với bát đĩa?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-5-030','esl-fast-beginner-1-5','What does he do after looking at the list?','Sau khi nhìn vào danh sách, cậu bé làm gì?','ACTIVE',NULL,NULL,NULL,NULL);

INSERT INTO QUESTIONS (QUESTION_CODE, VOLUME_SLUG, QUESTION_TEXT, QUESTION_TEXT_VI, STATUS, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES
	/* (UUID(),'esl-fast-beginner-1-6','The First Song','Bài hát đầu tiên','BEGINNER_01_ESL_FAST_CHILDREN_006.mp3',NULL,'00:00:00.000','00:00:30.000','esl-fast-children-1',1,1,1,6), */
	('Q-esl-fast-beginner-1-6-001', 'esl-fast-beginner-1-6', 'Where does she sit?', 'Cô bé ngồi ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-002', 'esl-fast-beginner-1-6', 'Who turns on the radio?', 'Ai bật radio?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-003', 'esl-fast-beginner-1-6', 'What does her dad turn on?', 'Bố cô bé bật gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-004', 'esl-fast-beginner-1-6', 'What plays on the radio?', 'Điều gì phát trên radio?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-005', 'esl-fast-beginner-1-6', 'What does she tap?', 'Cô bé gõ nhịp bằng gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-006', 'esl-fast-beginner-1-6', 'What does she do with her feet?', 'Cô bé làm gì bằng chân?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-007', 'esl-fast-beginner-1-6', 'What does she sway?', 'Cô bé lắc lư cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-008', 'esl-fast-beginner-1-6', 'Who laughs at her?', 'Ai bật cười với cô bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-009', 'esl-fast-beginner-1-6', 'Why does her dad laugh?', 'Tại sao bố cô bé bật cười?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-010', 'esl-fast-beginner-1-6', 'Does her dad like the song?', 'Bố cô bé có thích bài hát không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-011', 'esl-fast-beginner-1-6', 'Who likes the song, too?', 'Ai cũng thích bài hát?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-012', 'esl-fast-beginner-1-6', 'What happens after the song plays?', 'Điều gì xảy ra sau khi bài hát phát?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-013', 'esl-fast-beginner-1-6', 'What happens to the song?', 'Điều gì xảy ra với bài hát?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-014', 'esl-fast-beginner-1-6', 'What does the radio play next?', 'Sau đó radio phát gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-015', 'esl-fast-beginner-1-6', 'Is the second song the same song?', 'Bài hát thứ hai có giống bài hát trước không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-016', 'esl-fast-beginner-1-6', 'Does she like the new song?', 'Cô bé có thích bài hát mới không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-017', 'esl-fast-beginner-1-6', 'What does she do when she does not like the new song?', 'Cô bé làm gì khi không thích bài hát mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-018', 'esl-fast-beginner-1-6', 'Where is she when her dad turns on the radio?', 'Cô bé ở đâu khi bố bật radio?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-019', 'esl-fast-beginner-1-6', 'What does she do when the first song plays?', 'Cô bé làm gì khi bài hát đầu tiên phát?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-020', 'esl-fast-beginner-1-6', 'Does she sit quietly at the beginning?', 'Lúc đầu cô bé có ngồi im lặng không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-021', 'esl-fast-beginner-1-6', 'What does her dad do when he sees her?', 'Bố cô bé làm gì khi nhìn thấy cô bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-022', 'esl-fast-beginner-1-6', 'How does she move to the first song?', 'Cô bé chuyển động theo bài hát đầu tiên như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-023', 'esl-fast-beginner-1-6', 'What does she tap while listening to the song?', 'Cô bé gõ nhịp bằng gì khi nghe bài hát?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-024', 'esl-fast-beginner-1-6', 'What does she sway while listening to the song?', 'Cô bé lắc lư cái gì khi nghe bài hát?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-025', 'esl-fast-beginner-1-6', 'What does her dad think about the first song?', 'Bố cô bé nghĩ gì về bài hát đầu tiên?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-026', 'esl-fast-beginner-1-6', 'What happens after her dad laughs?', 'Điều gì xảy ra sau khi bố cô bé bật cười?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-027', 'esl-fast-beginner-1-6', 'What happens after the first song is over?', 'Điều gì xảy ra sau khi bài hát đầu tiên kết thúc?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-028', 'esl-fast-beginner-1-6', 'How does she feel about the new song?', 'Cô bé cảm thấy thế nào về bài hát mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-029', 'esl-fast-beginner-1-6', 'What does she do at the end?', 'Cuối cùng cô bé làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-6-030', 'esl-fast-beginner-1-6', 'What does she do after the radio plays a different song?', 'Cô bé làm gì sau khi radio phát một bài hát khác?', 'ACTIVE', NULL, NULL, NULL, NULL),

	/* (UUID(),'esl-fast-beginner-1-7','Visiting the Doctor','Đi khám bác sĩ','BEGINNER_01_ESL_FAST_CHILDREN_007.mp3',NULL,'00:00:00.000','00:00:37.000','esl-fast-children-1',1,1,1,7), */
	('Q-esl-fast-beginner-1-7-001', 'esl-fast-beginner-1-7', 'How does Hayley feel?', 'Hayley cảm thấy thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-002', 'esl-fast-beginner-1-7', 'What does Hayley feel?', 'Hayley cảm thấy gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-003', 'esl-fast-beginner-1-7', 'Who touches Hayley''s forehead?', 'Ai chạm vào trán Hayley?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-004', 'esl-fast-beginner-1-7', 'What does her mom touch?', 'Mẹ cô bé chạm vào đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-005', 'esl-fast-beginner-1-7', 'What is wrong with Hayley?', 'Hayley bị làm sao?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-006', 'esl-fast-beginner-1-7', 'Does Hayley have a fever?', 'Hayley có bị sốt không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-007', 'esl-fast-beginner-1-7', 'Who takes Hayley to a doctor?', 'Ai đưa Hayley đi khám bác sĩ?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-008', 'esl-fast-beginner-1-7', 'Where does her mom take Hayley?', 'Mẹ cô bé đưa Hayley đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-009', 'esl-fast-beginner-1-7', 'What is the doctor like?', 'Bác sĩ là người như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-010', 'esl-fast-beginner-1-7', 'Is the doctor kind?', 'Bác sĩ có ân cần không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-011', 'esl-fast-beginner-1-7', 'What does the doctor give Hayley?', 'Bác sĩ cho Hayley cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-012', 'esl-fast-beginner-1-7', 'Who gives Hayley a sticker?', 'Ai tặng Hayley một miếng sticker?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-013', 'esl-fast-beginner-1-7', 'What does the doctor tell Hayley to take?', 'Bác sĩ dặn Hayley uống gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-014', 'esl-fast-beginner-1-7', 'Does the doctor tell her to take a pill?', 'Bác sĩ có dặn cô bé uống thuốc không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-015', 'esl-fast-beginner-1-7', 'What does the doctor tell Hayley to drink?', 'Bác sĩ dặn Hayley uống gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-016', 'esl-fast-beginner-1-7', 'How much water does the doctor tell her to drink?', 'Bác sĩ dặn cô bé uống bao nhiêu nước?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-017', 'esl-fast-beginner-1-7', 'Where does Hayley go after seeing the doctor?', 'Hayley đi đâu sau khi gặp bác sĩ?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-018', 'esl-fast-beginner-1-7', 'Does Hayley go home?', 'Hayley có về nhà không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-019', 'esl-fast-beginner-1-7', 'What does Hayley do at home?', 'Hayley làm gì ở nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-020', 'esl-fast-beginner-1-7', 'What does she take?', 'Cô bé uống gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-021', 'esl-fast-beginner-1-7', 'What does she drink?', 'Cô bé uống gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-022', 'esl-fast-beginner-1-7', 'How long does she take the pill and drink water?', 'Cô bé uống thuốc và uống nước trong bao lâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-023', 'esl-fast-beginner-1-7', 'Does she do this for three days?', 'Cô bé có làm như vậy trong ba ngày không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-024', 'esl-fast-beginner-1-7', 'What happens after three days?', 'Điều gì xảy ra sau ba ngày?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-025', 'esl-fast-beginner-1-7', 'Is Hayley healthy again?', 'Hayley có khỏe lại không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-026', 'esl-fast-beginner-1-7', 'Why does Hayley see a doctor?', 'Tại sao Hayley đi khám bác sĩ?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-027', 'esl-fast-beginner-1-7', 'What does Hayley do after the doctor tells her to take a pill?', 'Hayley làm gì sau khi bác sĩ dặn uống thuốc?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-028', 'esl-fast-beginner-1-7', 'What does Hayley do after the doctor tells her to drink water?', 'Hayley làm gì sau khi bác sĩ dặn uống nước?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-029', 'esl-fast-beginner-1-7', 'Who helps Hayley when she has a fever?', 'Ai giúp Hayley khi cô bé bị sốt?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-7-030', 'esl-fast-beginner-1-7', 'What does Hayley do for three days?', 'Hayley làm gì trong ba ngày?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-8','Different Foods','Các loại thức ăn khác nhau','BEGINNER_01_ESL_FAST_CHILDREN_008.mp3',NULL,'00:00:00.000','00:00:34.000','esl-fast-children-1',1,1,1,8), */
	('Q-esl-fast-beginner-1-8-001', 'esl-fast-beginner-1-8', 'How does Sarah feel?', 'Sarah cảm thấy thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-002', 'esl-fast-beginner-1-8', 'Why does Sarah go to the kitchen?', 'Tại sao Sarah đi vào bếp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-003', 'esl-fast-beginner-1-8', 'Where does Sarah go?', 'Sarah đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-004', 'esl-fast-beginner-1-8', 'What does she open?', 'Cô bé mở gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-005', 'esl-fast-beginner-1-8', 'Where does she find a lot of snacks?', 'Cô bé tìm thấy rất nhiều đồ ăn vặt ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-006', 'esl-fast-beginner-1-8', 'What is in the cabinet?', 'Có gì trong tủ?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-007', 'esl-fast-beginner-1-8', 'How are the marshmallows?', 'Kẹo dẻo như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-008', 'esl-fast-beginner-1-8', 'Are the marshmallows too sweet?', 'Kẹo dẻo có quá ngọt không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-009', 'esl-fast-beginner-1-8', 'How are the potato chips?', 'Khoai tây chiên như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-010', 'esl-fast-beginner-1-8', 'Are the potato chips too salty?', 'Khoai tây chiên có quá mặn không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-011', 'esl-fast-beginner-1-8', 'How is the ice cream?', 'Kem như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-012', 'esl-fast-beginner-1-8', 'Is the ice cream too watery?', 'Kem có quá loãng không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-013', 'esl-fast-beginner-1-8', 'How are the kiwis?', 'Kiwi như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-014', 'esl-fast-beginner-1-8', 'Are the kiwis too sour?', 'Kiwi có quá chua không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-015', 'esl-fast-beginner-1-8', 'How is the cereal?', 'Ngũ cốc như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-016', 'esl-fast-beginner-1-8', 'Is the cereal too sweet?', 'Ngũ cốc có quá ngọt không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-017', 'esl-fast-beginner-1-8', 'What does Sarah think about the snacks?', 'Sarah nghĩ gì về những món ăn vặt?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-018', 'esl-fast-beginner-1-8', 'Who comes home?', 'Ai trở về nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-019', 'esl-fast-beginner-1-8', 'When does her dad come home?', 'Khi nào bố cô bé trở về nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-020', 'esl-fast-beginner-1-8', 'What does her dad give her?', 'Bố cô bé đưa cho cô bé gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-021', 'esl-fast-beginner-1-8', 'Who gives Sarah crackers?', 'Ai đưa bánh quy cho Sarah?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-022', 'esl-fast-beginner-1-8', 'What does Sarah eat at the end?', 'Cuối cùng Sarah ăn gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-023', 'esl-fast-beginner-1-8', 'How are the crackers?', 'Những chiếc bánh quy như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-024', 'esl-fast-beginner-1-8', 'Does Sarah like the crackers?', 'Sarah có thích bánh quy không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-025', 'esl-fast-beginner-1-8', 'Which snack is too sweet?', 'Món ăn vặt nào quá ngọt?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-026', 'esl-fast-beginner-1-8', 'Which snack is too salty?', 'Món ăn vặt nào quá mặn?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-027', 'esl-fast-beginner-1-8', 'Which snack is too sour?', 'Món ăn vặt nào quá chua?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-028', 'esl-fast-beginner-1-8', 'Which snack is too bland?', 'Món ăn vặt nào quá nhạt?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-029', 'esl-fast-beginner-1-8', 'What happens after Sarah opens the cabinet?', 'Điều gì xảy ra sau khi Sarah mở tủ?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-8-030', 'esl-fast-beginner-1-8', 'What happens after her dad comes home?', 'Điều gì xảy ra sau khi bố cô bé trở về nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-9','The Corner','Góc phố','BEGINNER_01_ESL_FAST_CHILDREN_009.mp3',NULL,'00:00:00.000','00:00:31.000','esl-fast-children-1',1,1,1,9), */
	('Q-esl-fast-beginner-1-9-001', 'esl-fast-beginner-1-9', 'What does Jill not like?', 'Jill không thích điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-002', 'esl-fast-beginner-1-9', 'Does Jill like math?', 'Jill có thích môn toán không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-003', 'esl-fast-beginner-1-9', 'What does Jill start talking about?', 'Jill bắt đầu nói chuyện về điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-004', 'esl-fast-beginner-1-9', 'Who laughs?', 'Ai bật cười?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-005', 'esl-fast-beginner-1-9', 'What do Jill''s friends do?', 'Bạn bè của Jill làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-006', 'esl-fast-beginner-1-9', 'What do they stop doing?', 'Họ ngừng làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-007', 'esl-fast-beginner-1-9', 'What are they doing before they stop?', 'Trước khi dừng lại, họ đang làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-008', 'esl-fast-beginner-1-9', 'How does the teacher feel?', 'Cô giáo cảm thấy thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-009', 'esl-fast-beginner-1-9', 'Who is upset?', 'Ai cảm thấy không hài lòng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-010', 'esl-fast-beginner-1-9', 'What does the teacher tell them to do?', 'Cô giáo bảo họ làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-011', 'esl-fast-beginner-1-9', 'Where does the teacher tell them to stand?', 'Cô giáo bảo họ đứng ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-012', 'esl-fast-beginner-1-9', 'Who goes to the corner?', 'Ai đi vào góc lớp?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-013', 'esl-fast-beginner-1-9', 'Where does Jill go?', 'Jill đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-014', 'esl-fast-beginner-1-9', 'Is it easy to be quiet?', 'Giữ im lặng có dễ không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-015', 'esl-fast-beginner-1-9', 'What is hard for Jill?', 'Điều gì khó đối với Jill?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-016', 'esl-fast-beginner-1-9', 'What does Jill think about?', 'Jill nghĩ về điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-017', 'esl-fast-beginner-1-9', 'Who does Jill think about?', 'Jill nghĩ về ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-018', 'esl-fast-beginner-1-9', 'What family does Jill think about?', 'Jill nghĩ về gia đình nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-019', 'esl-fast-beginner-1-9', 'What animal does Jill think about?', 'Jill nghĩ về con vật nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-020', 'esl-fast-beginner-1-9', 'What does Jill think about after her family?', 'Sau khi nghĩ về gia đình, Jill nghĩ về điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-021', 'esl-fast-beginner-1-9', 'How long passes?', 'Bao lâu trôi qua?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-022', 'esl-fast-beginner-1-9', 'How many minutes pass?', 'Bao nhiêu phút trôi qua?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-023', 'esl-fast-beginner-1-9', 'What happens after five minutes?', 'Điều gì xảy ra sau năm phút?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-024', 'esl-fast-beginner-1-9', 'Who lets Jill go?', 'Ai cho Jill quay lại chỗ?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-025', 'esl-fast-beginner-1-9', 'What does the teacher let Jill do?', 'Cô giáo cho Jill làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-026', 'esl-fast-beginner-1-9', 'Where is Jill told to stand?', 'Jill được bảo đứng ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-027', 'esl-fast-beginner-1-9', 'What are Jill and her friends supposed to be doing?', 'Jill và các bạn đáng lẽ đang làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-028', 'esl-fast-beginner-1-9', 'Why does the teacher become upset?', 'Vì sao cô giáo cảm thấy không hài lòng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-029', 'esl-fast-beginner-1-9', 'What does Jill talk about instead of doing math?', 'Thay vì làm toán, Jill nói chuyện về điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-9-030', 'esl-fast-beginner-1-9', 'What happens at the end?', 'Điều gì xảy ra ở cuối câu chuyện?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-10','A Surprise Party','Bữa tiệc bất ngờ','BEGINNER_01_ESL_FAST_CHILDREN_010.mp3',NULL,'00:00:00.000','00:00:31.000','esl-fast-children-1',1,1,1,10), */
	('Q-esl-fast-beginner-1-10-001', 'esl-fast-beginner-1-10', 'Whose birthday is it?', 'Hôm nay là sinh nhật của ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-002', 'esl-fast-beginner-1-10', 'Is it Lily''s birthday?', 'Hôm nay có phải là sinh nhật của Lily không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-003', 'esl-fast-beginner-1-10', 'What does Lily do first?', 'Lily làm gì đầu tiên?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-004', 'esl-fast-beginner-1-10', 'Where does Lily get out of?', 'Lily bước ra khỏi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-005', 'esl-fast-beginner-1-10', 'Does anybody say anything to Lily?', 'Có ai nói gì với Lily không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-006', 'esl-fast-beginner-1-10', 'Who takes Lily to school?', 'Ai đưa Lily đến trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-007', 'esl-fast-beginner-1-10', 'Where does Lily go with her mom?', 'Lily đi đâu cùng mẹ?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-008', 'esl-fast-beginner-1-10', 'Do Lily''s friends say anything to her?', 'Bạn bè của Lily có nói gì với cô bé không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-009', 'esl-fast-beginner-1-10', 'Who does not say anything to Lily at school?', 'Ai không nói gì với Lily ở trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-010', 'esl-fast-beginner-1-10', 'Does the teacher say anything?', 'Cô giáo có nói gì không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-011', 'esl-fast-beginner-1-10', 'How does Lily feel?', 'Lily cảm thấy thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-012', 'esl-fast-beginner-1-10', 'Is Lily happy?', 'Lily có vui không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-013', 'esl-fast-beginner-1-10', 'Where does Lily walk?', 'Lily đi bộ ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-014', 'esl-fast-beginner-1-10', 'Does Lily walk home alone?', 'Lily có đi bộ về nhà một mình không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-015', 'esl-fast-beginner-1-10', 'How does Lily go home?', 'Lily về nhà bằng cách nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-016', 'esl-fast-beginner-1-10', 'What does Lily open?', 'Lily mở cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-017', 'esl-fast-beginner-1-10', 'What does Lily see after opening the door?', 'Sau khi mở cửa, Lily nhìn thấy gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-018', 'esl-fast-beginner-1-10', 'Who is holding a cake?', 'Ai đang cầm một chiếc bánh?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-019', 'esl-fast-beginner-1-10', 'What are Lily''s friends and family holding?', 'Bạn bè và gia đình của Lily đang cầm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-020', 'esl-fast-beginner-1-10', 'What do they hold together?', 'Mọi người cùng cầm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-021', 'esl-fast-beginner-1-10', 'What do they say to Lily?', 'Mọi người nói gì với Lily?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-022', 'esl-fast-beginner-1-10', 'Do they say "Surprise Lily!"?', 'Mọi người có nói "Surprise Lily!" không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-023', 'esl-fast-beginner-1-10', 'Who says "Surprise Lily!"?', 'Ai nói "Surprise Lily!"?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-024', 'esl-fast-beginner-1-10', 'When does Lily see her friends and family?', 'Khi nào Lily nhìn thấy bạn bè và gia đình?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-025', 'esl-fast-beginner-1-10', 'What does Lily do before opening the door?', 'Lily làm gì trước khi mở cửa?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-026', 'esl-fast-beginner-1-10', 'What happens at school?', 'Điều gì xảy ra ở trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-027', 'esl-fast-beginner-1-10', 'Who takes Lily to school?', 'Ai đưa Lily đến trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-028', 'esl-fast-beginner-1-10', 'Who does not say anything to Lily at school?', 'Ai không nói gì với Lily ở trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-029', 'esl-fast-beginner-1-10', 'What does Lily find at home?', 'Lily nhìn thấy gì ở nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-10-030', 'esl-fast-beginner-1-10', 'What happens at the end of the story?', 'Điều gì xảy ra ở cuối câu chuyện?', 'ACTIVE', NULL, NULL, NULL, NULL);
	
INSERT INTO QUESTIONS (QUESTION_CODE, VOLUME_SLUG, QUESTION_TEXT, QUESTION_TEXT_VI, STATUS, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES
    /* (UUID(),'esl-fast-beginner-1-11','A New Pet','Thú cưng mới','BEGINNER_01_ESL_FAST_CHILDREN_011.mp3',NULL,'00:00:00.000','00:00:32.000','esl-fast-children-1',1,1,1,11), */
	('Q-esl-fast-beginner-1-11-001', 'esl-fast-beginner-1-11', 'What is Kate doing?', 'Kate đang làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-002', 'esl-fast-beginner-1-11', 'What does Kate see?', 'Kate nhìn thấy gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-003', 'esl-fast-beginner-1-11', 'Who sees a dog?', 'Ai nhìn thấy một chú chó?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-004', 'esl-fast-beginner-1-11', 'What does the dog do with its tail?', 'Chú chó làm gì với cái đuôi của nó?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-005', 'esl-fast-beginner-1-11', 'Does the dog wag its tail?', 'Chú chó có vẫy đuôi không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-006', 'esl-fast-beginner-1-11', 'Does Kate like the dog?', 'Kate có thích chú chó không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-007', 'esl-fast-beginner-1-11', 'What does the dog not have?', 'Chú chó không có gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-008', 'esl-fast-beginner-1-11', 'Does the dog have a collar?', 'Chú chó có đeo vòng cổ không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-009', 'esl-fast-beginner-1-11', 'Where does Kate take the dog?', 'Kate đưa chú chó đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-010', 'esl-fast-beginner-1-11', 'Who takes the dog home?', 'Ai đưa chú chó về nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-011', 'esl-fast-beginner-1-11', 'What does Kate do to the dog?', 'Kate làm gì cho chú chó?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-012', 'esl-fast-beginner-1-11', 'Does Kate wash the dog?', 'Kate có tắm cho chú chó không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-013', 'esl-fast-beginner-1-11', 'What does Kate name the dog?', 'Kate đặt tên cho chú chó là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-014', 'esl-fast-beginner-1-11', 'What is the dog''s name?', 'Tên của chú chó là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-015', 'esl-fast-beginner-1-11', 'Who is Toby?', 'Toby là ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-016', 'esl-fast-beginner-1-11', 'Where does Kate take Toby?', 'Kate đưa Toby đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-017', 'esl-fast-beginner-1-11', 'Who does Kate take to the vet?', 'Kate đưa ai đến bác sĩ thú y?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-018', 'esl-fast-beginner-1-11', 'Is Toby healthy?', 'Toby có khỏe mạnh không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-019', 'esl-fast-beginner-1-11', 'How is Toby?', 'Toby như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-020', 'esl-fast-beginner-1-11', 'Who walks Toby every day?', 'Ai dắt Toby đi dạo mỗi ngày?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-021', 'esl-fast-beginner-1-11', 'How often does Kate walk Toby?', 'Kate dắt Toby đi dạo bao lâu một lần?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-022', 'esl-fast-beginner-1-11', 'Does Kate walk Toby every day?', 'Kate có dắt Toby đi dạo mỗi ngày không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-023', 'esl-fast-beginner-1-11', 'Who loves Toby?', 'Ai yêu quý Toby?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-024', 'esl-fast-beginner-1-11', 'Who does Kate love?', 'Kate yêu quý ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-025', 'esl-fast-beginner-1-11', 'Do Kate and Toby love each other?', 'Kate và Toby có yêu quý nhau không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-026', 'esl-fast-beginner-1-11', 'What happens after Kate sees the dog?', 'Điều gì xảy ra sau khi Kate nhìn thấy chú chó?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-027', 'esl-fast-beginner-1-11', 'What does Kate do after taking the dog home?', 'Kate làm gì sau khi đưa chú chó về nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-028', 'esl-fast-beginner-1-11', 'What does Kate do after washing the dog?', 'Kate làm gì sau khi tắm cho chú chó?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-029', 'esl-fast-beginner-1-11', 'What does Kate do before walking Toby every day?', 'Kate làm gì trước khi dắt Toby đi dạo mỗi ngày?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-11-030', 'esl-fast-beginner-1-11', 'How does the story end?', 'Câu chuyện kết thúc như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-12','Group Project','Dự án nhóm','BEGINNER_01_ESL_FAST_CHILDREN_012.mp3',NULL,'00:00:00.000','00:00:34.000','esl-fast-children-1',1,1,1,12), */
	('Q-esl-fast-beginner-1-12-001', 'esl-fast-beginner-1-12', 'What does Ms. Howard assign?', 'Cô Howard giao bài gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-002', 'esl-fast-beginner-1-12', 'Who assigns the project?', 'Ai giao dự án?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-003', 'esl-fast-beginner-1-12', 'Who does Ms. Howard want to work in groups?', 'Cô Howard muốn ai làm việc theo nhóm?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-004', 'esl-fast-beginner-1-12', 'How does Ms. Howard want the students to work?', 'Cô Howard muốn các học sinh làm việc như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-005', 'esl-fast-beginner-1-12', 'Who works with Joe and Bill?', 'Ai làm việc cùng Joe và Bill?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-006', 'esl-fast-beginner-1-12', 'Who is in Adam''s group?', 'Ai ở trong nhóm của Adam?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-007', 'esl-fast-beginner-1-12', 'What is Adam like?', 'Adam là người như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-008', 'esl-fast-beginner-1-12', 'Who is smart?', 'Ai thông minh?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-009', 'esl-fast-beginner-1-12', 'What can Joe do well?', 'Joe có thể làm tốt việc gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-010', 'esl-fast-beginner-1-12', 'Who draws well?', 'Ai vẽ đẹp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-011', 'esl-fast-beginner-1-12', 'What is Bill like?', 'Bill là người như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-012', 'esl-fast-beginner-1-12', 'Who is cooperative?', 'Ai là người hợp tác?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-013', 'esl-fast-beginner-1-12', 'What kind of group do Adam, Joe, and Bill make?', 'Adam, Joe và Bill tạo thành nhóm như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-014', 'esl-fast-beginner-1-12', 'Do Adam, Joe, and Bill make a good group?', 'Adam, Joe và Bill có tạo thành một nhóm tốt không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-015', 'esl-fast-beginner-1-12', 'What do they turn in?', 'Họ nộp cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-016', 'esl-fast-beginner-1-12', 'Who turns in the project?', 'Ai nộp dự án?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-017', 'esl-fast-beginner-1-12', 'Does Ms. Howard like the project?', 'Cô Howard có thích bài dự án không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-018', 'esl-fast-beginner-1-12', 'Who likes the project?', 'Ai thích bài dự án?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-019', 'esl-fast-beginner-1-12', 'What does Ms. Howard give them?', 'Cô Howard cho họ cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-020', 'esl-fast-beginner-1-12', 'What kind of grade does Ms. Howard give them?', 'Cô Howard cho họ điểm như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-021', 'esl-fast-beginner-1-12', 'Are Adam, Joe, and Bill happy at the end?', 'Cuối cùng Adam, Joe và Bill có vui không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-022', 'esl-fast-beginner-1-12', 'Who is joyful at the end?', 'Cuối cùng ai rất vui?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-023', 'esl-fast-beginner-1-12', 'Why are Adam, Joe, and Bill joyful?', 'Tại sao Adam, Joe và Bill rất vui?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-024', 'esl-fast-beginner-1-12', 'How many students are in Adam''s group?', 'Có bao nhiêu học sinh trong nhóm của Adam?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-025', 'esl-fast-beginner-1-12', 'Which student is smart?', 'Học sinh nào thông minh?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-026', 'esl-fast-beginner-1-12', 'Which student draws well?', 'Học sinh nào vẽ đẹp?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-027', 'esl-fast-beginner-1-12', 'Which student is cooperative?', 'Học sinh nào hợp tác tốt?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-028', 'esl-fast-beginner-1-12', 'What do the three students work on together?', 'Ba học sinh cùng nhau làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-029', 'esl-fast-beginner-1-12', 'What happens after they turn in their project?', 'Điều gì xảy ra sau khi họ nộp dự án?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-12-030', 'esl-fast-beginner-1-12', 'What makes the three students joyful?', 'Điều gì khiến ba học sinh vui mừng?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-13','A Cat and A Mouse','Một con mèo và một con chuột','BEGINNER_01_ESL_FAST_CHILDREN_013.mp3',NULL,'00:00:00.000','00:00:40.000','esl-fast-children-1',1,1,1,13), */
	('Q-esl-fast-beginner-1-13-001','esl-fast-beginner-1-13','How does the cat feel at the beginning?','Con mèo cảm thấy thế nào lúc đầu?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-002','esl-fast-beginner-1-13','What does the cat try to do?','Con mèo cố làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-003','esl-fast-beginner-1-13','What does the cat play with?','Con mèo chơi với cái gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-004','esl-fast-beginner-1-13','What does the cat scratch?','Con mèo gãi cái gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-005','esl-fast-beginner-1-13','What does the cat do after scratching his tummy?','Con mèo làm gì sau khi gãi bụng?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-006','esl-fast-beginner-1-13','What does the cat drink?','Con mèo uống gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-007','esl-fast-beginner-1-13','Is the cat still bored after drinking milk?','Con mèo có vẫn chán sau khi uống sữa không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-008','esl-fast-beginner-1-13','What does the cat see?','Con mèo nhìn thấy gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-009','esl-fast-beginner-1-13','What is the mouse eating?','Con chuột đang ăn gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-010','esl-fast-beginner-1-13','What does the cat steal?','Con mèo cướp cái gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-011','esl-fast-beginner-1-13','How does the mouse feel after the cat steals the cheese?','Con chuột cảm thấy thế nào sau khi con mèo cướp phô mai?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-012','esl-fast-beginner-1-13','Who chases the cat?','Ai đuổi theo con mèo?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-013','esl-fast-beginner-1-13','Who is eating cheese?','Ai đang ăn phô mai?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-014','esl-fast-beginner-1-13','Who steals the cheese?','Ai cướp phô mai?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-015','esl-fast-beginner-1-13','Who is angry?','Ai đang tức giận?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-016','esl-fast-beginner-1-13','What does the cat do with the yarn?','Con mèo làm gì với cuộn len?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-017','esl-fast-beginner-1-13','What does the cat do with his tummy?','Con mèo làm gì với bụng của mình?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-018','esl-fast-beginner-1-13','Does the cat take a nap?','Con mèo có chợp mắt không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-019','esl-fast-beginner-1-13','Does the cat drink milk?','Con mèo có uống sữa không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-020','esl-fast-beginner-1-13','What happens after the cat sees the mouse?','Điều gì xảy ra sau khi con mèo nhìn thấy con chuột?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-021','esl-fast-beginner-1-13','What happens after the mouse gets angry?','Điều gì xảy ra sau khi con chuột tức giận?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-022','esl-fast-beginner-1-13','What makes the mouse angry?','Điều gì khiến con chuột tức giận?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-023','esl-fast-beginner-1-13','Why does the cat have fun at the end?','Tại sao con mèo vui thích ở cuối câu chuyện?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-024','esl-fast-beginner-1-13','How many times does the cat try to have fun before seeing the mouse?','Con mèo cố tìm cách giải trí bao nhiêu hoạt động trước khi nhìn thấy chuột?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-025','esl-fast-beginner-1-13','Which animal is bored at the beginning?','Con vật nào buồn chán lúc đầu?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-026','esl-fast-beginner-1-13','Which animal is angry?','Con vật nào tức giận?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-027','esl-fast-beginner-1-13','Which animal chases another animal?','Con vật nào đuổi theo con vật khác?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-028','esl-fast-beginner-1-13','What does the mouse eat before the cat steals it?','Con chuột ăn gì trước khi con mèo cướp nó?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-029','esl-fast-beginner-1-13','What is the cat like at the end?','Con mèo cảm thấy thế nào ở cuối câu chuyện?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-13-030','esl-fast-beginner-1-13','What does the cat do before seeing the mouse?','Con mèo làm gì trước khi nhìn thấy con chuột?','ACTIVE',NULL,NULL,NULL,NULL),
	
	/* (UUID(),'esl-fast-beginner-1-14','Lemonade Stand','Quầy nước chanh','BEGINNER_01_ESL_FAST_CHILDREN_014.mp3',NULL,'00:00:00.000','00:00:37.000','esl-fast-children-1',1,1,1,14), */
	('Q-esl-fast-beginner-1-14-001','esl-fast-beginner-1-14','Where does John want to go?','John muốn đi đâu?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-002','esl-fast-beginner-1-14','What does John want to attend?','John muốn tham gia sự kiện gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-003','esl-fast-beginner-1-14','How much money does John need?','John cần bao nhiêu tiền?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-004','esl-fast-beginner-1-14','How does John want to earn the money?','John muốn kiếm tiền bằng cách nào?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-005','esl-fast-beginner-1-14','What does John plan to open?','John dự định mở quầy gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-006','esl-fast-beginner-1-14','Where does John go to buy lemons?','John đi đâu để mua chanh?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-007','esl-fast-beginner-1-14','How are the lemons at the market?','Chanh ở chợ như thế nào?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-008','esl-fast-beginner-1-14','Are the lemons ripe?','Chanh đã chín chưa?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-009','esl-fast-beginner-1-14','How many lemons does John buy?','John mua bao nhiêu quả chanh?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-010','esl-fast-beginner-1-14','What does John start making?','John bắt đầu làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-011','esl-fast-beginner-1-14','What are a lot of people doing?','Rất nhiều người đang làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-012','esl-fast-beginner-1-14','Is John''s lemonade stand successful?','Quầy nước chanh của John có thành công không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-013','esl-fast-beginner-1-14','Does John make enough money?','John có kiếm đủ tiền không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-014','esl-fast-beginner-1-14','Why does John need fifty dollars?','Tại sao John cần 50 đô la?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-015','esl-fast-beginner-1-14','What does John want to pay for himself?','John muốn tự kiếm tiền để chi trả cho việc gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-016','esl-fast-beginner-1-14','What does John sell at his stand?','John bán gì ở quầy của mình?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-017','esl-fast-beginner-1-14','Who wants to go on the field trip?','Ai muốn tham gia chuyến dã ngoại?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-018','esl-fast-beginner-1-14','Who wants to earn the money himself?','Ai muốn tự mình kiếm tiền?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-019','esl-fast-beginner-1-14','What does John buy at the market?','John mua gì ở chợ?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-020','esl-fast-beginner-1-14','What does John do after buying the lemons?','John làm gì sau khi mua chanh?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-021','esl-fast-beginner-1-14','How many dollars does John need for the trip?','John cần bao nhiêu đô la cho chuyến đi?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-022','esl-fast-beginner-1-14','What kind of lemons does John buy?','John mua loại chanh như thế nào?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-023','esl-fast-beginner-1-14','Are the lemons expensive?','Chanh có đắt không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-024','esl-fast-beginner-1-14','What is successful?','Điều gì thành công?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-025','esl-fast-beginner-1-14','What does John use to make lemonade?','John dùng gì để làm nước chanh?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-026','esl-fast-beginner-1-14','Where are people standing in line?','Mọi người đang xếp hàng ở đâu?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-027','esl-fast-beginner-1-14','What does John want to do by himself?','John muốn tự mình làm điều gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-028','esl-fast-beginner-1-14','What happens to John''s lemonade stand?','Điều gì xảy ra với quầy nước chanh của John?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-029','esl-fast-beginner-1-14','Does John earn enough money for his goal?','John có kiếm đủ tiền cho mục tiêu của mình không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-14-030','esl-fast-beginner-1-14','What is the result of John''s hard work?','Kết quả của sự cố gắng của John là gì?','ACTIVE',NULL,NULL,NULL,NULL),
	
	/* (UUID(),'esl-fast-beginner-1-15','New and Old','Mới và cũ','BEGINNER_01_ESL_FAST_CHILDREN_015.mp3',NULL,'00:00:00.000','00:00:33.000','esl-fast-children-1',1,1,1,15), */
	('Q-esl-fast-beginner-1-15-001','esl-fast-beginner-1-15','What is tomorrow?','Ngày mai là ngày gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-002','esl-fast-beginner-1-15','Who is the story about?','Câu chuyện kể về ai?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-003','esl-fast-beginner-1-15','What does Barbara look at?','Barbara nhìn vào cái gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-004','esl-fast-beginner-1-15','What does Barbara need?','Barbara cần thứ gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-005','esl-fast-beginner-1-15','What is wrong with her backpack?','Ba lô của cô bé bị làm sao?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-006','esl-fast-beginner-1-15','Is her backpack clean?','Ba lô của cô bé có sạch không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-007','esl-fast-beginner-1-15','When does Barbara need a new backpack?','Khi nào Barbara cần một chiếc ba lô mới?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-008','esl-fast-beginner-1-15','Who takes Barbara shopping?','Ai đưa Barbara đi mua sắm?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-009','esl-fast-beginner-1-15','Where does her mom take her?','Mẹ đưa cô bé đi đâu?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-010','esl-fast-beginner-1-15','What are there many of in the store?','Có rất nhiều thứ gì trong cửa hàng?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-011','esl-fast-beginner-1-15','What color are the stars on one backpack?','Những ngôi sao trên một chiếc ba lô có màu gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-012','esl-fast-beginner-1-15','What shape is on the first backpack?','Hình gì có trên chiếc ba lô đầu tiên?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-013','esl-fast-beginner-1-15','What does another backpack have?','Một chiếc ba lô khác có gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-014','esl-fast-beginner-1-15','What colors are the stripes?','Các sọc có những màu gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-015','esl-fast-beginner-1-15','What animals are on another backpack?','Những con vật nào có trên một chiếc ba lô khác?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-016','esl-fast-beginner-1-15','Which backpack does Barbara like?','Barbara thích chiếc ba lô nào?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-017','esl-fast-beginner-1-15','Does Barbara like the backpack with dogs?','Barbara có thích chiếc ba lô có hình chó không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-018','esl-fast-beginner-1-15','What does Barbara do after choosing a backpack?','Barbara làm gì sau khi chọn một chiếc ba lô?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-019','esl-fast-beginner-1-15','Does Barbara buy the backpack she likes?','Barbara có mua chiếc ba lô mình thích không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-020','esl-fast-beginner-1-15','Who goes shopping with Barbara?','Ai đi mua sắm cùng Barbara?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-021','esl-fast-beginner-1-15','What will Barbara do tomorrow?','Ngày mai Barbara sẽ làm gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-022','esl-fast-beginner-1-15','Why does Barbara need a new backpack?','Tại sao Barbara cần một chiếc ba lô mới?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-023','esl-fast-beginner-1-15','How many backpacks are described with designs?','Có bao nhiêu chiếc ba lô được mô tả có hình trang trí?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-024','esl-fast-beginner-1-15','Which backpack has rainbow stripes?','Chiếc ba lô nào có các sọc cầu vồng?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-025','esl-fast-beginner-1-15','Which backpack has yellow stars?','Chiếc ba lô nào có những ngôi sao màu vàng?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-026','esl-fast-beginner-1-15','Which backpack has dogs?','Chiếc ba lô nào có hình những chú chó?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-027','esl-fast-beginner-1-15','What does Barbara do with her old backpack?','Barbara làm gì với chiếc ba lô cũ?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-028','esl-fast-beginner-1-15','Does Barbara choose a backpack with stars?','Barbara có chọn chiếc ba lô có ngôi sao không?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-029','esl-fast-beginner-1-15','What does Barbara buy?','Barbara mua gì?','ACTIVE',NULL,NULL,NULL,NULL),
	('Q-esl-fast-beginner-1-15-030','esl-fast-beginner-1-15','Who buys the new backpack?','Ai mua chiếc ba lô mới?','ACTIVE',NULL,NULL,NULL,NULL);
	
	/* (UUID(),'esl-fast-beginner-1-16','The Kind Dentist','Nha sĩ tốt bụng','BEGINNER_01_ESL_FAST_CHILDREN_016.mp3',NULL,'00:00:00.000','00:00:40.000','esl-fast-children-1',1,1,1,16), */
	
	
	/* (UUID(),'esl-fast-beginner-1-17','A Trip to the Library','Chuyến đi đến thư viện','BEGINNER_01_ESL_FAST_CHILDREN_017.mp3',NULL,'00:00:00.000','00:00:30.000','esl-fast-children-1',1,1,1,17), */
	
	
	/* (UUID(),'esl-fast-beginner-1-18','A Lot of Ants','Rất nhiều con kiến','BEGINNER_01_ESL_FAST_CHILDREN_018.mp3',NULL,'00:00:00.000','00:00:28.000','esl-fast-children-1',1,1,1,18), */
	
	
	/* (UUID(),'esl-fast-beginner-1-19','Picking a Costume','Chọn trang phục','BEGINNER_01_ESL_FAST_CHILDREN_019.mp3',NULL,'00:00:00.000','00:00:32.500','esl-fast-children-1',1,1,1,19), */
	
	
	/* (UUID(),'esl-fast-beginner-1-20','Petting Zoo','Vườn thú cưng','BEGINNER_01_ESL_FAST_CHILDREN_020.mp3',NULL,'00:00:00.000','00:00:40.000','esl-fast-children-1',1,1,1,20), */
	
	
	/* (UUID(),'esl-fast-beginner-1-21','Mom is Mad','Mẹ đang tức giận','BEGINNER_01_ESL_FAST_CHILDREN_021.mp3',NULL,'00:00:00.000','00:00:35.500','esl-fast-children-1',1,1,1,21, */
    ('Q-esl-fast-beginner-1-21-001', 'esl-fast-beginner-1-21', 'Whose room is messy?', 'Phòng của ai rất bừa bộn?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-002', 'esl-fast-beginner-1-21', 'What is under Robert''s bed?', 'Có gì ở dưới gầm giường của Robert?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-003', 'esl-fast-beginner-1-21', 'Where is the pizza?', 'Bánh pizza ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-004', 'esl-fast-beginner-1-21', 'What is on the wall?', 'Có gì trên tường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-005', 'esl-fast-beginner-1-21', 'Where is the glue?', 'Keo ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-006', 'esl-fast-beginner-1-21', 'What is there a pile of?', 'Có một đống gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-007', 'esl-fast-beginner-1-21', 'Where are the toys?', 'Đồ chơi ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-008', 'esl-fast-beginner-1-21', 'Does Robert care about the messy room?', 'Robert có bận tâm về căn phòng bừa bộn không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-009', 'esl-fast-beginner-1-21', 'What does Robert watch?', 'Robert xem gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-010', 'esl-fast-beginner-1-21', 'Who goes into Robert''s room?', 'Ai bước vào phòng của Robert?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-011', 'esl-fast-beginner-1-21', 'What does Robert''s mom turn off?', 'Mẹ của Robert tắt gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-012', 'esl-fast-beginner-1-21', 'Who turns off the television?', 'Ai tắt tivi?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-013', 'esl-fast-beginner-1-21', 'What does Robert''s mom do to him?', 'Mẹ của Robert làm gì với cậu bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-014', 'esl-fast-beginner-1-21', 'What does Robert start to do?', 'Robert bắt đầu làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-015', 'esl-fast-beginner-1-21', 'What is messy?', 'Cái gì rất bừa bộn?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-016', 'esl-fast-beginner-1-21', 'What is under the bed?', 'Có gì dưới gầm giường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-017', 'esl-fast-beginner-1-21', 'What is stuck on the wall?', 'Có gì dính trên tường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-018', 'esl-fast-beginner-1-21', 'What kind of clothes are mentioned?', 'Có loại quần áo nào được nhắc đến?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-019', 'esl-fast-beginner-1-21', 'Where are the clothes?', 'Quần áo ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-020', 'esl-fast-beginner-1-21', 'Where are the toys located?', 'Đồ chơi được đặt ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-021', 'esl-fast-beginner-1-21', 'What does Robert watch on television?', 'Robert xem gì trên tivi?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-022', 'esl-fast-beginner-1-21', 'When does Robert''s mom enter the room?', 'Khi nào mẹ của Robert bước vào phòng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-023', 'esl-fast-beginner-1-21', 'What does Robert''s mom do after entering the room?', 'Mẹ của Robert làm gì sau khi bước vào phòng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-024', 'esl-fast-beginner-1-21', 'How does Robert''s mom react to the messy room?', 'Mẹ của Robert phản ứng thế nào với căn phòng bừa bộn?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-025', 'esl-fast-beginner-1-21', 'What does Robert do after his mom yells at him?', 'Robert làm gì sau khi mẹ la mắng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-026', 'esl-fast-beginner-1-21', 'What is Robert''s attitude toward his messy room?', 'Thái độ của Robert đối với căn phòng bừa bộn là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-027', 'esl-fast-beginner-1-21', 'What does Robert eventually do?', 'Cuối cùng Robert làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-028', 'esl-fast-beginner-1-21', 'What is on the floor in Robert''s room?', 'Có gì trên sàn phòng của Robert?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-029', 'esl-fast-beginner-1-21', 'Who yells at Robert?', 'Ai la mắng Robert?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-21-030', 'esl-fast-beginner-1-21', 'What does Robert clean?', 'Robert dọn dẹp cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-22','Father\'s Day','Ngày của cha','BEGINNER_01_ESL_FAST_CHILDREN_022.mp3',NULL,'00:00:00.000','00:00:39.000','esl-fast-children-1',1,1,1,22), */
	('Q-esl-fast-beginner-1-22-001', 'esl-fast-beginner-1-22', 'What day is it?', 'Hôm nay là ngày gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-002', 'esl-fast-beginner-1-22', 'Whose day is it?', 'Đây là ngày của ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-003', 'esl-fast-beginner-1-22', 'Who surprises his father?', 'Ai tạo bất ngờ cho bố của mình?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-004', 'esl-fast-beginner-1-22', 'Who is Daniel surprising?', 'Daniel tạo bất ngờ cho ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-005', 'esl-fast-beginner-1-22', 'What does Daniel serve his father?', 'Daniel mang gì cho bố?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-006', 'esl-fast-beginner-1-22', 'What does Daniel serve first?', 'Daniel mang gì ra đầu tiên?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-007', 'esl-fast-beginner-1-22', 'What is on the tray?', 'Có gì trên khay?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-008', 'esl-fast-beginner-1-22', 'Are there eggs on the tray?', 'Có trứng trên khay không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-009', 'esl-fast-beginner-1-22', 'What kind of juice is on the tray?', 'Trên khay có loại nước ép nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-010', 'esl-fast-beginner-1-22', 'How does Daniel''s father feel?', 'Bố của Daniel cảm thấy thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-011', 'esl-fast-beginner-1-22', 'Is Daniel''s father happy?', 'Bố của Daniel có vui không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-012', 'esl-fast-beginner-1-22', 'What do Daniel and his father do later?', 'Sau đó Daniel và bố làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-013', 'esl-fast-beginner-1-22', 'What sport do they play?', 'Họ chơi môn thể thao nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-014', 'esl-fast-beginner-1-22', 'Who plays tennis with Daniel?', 'Ai chơi quần vợt với Daniel?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-015', 'esl-fast-beginner-1-22', 'Where does Daniel stand?', 'Daniel đứng ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-016', 'esl-fast-beginner-1-22', 'What does Daniel swing?', 'Daniel đánh cái gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-017', 'esl-fast-beginner-1-22', 'What does Daniel''s father do?', 'Bố của Daniel làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-018', 'esl-fast-beginner-1-22', 'Does Daniel''s father hit the ball back?', 'Bố của Daniel có đánh bóng trả lại không?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-019', 'esl-fast-beginner-1-22', 'What do they watch finally?', 'Cuối cùng họ xem gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-020', 'esl-fast-beginner-1-22', 'When do they watch the sunset?', 'Khi nào họ ngắm hoàng hôn?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-021', 'esl-fast-beginner-1-22', 'Who watches the sunset?', 'Ai ngắm hoàng hôn?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-022', 'esl-fast-beginner-1-22', 'What is Daniel''s father happy about?', 'Bố của Daniel vui vì điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-023', 'esl-fast-beginner-1-22', 'What food does Daniel prepare?', 'Daniel chuẩn bị món ăn gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-024', 'esl-fast-beginner-1-22', 'What drink does Daniel prepare?', 'Daniel chuẩn bị đồ uống gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-025', 'esl-fast-beginner-1-22', 'What does Daniel do for Father''s Day?', 'Daniel làm gì vào Ngày của Cha?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-026', 'esl-fast-beginner-1-22', 'What happens after breakfast?', 'Điều gì xảy ra sau bữa sáng?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-027', 'esl-fast-beginner-1-22', 'What happens after Daniel hits the ball?', 'Điều gì xảy ra sau khi Daniel đánh bóng?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-028', 'esl-fast-beginner-1-22', 'How does the day end?', 'Ngày hôm đó kết thúc như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-029', 'esl-fast-beginner-1-22', 'What does Daniel think about the day?', 'Daniel nghĩ gì về ngày hôm đó?', 'ACTIVE', NULL, NULL, NULL, NULL),
	('Q-esl-fast-beginner-1-22-030', 'esl-fast-beginner-1-22', 'What is the main idea of the story?', 'Ý chính của bài đọc là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
		
	/* (UUID(),'esl-fast-beginner-1-23','The Baby Sister','Em bé gái','BEGINNER_01_ESL_FAST_CHILDREN_023.mp3',NULL,'00:00:00.000','00:00:37.000','esl-fast-children-1',1,1,1,23), */
	('Q-esl-fast-beginner-1-23-001', 'esl-fast-beginner-1-23', 'Who loves her baby sister?', 'Ai rất yêu quý em gái bé bỏng của mình?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-002', 'esl-fast-beginner-1-23', 'Who is Betty''s baby sister?', 'Em gái bé bỏng của Betty là ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-003', 'esl-fast-beginner-1-23', 'What does Betty do for her baby sister?', 'Betty làm gì cho em gái bé bỏng của mình?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-004', 'esl-fast-beginner-1-23', 'Does Betty take care of her baby sister?', 'Betty có chăm sóc em gái bé bỏng của mình không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-005', 'esl-fast-beginner-1-23', 'What does Betty change for the baby?', 'Betty thay gì cho em bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-006', 'esl-fast-beginner-1-23', 'What does Betty do after changing the baby''s diaper?', 'Betty làm gì sau khi thay tã cho em bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-007', 'esl-fast-beginner-1-23', 'What does Betty feed her baby sister?', 'Betty cho em gái bé bỏng ăn gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-008', 'esl-fast-beginner-1-23', 'What does Betty teach her baby sister to do?', 'Betty dạy em gái bé bỏng làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-009', 'esl-fast-beginner-1-23', 'What does Betty teach her baby sister to walk?', 'Betty dạy em gái bé bỏng điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-010', 'esl-fast-beginner-1-23', 'What does Betty teach her baby sister besides walking?', 'Ngoài tập đi, Betty còn dạy em gái bé bỏng điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-011', 'esl-fast-beginner-1-23', 'Is it easy to take care of babies?', 'Chăm sóc em bé có dễ không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-012', 'esl-fast-beginner-1-23', 'Who cries sometimes?', 'Ai đôi khi khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-013', 'esl-fast-beginner-1-23', 'When does Betty''s baby sister cry?', 'Em gái bé bỏng của Betty khóc khi nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-014', 'esl-fast-beginner-1-23', 'What game does Betty play with her baby sister?', 'Betty chơi trò gì với em gái bé bỏng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-015', 'esl-fast-beginner-1-23', 'What is peek-a-boo?', 'Peek-a-boo là trò gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-016', 'esl-fast-beginner-1-23', 'What does Betty cover when she plays peek-a-boo?', 'Betty che gì khi chơi ú òa?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-017', 'esl-fast-beginner-1-23', 'What does Betty do after covering her eyes?', 'Betty làm gì sau khi che mắt?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-018', 'esl-fast-beginner-1-23', 'What does the baby do when Betty plays peek-a-boo?', 'Em bé làm gì khi Betty chơi ú òa?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-019', 'esl-fast-beginner-1-23', 'Does the baby laugh?', 'Em bé có cười không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-020', 'esl-fast-beginner-1-23', 'How does the baby react to peek-a-boo?', 'Em bé phản ứng thế nào với trò ú òa?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-021', 'esl-fast-beginner-1-23', 'What kind of sister is Betty?', 'Betty là một người chị như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-022', 'esl-fast-beginner-1-23', 'What does Betty do to help her baby sister?', 'Betty làm gì để giúp đỡ em gái bé bỏng?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-023', 'esl-fast-beginner-1-23', 'How many things does Betty teach her baby sister?', 'Betty dạy em gái bé bỏng bao nhiêu điều?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-024', 'esl-fast-beginner-1-23', 'What does Betty do with the baby''s diaper?', 'Betty làm gì với tã của em bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-025', 'esl-fast-beginner-1-23', 'What does Betty do when her baby sister needs food?', 'Betty làm gì khi em gái bé bỏng cần ăn?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-026', 'esl-fast-beginner-1-23', 'What new skill does Betty teach the baby?', 'Betty dạy em bé kỹ năng mới nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-027', 'esl-fast-beginner-1-23', 'What does Betty teach the baby about language?', 'Betty dạy em bé điều gì về ngôn ngữ?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-028', 'esl-fast-beginner-1-23', 'What does Betty do when the baby cries?', 'Betty làm gì khi em bé khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-029', 'esl-fast-beginner-1-23', 'Why does the baby laugh?', 'Tại sao em bé cười?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-030', 'esl-fast-beginner-1-23', 'What is the main idea of the story?', 'Ý chính của bài đọc là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-24','Sometimes You Lose','Đôi khi bạn thua','BEGINNER_01_ESL_FAST_CHILDREN_024.mp3',NULL,'00:00:00.000','00:00:39.000','esl-fast-children-1','YES',24) */
    ('Q-esl-fast-beginner-1-24-001', 'esl-fast-beginner-1-24', 'What happened to Sarah''s basketball team?', 'Điều gì đã xảy ra với đội bóng rổ của Sarah?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-002', 'esl-fast-beginner-1-24', 'How does Sarah feel after the game?', 'Sarah cảm thấy thế nào sau trận đấu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-003', 'esl-fast-beginner-1-24', 'How does Sarah walk home?', 'Sarah đi bộ về nhà như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-004', 'esl-fast-beginner-1-24', 'Where does Sarah sit when she gets home?', 'Sarah ngồi ở đâu khi về đến nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-005', 'esl-fast-beginner-1-24', 'What does Sarah start doing on the couch?', 'Sarah bắt đầu làm gì khi ngồi trên ghế sofa?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-006', 'esl-fast-beginner-1-24', 'Who sees Sarah crying?', 'Ai nhìn thấy Sarah đang khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-007', 'esl-fast-beginner-1-24', 'What does Sarah''s mom do when she sees her?', 'Mẹ của Sarah làm gì khi nhìn thấy cô bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-008', 'esl-fast-beginner-1-24', 'What does Sarah''s mom bake?', 'Mẹ của Sarah làm bánh gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-009', 'esl-fast-beginner-1-24', 'Whose favorite cookies does her mom bake?', 'Mẹ của Sarah làm loại bánh quy yêu thích của ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-010', 'esl-fast-beginner-1-24', 'What makes Sarah smile?', 'Điều gì khiến Sarah mỉm cười?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-011', 'esl-fast-beginner-1-24', 'What does Sarah wipe away?', 'Sarah lau đi điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-012', 'esl-fast-beginner-1-24', 'What does Sarah realize about winning and losing?', 'Sarah nhận ra điều gì về việc thắng và thua?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-013', 'esl-fast-beginner-1-24', 'What does the word "upset" mean in the lesson?', 'Từ "upset" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-014', 'esl-fast-beginner-1-24', 'What does "sadly" mean in the lesson?', 'Từ "sadly" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-015', 'esl-fast-beginner-1-24', 'What does "hug" mean in the lesson?', 'Từ "hug" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-016', 'esl-fast-beginner-1-24', 'What does "tears" mean in the lesson?', 'Từ "tears" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-017', 'esl-fast-beginner-1-24', 'Why does Sarah cry?', 'Tại sao Sarah khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-018', 'esl-fast-beginner-1-24', 'How does Sarah feel after eating the warm cookies?', 'Sarah cảm thấy thế nào sau khi ăn những chiếc bánh quy ấm áp?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-019', 'esl-fast-beginner-1-24', 'What does Sarah do after her mom bakes the cookies?', 'Sarah làm gì sau khi mẹ làm bánh quy?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-020', 'esl-fast-beginner-1-24', 'What is the main lesson Sarah learns?', 'Bài học chính mà Sarah rút ra là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-25','A New Home','Ngôi nhà mới','BEGINNER_01_ESL_FAST_CHILDREN_025.mp3',NULL,'00:00:00.000','00:00:30.000','esl-fast-children-1','YES',25) */
    ('Q-esl-fast-beginner-1-25-001', 'esl-fast-beginner-1-25', 'Where does he move?', 'Cậu bé chuyển đến đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-002', 'esl-fast-beginner-1-25', 'What kind of place does he move to?', 'Cậu bé chuyển đến một nơi như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-003', 'esl-fast-beginner-1-25', 'What are there many of in the new city?', 'Có rất nhiều gì ở thành phố mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-004', 'esl-fast-beginner-1-25', 'What are many people doing?', 'Có nhiều người đang làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-005', 'esl-fast-beginner-1-25', 'What kind of cars are mentioned?', 'Loại xe nào được nhắc đến?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-006', 'esl-fast-beginner-1-25', 'How does he feel in the new city?', 'Cậu bé cảm thấy thế nào ở thành phố mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-007', 'esl-fast-beginner-1-25', 'Why might he feel lonely?', 'Tại sao cậu bé có thể cảm thấy cô đơn?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-008', 'esl-fast-beginner-1-25', 'How do people act in the new city?', 'Mọi người cư xử như thế nào ở thành phố mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-009', 'esl-fast-beginner-1-25', 'Where does he go after moving?', 'Sau khi chuyển nhà, cậu bé đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-010', 'esl-fast-beginner-1-25', 'What does he see at his new school?', 'Cậu bé nhìn thấy gì ở trường mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-011', 'esl-fast-beginner-1-25', 'What does the person look like?', 'Người đó trông như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-012', 'esl-fast-beginner-1-25', 'Who does he meet at school?', 'Cậu bé gặp ai ở trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-013', 'esl-fast-beginner-1-25', 'What does he ask the person to do?', 'Cậu bé nhờ người đó làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-014', 'esl-fast-beginner-1-25', 'Does he know the new city well?', 'Cậu bé có biết rõ thành phố mới không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-015', 'esl-fast-beginner-1-25', 'Is the new city crowded?', 'Thành phố mới có đông đúc không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-016', 'esl-fast-beginner-1-25', 'What is different about the new place?', 'Điều gì khác biệt ở nơi mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-017', 'esl-fast-beginner-1-25', 'What does he notice first about the city?', 'Cậu bé chú ý điều gì đầu tiên về thành phố?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-018', 'esl-fast-beginner-1-25', 'What does he notice about the people?', 'Cậu bé nhận thấy điều gì về mọi người?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-019', 'esl-fast-beginner-1-25', 'Where are many people walking?', 'Có nhiều người đang đi bộ ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-020', 'esl-fast-beginner-1-25', 'What makes the city look busy?', 'Điều gì khiến thành phố trông nhộn nhịp?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-021', 'esl-fast-beginner-1-25', 'What does he do when he gets to school?', 'Cậu bé làm gì khi đến trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-022', 'esl-fast-beginner-1-25', 'Does he find someone friendly?', 'Cậu bé có gặp một người thân thiện không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-023', 'esl-fast-beginner-1-25', 'How does the person seem?', 'Người đó có vẻ như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-024', 'esl-fast-beginner-1-25', 'What does he need help with?', 'Cậu bé cần giúp đỡ về việc gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-025', 'esl-fast-beginner-1-25', 'What does “show him around” mean?', '“Show him around” có nghĩa là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-026', 'esl-fast-beginner-1-25', 'Why does he talk to the friendly-looking person?', 'Tại sao cậu bé nói chuyện với người trông thân thiện?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-027', 'esl-fast-beginner-1-25', 'What is the boy experiencing?', 'Cậu bé đang trải qua điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-028', 'esl-fast-beginner-1-25', 'What happens before he goes to school?', 'Điều gì xảy ra trước khi cậu bé đến trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-029', 'esl-fast-beginner-1-25', 'What happens at the end of the story?', 'Điều gì xảy ra ở cuối câu chuyện?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-030', 'esl-fast-beginner-1-25', 'What is the main idea of the story?', 'Ý chính của câu chuyện là gì?', 'ACTIVE', NULL, NULL, NULL, NULL);