/* (UUID(),'esl-fast-beginner-1-24','Sometimes You Lose','Đôi khi bạn thua','BEGINNER_01_ESL_FAST_CHILDREN_024.mp3',NULL,'00:00:00.000','00:00:39.000','esl-fast-children-1','YES',24) */
INSERT INTO QUESTIONS (QUESTION_CODE, VOLUME_SLUG, QUESTION_TEXT, QUESTION_TEXT_VI, STATUS, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES
    ('Q-esl-fast-beginner-1-24-001', 'esl-fast-beginner-1-24', 'What happened to Sarah''s basketball team?', 'Điều gì đã xảy ra với đội bóng rổ của Sarah?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-002', 'esl-fast-beginner-1-24', 'How does Sarah feel after the game?', 'Sarah cảm thấy thế nào sau trận đấu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-003', 'esl-fast-beginner-1-24', 'How does Sarah walk home?', 'Sarah đi bộ về nhà như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-004', 'esl-fast-beginner-1-24', 'Where does Sarah sit when she gets home?', 'Sarah ngồi ở đâu khi về đến nhà?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-005', 'esl-fast-beginner-1-24', 'What does Sarah start doing on the couch?', 'Sarah bắt đầu làm gì khi ngồi trên ghế sofa?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-006', 'esl-fast-beginner-1-24', 'Who sees Sarah crying?', 'Ai nhìn thấy Sarah đang khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-007', 'esl-fast-beginner-1-24', 'What does Sarah''s mom do when she sees her?', 'Mẹ của Sarah làm gì khi nhìn thấy cô bé?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-008', 'esl-fast-beginner-1-24', 'What does Sarah''s mom bake?', 'Mẹ của Sarah làm bánh gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-009', 'esl-fast-beginner-1-24', 'Whose favorite cookies does her mom bake?', 'Mẹ của Sarah làm loại bánh quy yêu thích của ai?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-010', 'esl-fast-beginner-1-24', 'What makes Sarah smile?', 'Điều gì khiến Sarah mỉm cười?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-011', 'esl-fast-beginner-1-24', 'What does Sarah wipe away?', 'Sarah lau đi điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-012', 'esl-fast-beginner-1-24', 'What does Sarah realize about winning and losing?', 'Sarah nhận ra điều gì về việc thắng và thua?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-013', 'esl-fast-beginner-1-24', 'What does the word "upset" mean in the lesson?', 'Từ "upset" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-014', 'esl-fast-beginner-1-24', 'What does "sadly" mean in the lesson?', 'Từ "sadly" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-015', 'esl-fast-beginner-1-24', 'What does "hug" mean in the lesson?', 'Từ "hug" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-016', 'esl-fast-beginner-1-24', 'What does "tears" mean in the lesson?', 'Từ "tears" có nghĩa là gì trong bài học?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-017', 'esl-fast-beginner-1-24', 'Why does Sarah cry?', 'Tại sao Sarah khóc?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-018', 'esl-fast-beginner-1-24', 'How does Sarah feel after eating the warm cookies?', 'Sarah cảm thấy thế nào sau khi ăn những chiếc bánh quy ấm áp?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-019', 'esl-fast-beginner-1-24', 'What does Sarah do after her mom bakes the cookies?', 'Sarah làm gì sau khi mẹ làm bánh quy?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-24-020', 'esl-fast-beginner-1-24', 'What is the main lesson Sarah learns?', 'Bài học chính mà Sarah rút ra là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
	
	/* (UUID(),'esl-fast-beginner-1-25','A New Home','Ngôi nhà mới','BEGINNER_01_ESL_FAST_CHILDREN_025.mp3',NULL,'00:00:00.000','00:00:30.000','esl-fast-children-1','YES',25) */
    ('Q-esl-fast-beginner-1-25-001', 'esl-fast-beginner-1-25', 'Where does he move?', 'Cậu bé chuyển đến đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-002', 'esl-fast-beginner-1-25', 'What kind of place does he move to?', 'Cậu bé chuyển đến một nơi như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-003', 'esl-fast-beginner-1-25', 'What are there many of in the new city?', 'Có rất nhiều gì ở thành phố mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-004', 'esl-fast-beginner-1-25', 'What are many people doing?', 'Có nhiều người đang làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-005', 'esl-fast-beginner-1-25', 'What kind of cars are mentioned?', 'Loại xe nào được nhắc đến?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-006', 'esl-fast-beginner-1-25', 'How does he feel in the new city?', 'Cậu bé cảm thấy thế nào ở thành phố mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-007', 'esl-fast-beginner-1-25', 'Why might he feel lonely?', 'Tại sao cậu bé có thể cảm thấy cô đơn?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-008', 'esl-fast-beginner-1-25', 'How do people act in the new city?', 'Mọi người cư xử như thế nào ở thành phố mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-009', 'esl-fast-beginner-1-25', 'Where does he go after moving?', 'Sau khi chuyển nhà, cậu bé đi đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-010', 'esl-fast-beginner-1-25', 'What does he see at his new school?', 'Cậu bé nhìn thấy gì ở trường mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-011', 'esl-fast-beginner-1-25', 'What does the person look like?', 'Người đó trông như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-012', 'esl-fast-beginner-1-25', 'Who does he meet at school?', 'Cậu bé gặp ai ở trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-013', 'esl-fast-beginner-1-25', 'What does he ask the person to do?', 'Cậu bé nhờ người đó làm gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-014', 'esl-fast-beginner-1-25', 'Does he know the new city well?', 'Cậu bé có biết rõ thành phố mới không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-015', 'esl-fast-beginner-1-25', 'Is the new city crowded?', 'Thành phố mới có đông đúc không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-016', 'esl-fast-beginner-1-25', 'What is different about the new place?', 'Điều gì khác biệt ở nơi mới?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-017', 'esl-fast-beginner-1-25', 'What does he notice first about the city?', 'Cậu bé chú ý điều gì đầu tiên về thành phố?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-018', 'esl-fast-beginner-1-25', 'What does he notice about the people?', 'Cậu bé nhận thấy điều gì về mọi người?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-019', 'esl-fast-beginner-1-25', 'Where are many people walking?', 'Có nhiều người đang đi bộ ở đâu?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-020', 'esl-fast-beginner-1-25', 'What makes the city look busy?', 'Điều gì khiến thành phố trông nhộn nhịp?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-021', 'esl-fast-beginner-1-25', 'What does he do when he gets to school?', 'Cậu bé làm gì khi đến trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-022', 'esl-fast-beginner-1-25', 'Does he find someone friendly?', 'Cậu bé có gặp một người thân thiện không?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-023', 'esl-fast-beginner-1-25', 'How does the person seem?', 'Người đó có vẻ như thế nào?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-024', 'esl-fast-beginner-1-25', 'What does he need help with?', 'Cậu bé cần giúp đỡ về việc gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-025', 'esl-fast-beginner-1-25', 'What does “show him around” mean?', '“Show him around” có nghĩa là gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-026', 'esl-fast-beginner-1-25', 'Why does he talk to the friendly-looking person?', 'Tại sao cậu bé nói chuyện với người trông thân thiện?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-027', 'esl-fast-beginner-1-25', 'What is the boy experiencing?', 'Cậu bé đang trải qua điều gì?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-028', 'esl-fast-beginner-1-25', 'What happens before he goes to school?', 'Điều gì xảy ra trước khi cậu bé đến trường?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-029', 'esl-fast-beginner-1-25', 'What happens at the end of the story?', 'Điều gì xảy ra ở cuối câu chuyện?', 'ACTIVE', NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-030', 'esl-fast-beginner-1-25', 'What is the main idea of the story?', 'Ý chính của câu chuyện là gì?', 'ACTIVE', NULL, NULL, NULL, NULL);