INSERT INTO CONTENTS (ENG,VI,START_TIME,END_TIME, VOLUME_SLUG) VALUES
	/* ('Nightmare Tales - Lesson 1: The Writer','Những Câu Chuyện Ác Mộng - Bài 1: Nhà Văn','00:00:00.000','00:05:45.000','nightmare-tales-1'), */
	('Several years ago, a young writer rented a remote lakeside cabin in the mountains, so he could free himself of distractions and interruptions while he worked on his next novel','Vài năm trước, một nhà văn trẻ đã thuê một căn nhà gỗ nhỏ hẻo lánh ven hồ ở trong ngọn núi, để anh ấy có thể tránh xa các sao nhãng và gián đoạn trong lúc sáng tác cuốn tiểu thuyết sắp tới của mình','00:00:01.029','00:00:12.200','nightmare-tales-1'),
	('In his first week, he managed to accomplish an impressive amount of work and even though the feelings of being isolated and lonely were ever-present, he still felt as if someone was there watching him','Vào tuần đầu tiên, anh ta đã hoàn thành được một khối lượng công việc khá ấn tượng, và mặc dù cảm giác bị cô lập và cô đơn luôn hiện hữu, anh vẫn cảm thấy như có ai đó đang theo dõi mình','00:00:12.800','00:00:24.990','nightmare-tales-1'),
	('Then, late on a Sunday afternoon, he heard what he thought was someone calling his name','Rồi, vào cuối chiều Chủ Nhật, anh nghe thấy một chuyện mà anh nghĩ là ai đó đang gọi tên mình','00:00:26.100','00:00:32.950','nightmare-tales-1'),
	('Peter','Peter','00:00:32.950','00:00:35.800','nightmare-tales-1'),
	('He quickly disregarded this and put it down to having become overly perceptive to noises and his creative imagination running wild','Anh nhanh chóng bỏ qua điều này và cho rằng đó là do quá nhạy cảm với tiếng động, và trí tưởng tượng sáng tạo của anh đang trở nên mất kiểm soát','00:00:36.300','00:00:43.900','nightmare-tales-1'),
	('Then it happened again and again, and then it was so clear he had no doubt it was his name that was being called','Rồi nó lại xảy ra, lại lần nữa, và rồi rõ ràng đến mức anh không còn nghi ngờ gì nữa, đó là tên anh đang được gọi','00:00:44.500','00:00:57.960','nightmare-tales-1'),
	('He left his desk and went over to the window to see where it was coming from','Anh rời khỏi bàn làm việc và bước đến cửa sổ để xem nó phát ra từ đâu','00:00:59.860','00:01:04.700','nightmare-tales-1'),
	('In a large, old house not far away from his cabin, which he previously thought was unoccupied, was a small boy who was clearly calling his name and waving at him','Trong một ngôi nhà lớn, cũ kỹ không xa căn nhà gỗ của anh, nơi mà anh lúc trước nghĩ là không có người ở, có một cậu bé đang gọi rõ ràng tên anh và vẫy tay với anh','00:01:05.300','00:01:20.200','nightmare-tales-1'),
	('The man was extremely unsettled by this and waved back to the boy','Người đàn ông cảm thấy vô cùng bất an vì điều này, và vẫy tay lại với cậu bé','00:01:21.200','00:01:25.600','nightmare-tales-1'),
	('The boy then moved away from the window and the man was left standing there, wondering how the hell this boy knew his name','Cậu bé sau đó rời khỏi cửa sổ, để lại người đàn ông đứng đó, thắc mắc thế quái nào cậu bé lại biết được tên mình','00:01:26.300','00:01:34.600','nightmare-tales-1'),
	('He pondered the possibilities and finally figured that the cabin he had rented must have belonged to the family who lived there and the agent had gone and let them know who he was','Anh suy ngẫm về các khả năng, và cuối cùng nhận ra rằng căn nhà gỗ mà anh đã thuê hẳn là của gia đình từng sống ở đó, và người đại diện đã đến và cho họ biết về anh','00:01:35.100','00:01:45.500','nightmare-tales-1'),
	('A little annoyed at this, but not letting it get to him, he returned to his work','Hơi bực bội vì điều này, nhưng anh không để tâm, anh quay lại công việc','00:01:46.200','00:01:51.200','nightmare-tales-1'),
	('A few nights later, while he was sleeping, he heard his name being called again','Vài đêm sau, khi anh đang ngủ, anh lại nghe thấy tên mình được gọi','00:01:52.500','00:01:57.900','nightmare-tales-1'),
	('Once again, he first thought it was the wind','Một lần nữa, ban đầu anh nghĩ đó là tiếng gió','00:02:00.350','00:02:03.200','nightmare-tales-1'),
	('It soon became so clear there was no doubt','Nó rất nhanh trở nên rõ ràng đến mức không thể nghi ngờ','00:02:03.000','00:02:06.500','nightmare-tales-1'),
	('This child was calling his name again','Đứa bé này lại đang gọi tên anh','00:02:09.090','00:02:11.700','nightmare-tales-1'),
	('He got up and went over to the window','Anh đứng dậy và đi đến cửa sổ','00:02:12.560','00:02:15.200','nightmare-tales-1'),
	('To his shock, the little boy was standing outside his window, wearing nothing but a pair of shorts','Trước cú sốc của anh, cậu bé đang đứng bên ngoài cửa sổ, không mặc gì mà ngoài một chiếc quần đùi','00:02:15.200','00:02:22.200','nightmare-tales-1'),
	('The little boy smiled at him and said, "Peter, teach me to swim"','Cậu bé mỉm cười với anh và nói, "Peter, dạy em bơi đi"','00:02:23.120','00:02:29.200','nightmare-tales-1'),
	('The man thought he must be dreaming','Chàng trai nghĩ rằng mình hẳn là đang mơ','00:02:29.300','00:02:31.360','nightmare-tales-1'),
	('"What the hell is going on?", he thought','"Chuyện quái gì đang xảy ra vậy?", anh nghĩ','00:02:32.000','00:02:34.200','nightmare-tales-1'),
	('He scowled back at the boy','Anh cau mày lại với cậu bé','00:02:34.700','00:02:36.100','nightmare-tales-1'),
	('"No, it\'s the middle of the night"','"Không, bây giờ là nửa đêm"','00:02:36.200','00:02:38.500','nightmare-tales-1'),
	('"Go home"','"Về nhà đi"','00:02:38.600','00:02:39.600','nightmare-tales-1'),
	('The little boy\'s sweet smile suddenly turned to one of anger and he turned and ran back to the old house across the way','Nụ cười ngọt ngào của cậu bé bỗng chuyển sang giận dữ, và cậu quay người lại và chạy về ngôi nhà cũ bên kia đường','00:02:40.200','00:02:46.700','nightmare-tales-1'),
	('The man angry and still in disbelief, returned to his bed','Chàng trai giận dữ và vẫn không thể tin được, quay lại giường','00:02:47.800','00:02:52.400','nightmare-tales-1'),
	('But with this strange event playing on his mind, he could not fall asleep for the rest of the night','Nhưng với việc kỳ lạ này ám ảnh trong đầu, anh không thể ngủ lại cho đến hết đêm','00:02:52.900','00:02:59.200','nightmare-tales-1'),
	('The next morning, tired and angry, he went over to the old house to talk to the parents of the small child','Sáng hôm sau, mệt mỏi và giận dữ, anh đi đến ngôi nhà cổ để nói chuyện với cha mẹ của đứa trẻ','00:03:00.300','00:03:06.600','nightmare-tales-1'),
	('He knocked on the door and was slightly taken aback when an old lady answered the door','Anh gõ cửa và hơi bất ngờ khi một bà lão mở cửa','00:03:07.200','00:03:12.400','nightmare-tales-1'),
	('He got straight to it','Anh vào ngay vấn đề','00:03:13.000','00:03:14.400','nightmare-tales-1'),
	('"Did you know your little boy was out last night?"','Bà có biết thằng bé nhà bà đã ra ngoài tối qua không?','00:03:14.500','00:03:16.900','nightmare-tales-1'),
	('"He came to my window and asked to go swimming"','"Nó đến cửa sổ của tôi và yêu cầu đi bơi đấy"','00:03:17.000','00:03:19.400','nightmare-tales-1'),
	('The old lady looked at him, her face turning to anger','Bà lão nhìn anh, mặt bà chuyển sang tức giận','00:03:20.100','00:03:23.500','nightmare-tales-1'),
	('To his surprise, her face then turned to sadness and tears began to roll down her face','Trước sự ngạc nhiên của anh, gương mặt bà chuyển sang buồn bã, và nước mắt bắt đầu lăn xuống trên khuôn mặt bà','00:03:24.000','00:03:29.500','nightmare-tales-1'),
	('"This is a very cruel joke", she said to him','"Đây là một trò đùa rất tàn nhẫn", bà nói với anh','00:03:30.000','00:03:33.200','nightmare-tales-1'),
	('"What are you talking about?", he asked','"Bà đang nói về chuyện gì vậy?", anh hỏi','00:03:33.700','00:03:35.700','nightmare-tales-1'),
	('"My little boy drowned in the lake twenty years ago", she said','"Con trai tôi đã chết đuối ở hồ cách đây hai mươi năm", bà nói','00:03:36.300','00:03:40.700','nightmare-tales-1'),
	('A chill instantly ran through the man','Một cơn ớn lạnh lập tức chạy khắp người chàng trai','00:03:41.200','00:03:43.700','nightmare-tales-1'),
	('"But what about...", he began','"Nhưng thế còn...", anh bắt đầu','00:03:44.400','00:03:45.900','nightmare-tales-1'),
	('But before he could finish, she slammed the door and left him standing there, confused and scared','Nhưng trước khi anh kịp nói hết câu, bà đóng sầm cửa lại, để anh đứng đó, bối rối và sợ hãi','00:03:46.500','00:03:51.700','nightmare-tales-1'),
	('He went back to the cabin and that night, he again did not manage to get one wink of sleep as he pondered if he really had seen the little boy, or if he was slowly going insane','Anh quay lại căn nhà gỗ, và đêm đó, anh lại không thể chợp mắt được khi anh đang suy ngẫm liệu anh có thực sự nhìn thấy cậu bé, hay liệu anh đang dần phát điên','00:03:52.600','00:04:05.700','nightmare-tales-1'),
	('After a few sleepless nights and unsettled days, he found he had hit a wall with his writing and just couldn\'t continue his work','Sau vài đêm mất ngủ và những ngày bất an, anh thấy mình đã gặp bế tắc trong việc viết và thực sự không thể tiếp tục công việc của mình','00:04:07.300','00:04:14.200','nightmare-tales-1'),
	('He felt he needed to take a break and refocus','Anh cảm thấy mình cần phải nghỉ ngơi và tập trung lại','00:04:14.800','00:04:17.500','nightmare-tales-1'),
	('The weather had warmed up slightly, so he decided a relaxing swim would be exactly what he needed to help him clear his head and put the strange happenings behind him','Thời tiết đang ấm dần lên một chút, vì vậy anh quyết định đi bơi thư giãn đúng sẽ là điều anh cần để giúp anh loại bỏ căng thẳng và để qua những sự việc kỳ lạ lại phía sau','00:04:18.200','00:04:27.800','nightmare-tales-1'),
	('He ventured into the water and immediately felt better','Anh mạo hiểm bước xuống nước và lập tức cảm thấy tốt hơn','00:04:28.500','00:04:31.700','nightmare-tales-1'),
	('He floated on his back and contentedly let all the stress and worry float away','Anh nằm ngửa trôi nổi trên mặt nước trên mặt nước, thư thái để mọi căng thẳng và lo lắng trôi đi','00:04:32.200','00:04:37.400','nightmare-tales-1'),
	('Then suddenly, he heard it again "Peter"','Rồi đột nhiên, anh lại nghe thấy cái đó "Peter"','00:04:38.820','00:04:43.500','nightmare-tales-1'),
	('The muffled sound of the boy calling his name','Âm thanh nghèn nghẹn của cậu bé gọi tên anh','00:04:43.800','00:04:46.900','nightmare-tales-1'),
	('Where was it coming from?','Nó phát ra từ đâu?','00:04:47.500','00:04:48.900','nightmare-tales-1'),
	('He heard it again "Peter"','Anh lại nghe thấy nó lần nữa "Peter"','00:04:49.500','00:04:53.100','nightmare-tales-1'),
	('It was then he realized it was below him','Lúc đó anh mới nhận ra nó tới từ phía dưới mình','00:04:53.300','00:04:57.980','nightmare-tales-1'),
	('He ducked his head into the water and saw him, slowly floating up toward him','Anh lặn xuống nước, và thấy cậu bé, từ từ nổi lên tiến về phía anh','00:04:59.000','00:05:04.700','nightmare-tales-1'),
	('The unsettling smile on his face suddenly changed to a look of pure evil as he then latched onto his ankle','Nụ cười bất an trên khuôn mặt cậu bé đột ngột chuyển thành biểu cảm cực kỳ tà ác khi nó chộp lấy mắt cá chân của anh','00:05:05.000','00:05:12.700','nightmare-tales-1'),
	('Incredibly distressed, the man tried to scramble for the surface but he couldn\'t shake it off and was slowly pulled into the cold, deep darkness to his death','Đau khổ tột cùng, chàng trai cố gắng vật lộn để nổi lên mặt nước nhưng anh không thể thoát ra, và từ từ bị kéo vào bóng tối lạnh lẽo, sâu thẳm để rồi đến với cái chết','00:05:13.300','00:05:24.200','nightmare-tales-1'),
	('Weeks later, after the man\'s publisher failed to get in contact with him, the police were sent out to try and make contact','Vài tuần sau, sau khi nhà xuất bản của chàng trai không thể liên lạc được với anh, cảnh sát đã được cử đến để thử tìm cách liên lạc','00:05:26.400','00:05:33.300','nightmare-tales-1'),
	('They would never find him','Họ sẽ không bao giờ tìm thấy anh','00:05:34.200','00:05:35.500','nightmare-tales-1'),
	('What became of him is only known by the eyes that watch over the cabin and your every move','Điều gì đã xảy ra với anh chỉ được biết bởi những đôi mắt đang giám sát căn nhà gỗ, và từng hành động của bạn','00:05:36.200','00:05:44.500','nightmare-tales-1'),
	
	
	/* ('Nightmare Tales - Lesson 2: The bus stop','Những Câu Chuyện Ác Mộng - Bài 2: Trạm xe buýt','00:00:00.000','00:02:58.720','nightmare-tales-2'), */
	('On a dark autumn night, a lady who had just finished conducting a training session at a factory in the countryside stood alone at a bus stop, patiently waiting for the bus to arrive and take her back into the city','Vào một đêm mùa thu tăm tối, một người phụ nữ vừa hoàn thành một buổi huấn luyện tại nhà máy ở vùng nông thôn, đứng một mình tại trạm xe buýt, kiên nhẫn chờ xe đến để đưa cô quay lại thành phố','00:00:07.880','00:00:23.300','nightmare-tales-2'),
	('Ten minutes had passed','Mười phút đã trôi qua','00:00:24.820','00:00:26.380','nightmare-tales-2'),
	('The bus should have arrived by now, she thought to herself','Xe buýt đáng lẽ phải đến rồi, cô nghĩ thầm','00:00:27.400','00:00:30.160','nightmare-tales-2'),
	('And yet, there she still was, waiting','Và vậy là, cô vẫn đứng đó, chờ đợi','00:00:30.720','00:00:34.360','nightmare-tales-2'),
	('Then, out of the corner of her eye, she saw something','Sau đó, ở khóe mắt, cô nhìn thấy một thứ gì đó','00:00:35.540','00:00:39.440','nightmare-tales-2'),
	('A man was slowly approaching towards the bus stop and her','Một người đàn ông đang từ từ tiến lại gần trạm xe buýt và cô','00:00:40.480','00:00:45.100','nightmare-tales-2'),
	('Please don\'t be a weirdo, she thought to herself','Xin đừng là một người kỳ quặc, cô nghĩ thầm','00:00:46.920','00:00:49.620','nightmare-tales-2'),
	('Where the hell is this bus?','Cái xe buýt này ở đâu chứ?','00:00:50.520','00:00:52.500','nightmare-tales-2'),
	('Sure enough, when the person entered the light of the bus stop, she was filled with a feeling of dread','Quả thật, khi người đó bước vào ánh sáng của trạm xe buýt, cô cảm thấy một nỗi sợ hãi tràn ngập','00:00:53.410','00:00:59.660','nightmare-tales-2'),
	('She looked homeless and reeked of a foul odor','Ông ta trông như người vô gia cư và bốc mùi hôi thối','00:01:00.620','00:01:04.040','nightmare-tales-2'),
	('Three dollars, he said','Ba đô la, ông nói','00:01:05.620','00:01:08.280','nightmare-tales-2'),
	('Excuse me, she replied','Xin lỗi, cô trả lời','00:01:09.280','00:01:11.280','nightmare-tales-2'),
	('Three dollars, he repeated','Ba đô la, ông nhắc lại','00:01:12.500','00:01:15.000','nightmare-tales-2'),
	('Um, I\'m sorry, I don\'t have three dollars, she replied','Ừm, xin lỗi, tôi không có ba đô la, cô đáp','00:01:15.000','00:01:19.400','nightmare-tales-2'),
	('And then, he just stood there, silently staring at her','Và rồi, ông ta chỉ đứng đó, lặng lẽ nhìn cô','00:01:20.380','00:01:25.580','nightmare-tales-2'),
	('She became quite afraid at this point and was about to ask him to move away when he spoke again','Lúc này, cô bắt đầu thực sự sợ hãi và định bảo ông ta tránh xa ra thì ông lại lên tiếng','00:01:26.720','00:01:32.140','nightmare-tales-2'),
	('Three dollars','Ba đô la','00:01:33.040','00:01:34.220','nightmare-tales-2'),
	('She had had enough','Cô đã chịu đựng quá đủ','00:01:35.460','00:01:36.320','nightmare-tales-2'),
	('This guy was genuinely giving her the creeps and she felt scared and vulnerable','Người này thực sự khiến cô cảm thấy rùng mình, sợ hãi và yếu đuối','00:01:36.560','00:01:40.760','nightmare-tales-2'),
	('Look, I don\'t have three dollars, she snapped at him','Nghe này, tôi không có ba đô la, cô cáu kỉnh đáp lại','00:01:41.480','00:01:44.180','nightmare-tales-2'),
	('Now leave me alone, or I\'ll call the police','Giờ tránh ra, nếu không tôi sẽ gọi cảnh sát','00:01:44.180','00:01:46.600','nightmare-tales-2'),
	('He looked at her, then he looked around, and then, just left','Ông ta nhìn cô, rồi nhìn xung quanh, và sau đó, chỉ bỏ đi','00:01:47.160','00:01:52.880','nightmare-tales-2'),
	('He walked past her and headed on his way down the road, into the night','Ông ta đi ngang qua cô và tiến về phía con đường, chìm vào màn đêm','00:01:53.800','00:01:59.400','nightmare-tales-2'),
	('He had moved on, but this certainly didn\'t make her feel any better','Ông ta đã rời đi, nhưng điều này chắc chắn không làm cô cảm thấy đỡ hơn chút nào','00:02:00.640','00:02:04.280','nightmare-tales-2'),
	('She replayed in her head what had just transpired, and then quickly began to think of what she should do next','Cô nghĩ lại trong đầu những gì vừa xảy ra, rồi nhanh chóng bắt đầu suy nghĩ nên làm gì tiếp theo','00:02:05.240','00:02:11.100','nightmare-tales-2'),
	('She was all alone, in an unfamiliar area, waiting for a bus that looked like it would never come','Cô đang một mình ở một nơi xa lạ, chờ đợi một chuyến xe buýt có vẻ như sẽ không bao giờ đến','00:02:11.880','00:02:19.520','nightmare-tales-2'),
	('Now, she felt extremely frightened','Lúc này, cô cảm thấy vô cùng sợ hãi','00:02:21.160','00:02:23.460','nightmare-tales-2'),
	('What if he came back?','Nếu ông ta quay lại thì sao?','00:02:24.160','00:02:25.240','nightmare-tales-2'),
	('What would she do then?','Khi đó cô sẽ làm gì?','00:02:25.840','00:02:26.900','nightmare-tales-2'),
	('As she decided to get her phone and call a taxi, the bus arrived','Khi cô quyết định lấy điện thoại và gọi taxi thì xe buýt đến','00:02:27.840','00:02:32.160','nightmare-tales-2'),
	('Oh, thank goodness, she thought','Ôi, cảm ơn trời, cô nghĩ thầm','00:02:33.080','00:02:35.140','nightmare-tales-2'),
	('And as soon as the door opened, she jumped aboard and took a seat','Và ngay khi cửa mở, cô nhảy lên xe và ngồi xuống','00:02:35.880','00:02:39.180','nightmare-tales-2'),
	('Her heart was racing, but she was safe','Tim cô đập thình thịch, nhưng cô đã an toàn','00:02:39.840','00:02:42.440','nightmare-tales-2'),
	('The door closed and she asked the driver, how much?','Cửa đóng lại và cô hỏi người lái xe, bao nhiêu?','00:02:43.140','00:02:46.760','nightmare-tales-2'),
	('The driver replied, three dollars','Người lái xe trả lời, ba đô la','00:02:47.460','00:02:50.460','nightmare-tales-2'),
	('As he knocked her unconscious, switched out the lights, and then drove away, off, into the night','Khi ông ta đánh cô ngất đi, tắt đèn, rồi lái xe đi, mất hút trong màn đêm','00:02:51.460','00:02:58.720','nightmare-tales-2'),

	
	/* ('Nightmare Tales - Lesson 3: The park','Những Câu Chuyện Ác Mộng - Bài 3: Công Viên','00:00:00.000','00:03:16.870','nightmare-tales-3'), */
	('The day was warm and the weather was perfect','Ngày hôm đó trời ấm áp và thời tiết hoàn hảo','00:00:04.870','00:00:07.590','nightmare-tales-3'),
	('Perfect for a day in the park','Hoàn hảo cho một ngày ở công viên','00:00:08.330','00:00:10.270','nightmare-tales-3'),
	('A young mother and her little girl relaxed contentedly on the lush green grass, breathed in the fresh summer air and listened to the world go by','Một người mẹ trẻ và cô con gái nhỏ thư giãn thoải mái trên thảm cỏ xanh mượt, hít thở không khí mùa hè trong lành và lắng nghe thế giới xung quanh','00:00:11.010','00:00:19.710','nightmare-tales-3'),
	('The little girl, lying down on her back, was entertaining herself by trying to make out the different objects in the clouds','Cô bé, nằm ngửa, tự giải trí bằng cách cố gắng nhận ra các hình thù khác nhau trong những đám mây','00:00:20.830','00:00:27.370','nightmare-tales-3'),
	('She laughed as she made out a pig, followed by a mouse that looked like it was chasing some cheese','Cô bé cười khi nhận ra một con heo, tiếp đến là một con chuột dường như đang đuổi theo miếng pho mát','00:00:28.370','00:00:34.190','nightmare-tales-3'),
	('She could do this for hours as her overactive imagination never failed to entertain her','Cô bé có thể làm điều này hàng giờ vì trí tưởng tượng phong phú của cô không bao giờ làm cô buồn chán','00:00:34.970','00:00:40.250','nightmare-tales-3'),
	('Then she became a little scared as she saw what she thought was the face of a demon floating by and stared right at her and sent a chill through her body','Sau đó, cô bé hơi sợ khi nhìn thấy một thứ giống như khuôn mặt của quỷ lướt qua và nhìn chằm chằm vào cô, khiến cơ thể cô lạnh toát','00:00:41.230','00:00:51.910','nightmare-tales-3'),
	('She closed her eyes and waited a few moments, and then when she opened them again, it was gone','Cô bé nhắm mắt lại chờ một lúc, rồi khi mở mắt ra, thứ đó đã biến mất','00:00:53.090','00:00:58.730','nightmare-tales-3'),
	('She felt relieved by this but didn\'t feel like continuing her game','Cô bé cảm thấy nhẹ nhõm vì điều này nhưng không muốn tiếp tục trò chơi của mình','00:00:59.990','00:01:03.349','nightmare-tales-3'),
	('She shut her eyes and tried to think happy thoughts as she just focused on breathing in the fresh air and relaxing in the sun','Cô bé nhắm mắt lại và cố gắng nghĩ về những điều vui vẻ khi cô chỉ tập trung vào hít thở không khí trong lành và thư giãn dưới ánh nắng mặt trời','00:01:03.709','00:01:11.330','nightmare-tales-3'),
	('To the left of them, a foul ball from a baseball field flew over the fence and straight toward where she and her mother were sitting','Bên trái họ, một quả bóng baseball từ sân bay qua hàng rào và bay thẳng đến chỗ cô bé và mẹ cô đang ngồi','00:01:13.030','00:01:19.390','nightmare-tales-3'),
	('At the last second, the mother reached out and caught the ball','Ngay giây cuối cùng, người mẹ đã vươn tay và bắt lấy quả bóng','00:01:20.050','00:01:22.910','nightmare-tales-3'),
	('If she hadn\'t, it would have smashed into the little girl\'s skull at full speed','Nếu không, quả bóng sẽ đập vào hộp sọ của cô bé với tốc độ tối đa','00:01:22.910','00:01:27.250','nightmare-tales-3'),
	('The mother, furious at how careless these baseball players were, decided to head over to the field and give them a piece of her mind','Người mẹ, giận dữ với sự bất cẩn của các cầu thủ baseball này, quyết định tiến về sân và mắng họ một trận','00:01:28.010','00:01:34.990','nightmare-tales-3'),
	('Don\'t go anywhere, she said to the little girl as she walked away into the distance','Đừng đi đâu, bà nói với cô bé khi bà bước đi xa dần','00:01:35.750','00:01:40.230','nightmare-tales-3'),
	('The little girl lay back down and closed her eyes','Cô bé nằm xuống và nhắm mắt lại','00:01:41.610','00:01:44.150','nightmare-tales-3'),
	('She didn\'t want to look at the clouds anymore','Cô bé không muốn nhìn những đám mây nữa','00:01:44.850','00:01:46.470','nightmare-tales-3'),
	('She felt sick','Cô bé cảm thấy buồn nôn','00:01:47.310','00:01:48.070','nightmare-tales-3'),
	('She just wanted her mother to come back so they could go home','Cô bé chỉ muốn mẹ trở về để họ có thể cùng nhau về nhà','00:01:48.070','00:01:52.170','nightmare-tales-3'),
	('A few moments passed','Một vài khoảnh khắc trôi qua','00:01:53.130','00:01:54.490','nightmare-tales-3'),
	('However, when the little girl opened her eyes again, the day had turned to night and there was no one around','Tuy nhiên, khi cô bé mở mắt ra lần nữa, trời đã chuyển sang đêm và không có ai xung quanh','00:01:55.110','00:02:01.290','nightmare-tales-3'),
	('Not a sound to be heard','Không có âm thanh nào vang lên','00:02:02.050','00:02:03.810','nightmare-tales-3'),
	('Mama, she called, but there was no answer','Mẹ ơi, cô bé gọi, nhưng không có tiếng trả lời','00:02:05.010','00:02:07.770','nightmare-tales-3'),
	('Mama, she called again, but still, there was nothing','Mẹ ơi, cô bé lại gọi, nhưng vẫn không có gì','00:02:08.710','00:02:12.410','nightmare-tales-3'),
	('She was frightened and all alone','Cô bé sợ hãi và cô độc','00:02:13.390','00:02:15.210','nightmare-tales-3'),
	('And then, she saw..','Và rồi, cô bé thấy..','00:02:15.930','00:02:19.210','nightmare-tales-3'),
	('her','cô bé ấy','00:02:19.210','00:02:19.670','nightmare-tales-3'),
	('A small child','Một đứa trẻ nhỏ','00:02:21.010','00:02:22.590','nightmare-tales-3'),
	('A girl, who was sitting on the swing, all alone','Một cô bé, ngồi trên xích đu, hoàn toàn cô đơn','00:02:23.410','00:02:26.830','nightmare-tales-3'),
	('The little girl looked around for her mother or for anyone else, but there was no one','Cô bé nhìn quanh tìm mẹ hoặc ai đó, nhưng không có ai cả','00:02:27.890','00:02:32.490','nightmare-tales-3'),
	('It was just her and this scary little child','Chỉ có cô bé và đứa trẻ nhỏ đáng sợ này','00:02:33.150','00:02:36.870','nightmare-tales-3'),
	('Who are you?','Bạn là ai?','00:02:37.870','00:02:38.890','nightmare-tales-3'),
	('the little girl called out, but the girl on the swing didn\'t answer','cô bé cất tiếng gọi, nhưng cô bé trên xích đu không trả lời','00:02:38.950','00:02:42.230','nightmare-tales-3'),
	('In the blink of an eye, she was closer','Chỉ trong chớp mắt, cô bé đã tiến gần hơn','00:02:42.230','00:02:45.690','nightmare-tales-3'),
	('And another, closer still','Và một chớp mắt nữa, gần hơn nữa','00:02:47.490','00:02:49.530','nightmare-tales-3'),
	('They were now face to face with each other','Giờ đây họ đã đối mặt với nhau','00:02:50.530','00:02:52.530','nightmare-tales-3'),
	('Who are you?','Bạn là ai?','00:02:53.430','00:02:54.850','nightmare-tales-3'),
	('she asked again','cô bé lại hỏi','00:02:55.030','00:02:55.890','nightmare-tales-3'),
	('The girl looked up and a deathly chill ran through the little girl as she looked into her own eyes, which was followed by a chilling, I\'m you','Cô bé ngước nhìn lên và một cảm giác lạnh lẽo chết chóc chạy qua khi cô bé nhìn vào đôi mắt của chính mình, rồi tiếp theo là tiếng thì thầm rùng rợn: Ta là ngươi','00:02:56.690','00:03:06.710','nightmare-tales-3'),
	('She grabbed the little girl by the neck and although there was a struggle, there was no way she could stop being dragged down into the depths of the earth and into the afterlife','Cô bé nắm lấy cổ của chính mình và dù có vùng vẫy, không đời nào cô bé có thể ngăn cản bị kéo xuống sâu dưới lòng đất và vào cõi chết','00:03:07.510','00:03:16.870','nightmare-tales-3'),
	
	
	/* ('Nightmare Tales - Lesson 4: The hotel','Những Câu Chuyện Ác Mộng - Bài 4: Khách sạn','00:00:06.020','00:04:57.620','nightmare-tales-4'), */
	('On a cold and dark Friday night, a young couple had just completed their long journey into the mountains, for a weekend away at an extremely secluded and exclusive resort hotel','Vào một đêm thứ Sáu lạnh lẽo và tối tăm, một đôi trẻ vừa hoàn thành chuyến đi dài vào núi, để tận hưởng cuối tuần tại một khách sạn khu nghỉ dưỡng cực kỳ hẻo lánh và độc quyền','00:00:06.020','00:00:17.280','nightmare-tales-4'),
	('Earlier that day, the man had surprised his girlfriend by picking her up from work with her bags already packed','Trước đó trong ngày, người đàn ông đã gây bất ngờ cho bạn gái mình khi đến đón cô từ chỗ làm với hành lý của cô đã được sắp xếp sẵn','00:00:18.600','00:00:24.280','nightmare-tales-4'),
	('The girl was very impressed and was excited to stay at what looked like a beautiful and luxurious hotel','Cô gái rất ấn tượng và háo hức ở lại một khách sạn trông có vẻ đẹp và sang trọng','00:00:25.020','00:00:30.900','nightmare-tales-4'),
	('When they entered the lobby, it was slightly unsettled that not only was there no one at the reception to greet them, there was no one to be seen anywhere','Khi họ bước vào sảnh, có một chút khó chịu khi không chỉ không có ai ở quầy lễ tân để chào đón họ, mà cũng không thấy ai ở bất kỳ đâu','00:00:33.040','00:00:41.720','nightmare-tales-4'),
	('At first she thought that her boyfriend had failed to make a booking, but then she noticed their key, just left on the desk with a tag that read, Davis, room','Lúc đầu cô nghĩ bạn trai mình đã không đặt phòng, nhưng sau đó cô thấy chìa khóa của họ, được để lại trên bàn với một thẻ ghi, Davis, phòng','00:00:42.820','00:00:53.280','nightmare-tales-4'),
	('Figuring that the hotel had some staffing issues, they took the key and made their way up to the room','Cho rằng khách sạn có vấn đề về nhân sự, họ lấy chìa khóa và đi lên phòng','00:00:55.260','00:01:00.180','nightmare-tales-4'),
	('When they got to their room, they were both a little surprised at what they saw','Khi họ đến phòng của mình, cả hai đều hơi ngạc nhiên với những gì họ thấy','00:01:01.880','00:01:06.220','nightmare-tales-4'),
	('The furnishings of the room were extremely dated, in fact, it was so old there was no en-suite bathroom, they would have to use the communal one, which was located all the way at the other end of the cold, dark hallway','Nội thất trong phòng cực kỳ cổ, thực tế, nó cũ đến mức không có phòng tắm riêng, họ phải sử dụng phòng tắm chung, nằm ở đầu kia của hành lang lạnh lẽo và tối tăm','00:01:07.120','00:01:19.280','nightmare-tales-4'),
	('The room also had iron bars on the inside of the windows, for security reasons they figured, but it still certainly seemed a bit off-putting and did nothing to add to a warm romantic atmosphere','Phòng cũng có thanh sắt bên trong cửa sổ, họ nghĩ là vì lý do an ninh, nhưng nó vẫn có vẻ hơi khó chịu và không hề tạo nên bầu không khí ấm áp lãng mạn','00:01:20.120','00:01:31.720','nightmare-tales-4'),
	('They decided they could bear this for one night and once they managed to see some staff members, they would ask for another room, or just leave','Họ quyết định có thể chịu đựng qua một đêm và khi gặp nhân viên, họ sẽ yêu cầu một phòng khác hoặc rời đi','00:01:32.920','00:01:41.780','nightmare-tales-4'),
	('They got settled in and the woman ventured down the hall and enjoyed a nice hot shower','Họ ổn định chỗ ở và cô gái đi xuống hành lang và tận hưởng một buổi tắm nước nóng dễ chịu','00:01:42.800','00:01:48.460','nightmare-tales-4'),
	('At least the water is hot and the bathroom is clean, she thought to herself','Ít nhất nước còn nóng và phòng tắm sạch sẽ, cô nghĩ thầm','00:01:49.300','00:01:52.660','nightmare-tales-4'),
	('It was then, she thought she heard voices','Vào lúc đó, cô nghĩ rằng mình nghe thấy tiếng nói','00:01:53.480','00:01:57.960','nightmare-tales-4'),
	('She turned off the water and listened intently','Cô tắt nước và lắng nghe cẩn thận','00:01:59.460','00:02:01.700','nightmare-tales-4'),
	('What she heard next chilled her to the bone, it was a man\'s voice, saying they would come tonight to take the girl','Những gì cô nghe tiếp theo làm cô lạnh cả người, đó là giọng của một người đàn ông, nói rằng họ sẽ đến tối nay để bắt cô gái','00:02:02.280','00:02:10.160','nightmare-tales-4'),
	('This sent a shiver through her spine and she immediately finished her shower in order to get out of there','Điều này khiến cô rùng mình và cô lập tức hoàn tất việc tắm để rời khỏi đó','00:02:10.980','00:02:15.680','nightmare-tales-4'),
	('She peered out from behind the door expecting to see someone and to her surprise, the hallway was completely empty','Cô liếc nhìn ra từ sau cánh cửa, mong đợi thấy ai đó, và ngạc nhiên khi thấy hành lang hoàn toàn trống rỗng','00:02:16.220','00:02:24.320','nightmare-tales-4'),
	('She went back to the room, and then told her boyfriend what she had heard','Cô quay trở lại phòng, rồi kể với bạn trai những gì cô đã nghe thấy','00:02:25.320','00:02:28.360','nightmare-tales-4'),
	('He told her she was crazy, as he\'s had a look around while she was showering, there was no one in the entire hotel','Anh bảo cô thật điên rồ, vì anh đã nhìn quanh khi cô đang tắm, và chẳng có ai trong toàn bộ khách sạn','00:02:28.920','00:02:35.560','nightmare-tales-4'),
	('It would appear that they\'re completely alone','Có vẻ như họ hoàn toàn cô độc','00:02:36.120','00:02:39.620','nightmare-tales-4'),
	('They went to bed and were surprised at how comfortable the bed actually was','Họ lên giường và ngạc nhiên khi thấy chiếc giường thoải mái đến thế','00:02:42.040','00:02:45.920','nightmare-tales-4'),
	('They both drifted off to sleep quickly','Cả hai nhanh chóng chìm vào giấc ngủ','00:02:46.660','00:02:48.620','nightmare-tales-4'),
	('That was until the woman heard a noise','Cho đến khi người phụ nữ nghe thấy một tiếng động','00:02:49.280','00:02:51.980','nightmare-tales-4'),
	('Someone\'s trying to get in, she thought','Ai đó đang cố vào đây, cô nghĩ','00:02:52.880','00:02:54.800','nightmare-tales-4'),
	('She called out to her partner','Cô gọi với bạn đời của mình','00:02:55.080','00:02:56.620','nightmare-tales-4'),
	('Dave, someone\'s coming, she said','Dave, có ai đó đang tới, cô nói','00:02:57.180','00:02:59.260','nightmare-tales-4'),
	('Don\'t be ridiculous, he said, it\'s probably the wind','Đừng ngớ ngẩn, anh nói, chắc là gió thôi','00:02:59.980','00:03:03.140','nightmare-tales-4'),
	('Look, we\'re completely safe','Nhìn xem, chúng ta hoàn toàn an toàn','00:03:03.840','00:03:05.760','nightmare-tales-4'),
	('The door is locked and bolted and the windows have bars, right?','Cửa đã khóa và cài chốt, cửa sổ cũng có thanh chắn, đúng không?','00:03:06.220','00:03:10.860','nightmare-tales-4'),
	('No one can get in here','Không ai có thể vào đây','00:03:11.560','00:03:12.880','nightmare-tales-4'),
	('This made her feel mildly better','Điều này khiến cô cảm thấy khá hơn một chút','00:03:13.780','00:03:15.780','nightmare-tales-4'),
	('However, she still couldn\'t fully get settled, especially since what she had heard earlier had crawled back into her mind','Tuy nhiên, cô vẫn không thể hoàn toàn yên tâm, đặc biệt khi những gì cô nghe thấy trước đó đã quay trở lại trong tâm trí','00:03:16.680','00:03:24.280','nightmare-tales-4'),
	('Suddenly, she heard a noise again and she looked over the end of the bed at the fireplace','Bất ngờ, cô lại nghe thấy tiếng động và nhìn qua cuối giường về phía lò sưởi','00:03:24.880','00:03:30.060','nightmare-tales-4'),
	('The fireplace, she thought, they\'re going to come down the chimney','Lò sưởi, cô nghĩ, họ sẽ chui xuống qua ống khói','00:03:31.120','00:03:34.340','nightmare-tales-4'),
	('She got out of bed and looked up the chimney','Cô bước ra khỏi giường và nhìn lên ống khói','00:03:35.660','00:03:37.540','nightmare-tales-4'),
	('Dave, wake up, she said','Dave, dậy đi, cô nói','00:03:38.420','00:03:40.480','nightmare-tales-4'),
	('The chimney\'s not secure','Ống khói không an toàn','00:03:41.020','00:03:42.560','nightmare-tales-4'),
	('They might come down here','Họ có thể xuống đây','00:03:43.100','00:03:44.400','nightmare-tales-4'),
	('Dave had woken up','Dave đã tỉnh dậy','00:03:45.540','00:03:47.160','nightmare-tales-4'),
	('In fact, he\'d been awake the entire time, waiting to open the door','Thực ra, anh đã thức suốt thời gian qua, chờ mở cửa','00:03:47.520','00:03:52.960','nightmare-tales-4'),
	('He let in two men in dark robes','Anh cho hai người đàn ông trong áo choàng đen vào','00:03:54.320','00:03:56.340','nightmare-tales-4'),
	('They entered the room and stared directly at the girl','Họ bước vào phòng và nhìn chằm chằm vào cô gái','00:03:56.840','00:03:59.740','nightmare-tales-4'),
	('The girl knew they had come for her','Cô gái biết rằng họ đến vì cô','00:04:00.940','00:04:02.880','nightmare-tales-4'),
	('She tried to scream, but couldn\'t','Cô cố hét lên, nhưng không thể','00:04:03.520','00:04:05.280','nightmare-tales-4'),
	('What the hell is going on, she thought','Chuyện quái gì đang xảy ra thế này, cô nghĩ','00:04:05.880','00:04:07.620','nightmare-tales-4'),
	('Dave, what have you done?','Dave, anh đã làm gì?','00:04:07.940','00:04:09.660','nightmare-tales-4'),
	('Why?','Tại sao?','00:04:10.240','00:04:10.540','nightmare-tales-4'),
	('It appeared that he didn\'t care at all','Có vẻ như anh ta hoàn toàn không quan tâm','00:04:12.340','00:04:15.180','nightmare-tales-4'),
	('Dave did nothing as the two cloaked figures moved closer and closer to his girl','Dave không làm gì khi hai người áo choàng tiến lại gần cô gái của anh','00:04:16.100','00:04:21.200','nightmare-tales-4'),
	('They grabbed the girl and dragged her down the hall, all into the darkness','Họ túm lấy cô gái và kéo cô xuống hành lang, vào trong bóng tối','00:04:22.340','00:04:27.960','nightmare-tales-4'),
	('As it turns out, a week earlier, Dave had incurred some massive losses at a mafia-run blackjack game','Hóa ra, một tuần trước, Dave đã thua đậm trong một trò chơi blackjack do mafia tổ chức','00:04:31.350','00:04:37.530','nightmare-tales-4'),
	('He had no way to pay his debts, so he offered up his girlfriend','Anh không có cách nào trả nợ, nên đã đề nghị bạn gái mình','00:04:38.150','00:04:41.810','nightmare-tales-4'),
	('They accepted, and then they set up a stay at the hotel to make it happen','Họ đã chấp nhận, rồi sắp xếp cho họ nghỉ tại khách sạn để thực hiện kế hoạch','00:04:43.070','00:04:48.070','nightmare-tales-4'),
	('Dave left the hotel, relieved that his debt was clear, without a hint of guilt at what he\'d just done','Dave rời khỏi khách sạn, nhẹ nhõm vì đã trả xong nợ, mà không hề cảm thấy tội lỗi về những gì vừa làm','00:04:50.240','00:04:57.620','nightmare-tales-4'),
	
	
	/* ('Nightmare Tales - Lesson 5: The Nanny','Những Câu Chuyện Ác Mộng - Bài 5: Người Giữ Trẻ','00:00:06.020','00:04:57.620','nightmare-tales-5'), */
	('A young family in midtown New York had employed a nanny to help care for their young child and she did so ever since the day he was born','Một gia đình trẻ ở trung tâm New York đã thuê một bảo mẫu để giúp chăm sóc con nhỏ của họ, và cô đã làm điều đó từ ngày cậu bé chào đời','00:00:06.020','00:00:15.760','nightmare-tales-5'),
	('The nanny would pamper him and love him as if he was her own','Người bảo mẫu luôn nuông chiều và yêu thương cậu bé như con đẻ của mình','00:00:16.780','00:00:20.740','nightmare-tales-5'),
	('He was a strange boy and over the years a fierce mean streak began to develop in him','Cậu bé là một đứa trẻ kỳ lạ và theo thời gian, một tính cách hung ác dần hình thành trong cậu','00:00:21.700','00:00:26.920','nightmare-tales-5'),
	('He often played pranks on the nanny','Cậu bé thường xuyên chơi khăm người bảo mẫu','00:00:27.540','00:00:29.360','nightmare-tales-5'),
	('Once he put a dead rat in her bed, another time he set fire to her favourite dress','Có lần cậu đặt một con chuột chết lên giường của cô, lần khác cậu đốt chiếc váy yêu thích của cô','00:00:30.000','00:00:34.780','nightmare-tales-5'),
	('He would even taint her food with ink or bleach','Cậu thậm chí còn pha mực hoặc thuốc tẩy vào thức ăn của cô','00:00:35.380','00:00:38.220','nightmare-tales-5'),
	('Regardless, the nanny saw all these things as him just being a playful child and there was nothing he could do to sway her unconditional love for him','Dù vậy, người bảo mẫu vẫn coi tất cả những điều này chỉ là trò nghịch ngợm của cậu bé, và không gì có thể làm thay đổi tình yêu vô điều kiện của cô dành cho cậu','00:00:39.220','00:00:47.920','nightmare-tales-5'),
	('The boy knew this and he loved the attention','Cậu bé biết điều này và thích được chú ý','00:00:49.560','00:00:52.420','nightmare-tales-5'),
	('However, this all changed when a new baby entered the household','Tuy nhiên, mọi thứ thay đổi khi một em bé mới chào đời trong gia đình','00:00:53.060','00:00:56.200','nightmare-tales-5'),
	('The nanny could no longer spend every waking moment with the boy and he hated that','Người bảo mẫu không còn có thể dành mọi khoảnh khắc thức dậy bên cạnh cậu bé và cậu ghét điều đó','00:00:57.140','00:01:02.280','nightmare-tales-5'),
	('The boy, wanting the nanny all to himself, took the newborn and drowned her in the bathtub in a cold and calculated way','Cậu bé, muốn chiếm hữu hoàn toàn người bảo mẫu, đã nhấn chìm em bé trong bồn tắm một cách lạnh lùng và tính toán','00:01:03.300','00:01:11.180','nightmare-tales-5'),
	('When the family found the drowned child, they were devastated','Khi gia đình phát hiện đứa bé bị đuối nước, họ vô cùng đau đớn','00:01:12.540','00:01:16.020','nightmare-tales-5'),
	('The mother, inconsolable','Người mẹ không thể nguôi ngoai','00:01:16.800','00:01:18.620','nightmare-tales-5'),
	('They couldn\'t understand how this could have happened','Họ không thể hiểu làm sao chuyện này có thể xảy ra','00:01:19.340','00:01:21.400','nightmare-tales-5'),
	('That was until the boy spoke up and said that he saw the nanny drown the child','Cho đến khi cậu bé lên tiếng và nói rằng cậu đã thấy người bảo mẫu dìm chết đứa bé','00:01:22.180','00:01:27.680','nightmare-tales-5'),
	('The nanny couldn\'t believe what she was hearing','Người bảo mẫu không thể tin vào những gì cô nghe thấy','00:01:28.500','00:01:30.700','nightmare-tales-5'),
	('The parents, not suspecting their innocent child could have done this, immediately turned their grief and anger towards the nanny and sent her to her room to wait for the police to arrive','Cha mẹ cậu bé, không nghi ngờ đứa con ngây thơ của mình có thể làm chuyện này, lập tức chuyển nỗi đau buồn và tức giận về phía người bảo mẫu và nhốt cô vào phòng đợi cảnh sát đến','00:01:31.380','00:01:42.320','nightmare-tales-5'),
	('Hours later, she took her own life','Vài giờ sau, cô đã tự kết liễu cuộc đời mình','00:01:43.540','00:01:46.160','nightmare-tales-5'),
	('She was so completely heartbroken by the child\'s betrayal and loss of the infant, that she became overwhelmed with sorrow and felt the only way out was to end it all','Cô hoàn toàn tan nát vì sự phản bội của đứa trẻ và mất đi đứa bé, nỗi đau tràn ngập khiến cô cảm thấy chỉ có cách duy nhất là kết thúc tất cả','00:01:47.140','00:01:59.420','nightmare-tales-5'),
	('Decades later, the young boy had grown into a successful businessman who ran his companies with a strict policy of bullying and intimidation','Nhiều thập kỷ sau, cậu bé ngày nào đã trưởng thành thành một doanh nhân thành đạt điều hành công ty bằng chính sách nghiêm khắc về bắt nạt và đe dọa','00:02:01.640','00:02:10.020','nightmare-tales-5'),
	('He was disliked and feared by all who knew him and he couldn\'t care less','Anh ta bị tất cả những người biết đến ghét bỏ và sợ hãi, nhưng anh không mảy may quan tâm','00:02:10.980','00:02:16.440','nightmare-tales-5'),
	('He had married to a wife he rarely showed affection to and they had recently had a child together','Anh ta đã kết hôn với một người vợ mà anh hiếm khi bày tỏ tình cảm và gần đây họ vừa có một đứa con','00:02:17.360','00:02:23.960','nightmare-tales-5'),
	('Interestingly, he loved the child with all his heart','Thú vị là anh yêu thương đứa trẻ hết lòng','00:02:25.140','00:02:29.060','nightmare-tales-5'),
	('On a Friday night, a few weeks later, the police were called out to the man\'s residence to investigate a call they had received about someone screaming and being beaten','Vào một đêm thứ Sáu, vài tuần sau, cảnh sát được gọi đến nhà của người đàn ông để điều tra về cuộc gọi báo có ai đó đang la hét và bị đánh đập','00:02:31.000','00:02:40.300','nightmare-tales-5'),
	('The man looked at them as if they were idiots and told them to get off his property before he reported them to the commissioner for harassment','Người đàn ông nhìn họ như thể họ là những kẻ ngốc và bảo họ rời khỏi khu nhà của mình trước khi anh báo cáo họ với ủy viên vì tội quấy rối','00:02:41.320','00:02:47.500','nightmare-tales-5'),
	('It was then that the wife appeared at the door, her face clearly beaten and bruised','Đúng lúc đó người vợ xuất hiện ở cửa, mặt cô rõ ràng bị đánh đập và bầm tím','00:02:48.480','00:02:54.940','nightmare-tales-5'),
	('The man was shocked by this, but even more so, when his wife asked the policeman to, please, save the baby','Người đàn ông bị sốc vì điều này, nhưng còn hơn thế nữa khi người vợ cầu xin cảnh sát hãy cứu đứa bé','00:02:55.760','00:03:04.800','nightmare-tales-5'),
	('The police went straight inside to check on the infant','Cảnh sát lập tức vào bên trong kiểm tra đứa bé','00:03:07.020','00:03:09.760','nightmare-tales-5'),
	('What they saw was too horrific for words','Những gì họ nhìn thấy quá kinh hoàng để diễn tả thành lời','00:03:10.500','00:03:12.920','nightmare-tales-5'),
	('The abuse that had occurred would scar them for the rest of their careers','Những gì đã xảy ra sẽ ám ảnh họ suốt sự nghiệp còn lại','00:03:12.920','00:03:17.520','nightmare-tales-5'),
	('The man was arrested and sentenced to life imprisonment without parole, forever left to rot in a cell','Người đàn ông bị bắt và kết án tù chung thân không được ân xá, mãi mãi thối rữa trong phòng giam','00:03:20.270','00:03:28.590','nightmare-tales-5'),
	('He wouldn\'t last long though, for what happens to his kind in prison is indescribable','Anh ta không thể sống lâu được, bởi vì những gì xảy ra với loại người như anh ta trong tù thật khó diễn tả','00:03:30.310','00:03:37.270','nightmare-tales-5'),
	('Not surprisingly, no one cared about what happened to the man and least of all, his wife','Không có gì ngạc nhiên khi không ai quan tâm đến những gì đã xảy ra với người đàn ông, và ít nhất là vợ của anh ta','00:03:40.150','00:03:47.710','nightmare-tales-5'),
	
	
	/* ('Nightmare Tales - Lesson 6: The diner','Những Câu Chuyện Ác Mộng - Bài 6: Quán ăn','00:00:06.020','00:04:57.620','nightmare-tales-6'),  */
	('On a cold dark night, around two in the morning, a young man and his father sat in a remote 24-hour diner, waiting to be served','Vào một đêm lạnh lẽo và tối tăm, khoảng hai giờ sáng, một chàng trai trẻ và cha mình ngồi trong một quán ăn 24 giờ hẻo lánh, chờ được phục vụ','00:00:09.610','00:00:18.470','nightmare-tales-6'),
	('The older man, who was sadly slowly going senile, had insisted on going out for some soup','Người đàn ông lớn tuổi, người đang dần dần mất trí nhớ, đã khăng khăng muốn ra ngoài để ăn một ít súp','00:00:19.430','00:00:25.310','nightmare-tales-6'),
	('Not having the energy to argue, the son took him out, for at least this way his father would be happy, and then he could get some peace and quiet','Không còn sức để tranh cãi, người con đã dẫn ông ra ngoài, vì ít nhất theo cách này cha anh sẽ vui và anh sẽ có một chút yên bình','00:00:26.030','00:00:33.630','nightmare-tales-6'),
	('The waiter walked over, welcomed them to the diner, and then asked if they were ready to order, to which they replied they were','Người phục vụ tiến lại gần, chào đón họ đến quán và hỏi liệu họ đã sẵn sàng gọi món, và họ trả lời rằng đã sẵn sàng','00:00:34.710','00:00:41.910','nightmare-tales-6'),
	('The waiter recommended for them to try the burgers','Người phục vụ đề nghị họ thử món bánh mì kẹp','00:00:42.790','00:00:45.250','nightmare-tales-6'),
	('Best in the west, he said, with a smile that made their skin crawl','Ngon nhất miền Tây, anh ta nói, với một nụ cười khiến họ lạnh sống lưng','00:00:45.870','00:00:50.230','nightmare-tales-6'),
	('They declined and proceeded to order what they came for','Họ từ chối và gọi món mà họ đã đến để ăn','00:00:51.490','00:00:54.750','nightmare-tales-6'),
	('The old man ordered tomato soup and the son a coffee','Ông cụ gọi súp cà chua và người con gọi một ly cà phê','00:00:55.470','00:00:59.410','nightmare-tales-6'),
	('When the waiter walked away, the son asked his if he had thought the waiter looked familiar','Khi người phục vụ đi khỏi, người con hỏi cha liệu ông có thấy người phục vụ trông quen thuộc không','00:01:00.510','00:01:05.090','nightmare-tales-6'),
	('Not surprisingly, the father said he had never seen him before','Không ngạc nhiên, người cha nói rằng ông chưa bao giờ gặp anh ta trước đây','00:01:06.290','00:01:09.650','nightmare-tales-6'),
	('But why?','Nhưng tại sao?','00:01:10.390','00:01:10.950','nightmare-tales-6'),
	('he asked','ông hỏi','00:01:11.230','00:01:11.810','nightmare-tales-6'),
	('The son proceeded to tell him that he thought he looked a lot like a man he saw on the news that was wanted for murder in another state, but he could easily be mistaken','Người con tiếp tục nói rằng anh nghĩ người phục vụ trông rất giống một người mà anh thấy trên bản tin, người đang bị truy nã vì tội giết người ở một bang khác, nhưng cũng có thể anh đã nhầm','00:01:12.730','00:01:21.570','nightmare-tales-6'),
	('This made the father quite uncomfortable, so he told his son to shut up and change the subject','Điều này khiến người cha khá khó chịu, vì vậy ông bảo con im lặng và đổi chủ đề','00:01:22.850','00:01:28.510','nightmare-tales-6'),
	('Instead, the son then got up, told his father he was going to the bathroom and would be back in a minute','Thay vào đó, người con đứng dậy, nói với cha rằng mình đi vệ sinh và sẽ quay lại trong giây lát','00:01:29.490','00:01:34.970','nightmare-tales-6'),
	('The father waited and waited','Người cha chờ đợi mãi','00:01:36.550','00:01:38.930','nightmare-tales-6'),
	('Almost 15 minutes had passed and his son hadn\'t returned','Gần 15 phút đã trôi qua mà người con vẫn chưa quay lại','00:01:40.090','00:01:44.110','nightmare-tales-6'),
	('He also hadn\'t seen the waiter again','Ông cũng không thấy người phục vụ nữa','00:01:44.850','00:01:46.910','nightmare-tales-6'),
	('Where was his son?','Con trai ông đâu?','00:01:47.970','00:01:49.010','nightmare-tales-6'),
	('And where was his soup?','Và món súp của ông đâu?','00:01:49.790','00:01:50.950','nightmare-tales-6'),
	('Just as he finished asking himself this, the waiter appeared with the soup','Ngay khi ông vừa tự hỏi điều đó, người phục vụ xuất hiện với món súp','00:01:52.210','00:01:56.230','nightmare-tales-6'),
	('Well, you took your time with that, the old man said','À, cậu đã mất khá nhiều thời gian cho việc đó, ông cụ nói','00:01:58.110','00:02:00.690','nightmare-tales-6'),
	('I\'m sorry, sir, said the waiter','Xin lỗi, thưa ngài, người phục vụ nói','00:02:01.250','00:02:02.930','nightmare-tales-6'),
	('We had some issues in the kitchen','Chúng tôi gặp một số vấn đề trong bếp','00:02:03.390','00:02:04.770','nightmare-tales-6'),
	('Where\'s my son?','Con trai tôi đâu?','00:02:05.610','00:02:06.470','nightmare-tales-6'),
	('the old man asked the waiter','ông cụ hỏi người phục vụ','00:02:06.690','00:02:07.870','nightmare-tales-6'),
	('Oh, I\'m sure he\'s not far','Ồ, tôi chắc rằng cậu ấy không ở xa đâu','00:02:08.750','00:02:11.210','nightmare-tales-6'),
	('I have a feeling you\'ll be seeing him really soon','Tôi có linh cảm rằng ngài sẽ gặp cậu ấy rất sớm thôi','00:02:12.050','00:02:14.770','nightmare-tales-6'),
	('And with this, he placed the bowl down on the table with a smile that would have given anyone the creeps','Và với điều đó, anh ta đặt cái bát xuống bàn với một nụ cười có thể khiến bất cứ ai rùng mình','00:02:15.310','00:02:19.970','nightmare-tales-6'),
	('The old man turned to his soup and dipped his spoon in to take his first mouthful','Ông cụ quay sang món súp và nhúng muỗng để ăn miếng đầu tiên','00:02:20.730','00:02:25.410','nightmare-tales-6'),
	('As he lifted the spoon, something else came with it','Khi ông nâng muỗng lên, một thứ khác đi kèm theo','00:02:26.090','00:02:29.730','nightmare-tales-6'),
	('Some glasses','Một cặp kính','00:02:30.430','00:02:31.330','nightmare-tales-6'),
	('What the hell, he thought to himself','Cái quái gì thế này, ông nghĩ thầm','00:02:31.850','00:02:33.830','nightmare-tales-6'),
	('A horrible chill ran through his body when he realized whose glasses they were','Một cảm giác ớn lạnh khủng khiếp chạy dọc cơ thể ông khi nhận ra đó là kính của ai','00:02:34.610','00:02:38.270','nightmare-tales-6'),
	('His son\'s','Của con trai ông','00:02:39.170','00:02:40.450','nightmare-tales-6'),
	('The old man looked across at the waiter and was overcome with rage when he saw the waiter\'s sickly grin staring back at him','Ông cụ nhìn chằm chằm vào người phục vụ và tức giận tột độ khi thấy nụ cười bệnh hoạn của anh ta nhìn lại ông','00:02:41.230','00:02:47.990','nightmare-tales-6'),
	('He grabbed a knife, leapt out of his seat and stabbed the waiter in the chest','Ông chộp lấy một con dao, nhảy ra khỏi chỗ ngồi và đâm vào ngực người phục vụ','00:02:48.850','00:02:53.130','nightmare-tales-6'),
	('The blade went straight through his heart','Lưỡi dao đâm thẳng vào tim anh ta','00:02:53.370','00:02:55.530','nightmare-tales-6'),
	('And while bleeding profusely all over the floor, he died','Và trong khi máu tuôn xối xả trên sàn, anh ta đã chết','00:02:56.070','00:02:59.870','nightmare-tales-6'),
	('Right at this moment, the son appeared from the kitchen and screamed at his father','Ngay lúc này, người con trai xuất hiện từ nhà bếp và hét lên với cha mình','00:03:00.870','00:03:04.690','nightmare-tales-6'),
	('No, what have you done?','Không, cha đã làm gì vậy?','00:03:04.810','00:03:06.870','nightmare-tales-6'),
	('It was a prank','Đó chỉ là một trò đùa','00:03:07.250','00:03:08.250','nightmare-tales-6'),
	('We were playing a prank','Chúng ta đang bày trò đùa thôi mà','00:03:08.350','00:03:09.590','nightmare-tales-6'),
	('The old man couldn\'t believe what he was hearing','Ông cụ không thể tin vào những gì mình đang nghe','00:03:10.190','00:03:12.490','nightmare-tales-6'),
	('A prank, but he\'s a Oh my god, he thought to himself as the reality quickly set in','Một trò đùa, nhưng anh ta là... Ôi trời ơi, ông nghĩ thầm khi nhận thức nhanh chóng thấm vào','00:03:13.090','00:03:19.090','nightmare-tales-6'),
	('I\'ve killed him','Ta đã giết anh ta rồi','00:03:19.910','00:03:21.090','nightmare-tales-6'),
	('The father and son had to act quickly','Hai cha con phải hành động nhanh chóng','00:03:22.710','00:03:24.390','nightmare-tales-6'),
	('They grabbed the body and decided to stash it in the cool room to buy them some time','Họ nắm lấy thi thể và quyết định giấu vào phòng lạnh để câu giờ','00:03:25.170','00:03:28.790','nightmare-tales-6'),
	('They would then clean the floor and disappear, as if they had never been there','Sau đó họ sẽ dọn dẹp sàn nhà và biến mất, như thể chưa từng có mặt ở đó','00:03:29.610','00:03:34.170','nightmare-tales-6'),
	('Perfect, they thought','Hoàn hảo, họ nghĩ','00:03:35.070','00:03:36.090','nightmare-tales-6'),
	('There were no witnesses and no one to stop them','Không có nhân chứng và cũng không ai ngăn họ lại','00:03:36.550','00:03:39.390','nightmare-tales-6'),
	('Well, that\'s what they thought','À, đó là những gì họ nghĩ','00:03:40.670','00:03:42.390','nightmare-tales-6'),
	('Until they slid back the door to the cool room and were greeted by a sight so shocking, it made both of them wish they were dead','Cho đến khi họ kéo cánh cửa phòng lạnh và bị chào đón bởi một cảnh tượng sốc đến nỗi khiến cả hai ước rằng họ đã chết đi','00:03:42.910','00:03:49.710','nightmare-tales-6'),
	('They had disturbed the waiter\'s brother, hard at work making meat for burgers','Họ đã làm phiền anh trai của người phục vụ, đang chăm chỉ chuẩn bị thịt cho bánh mì kẹp','00:03:50.970','00:03:56.510','nightmare-tales-6'),
	('The best in the West, apparently','Rõ ràng là ngon nhất ở phía Tây','00:03:57.390','00:03:59.050','nightmare-tales-6'),
	('Not that they would ever know','Dù rằng họ sẽ không bao giờ biết được','00:04:00.010','00:04:01.550','nightmare-tales-6');