INSERT INTO ANSWERS (QUESTION_CODE,ANSWER_CODE, ANSWER_TEXT, ANSWER_TEXT_VI, IS_CORRECT,DISPLAY_ORDER,CREATED_AT,UPDATED_AT,CREATED_BY,UPDATED_BY) VALUES
    ('Q-esl-fast-beginner-1-23-001', 'A', 'Betty', 'Betty', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-001', 'B', 'Sarah', 'Sarah', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-001', 'C', 'Mary', 'Mary', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-001', 'D', 'Anna', 'Anna', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-002', 'A', 'Her mother', 'Mẹ của cô bé', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-002', 'B', 'Her baby sister', 'Em gái bé bỏng của cô bé', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-002', 'C', 'Her friend', 'Bạn của cô bé', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-002', 'D', 'Her cousin', 'Em họ của cô bé', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-003', 'A', 'She takes care of her', 'Cô bé chăm sóc em', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-003', 'B', 'She ignores her', 'Cô bé phớt lờ em', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-003', 'C', 'She leaves her alone', 'Cô bé để em một mình', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-003', 'D', 'She teaches her mother', 'Cô bé dạy mẹ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-004', 'A', 'Yes, she does', 'Có', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-004', 'B', 'No, she does not', 'Không', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-004', 'C', 'Only sometimes', 'Chỉ đôi khi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-004', 'D', 'Nobody knows', 'Không ai biết', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-005', 'A', 'Her clothes', 'Quần áo của em', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-005', 'B', 'Her diaper', 'Tã của em', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-005', 'C', 'Her shoes', 'Giày của em', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-005', 'D', 'Her hat', 'Mũ của em', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-006', 'A', 'She feeds her', 'Cô bé cho em ăn', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-006', 'B', 'She goes outside', 'Cô bé đi ra ngoài', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-006', 'C', 'She goes to school', 'Cô bé đi học', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-006', 'D', 'She plays basketball', 'Cô bé chơi bóng rổ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-007', 'A', 'She feeds her', 'Cô bé cho em ăn', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-007', 'B', 'She gives her a toy', 'Cô bé đưa đồ chơi cho em', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-007', 'C', 'She gives her a book', 'Cô bé đưa sách cho em', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-007', 'D', 'She gives her a ball', 'Cô bé đưa bóng cho em', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-008', 'A', 'How to sleep', 'Cách ngủ', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-008', 'B', 'How to walk', 'Cách đi bộ', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-008', 'C', 'How to swim', 'Cách bơi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-008', 'D', 'How to run', 'Cách chạy', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-009', 'A', 'How to eat', 'Cách ăn', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-009', 'B', 'How to talk', 'Cách nói chuyện', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-009', 'C', 'How to walk', 'Cách đi', 'Y', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-009', 'D', 'How to sleep', 'Cách ngủ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-010', 'A', 'New words', 'Những từ mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-010', 'B', 'New songs', 'Những bài hát mới', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-010', 'C', 'New games', 'Những trò chơi mới', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-010', 'D', 'New dances', 'Những điệu nhảy mới', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-011', 'A', 'Yes, it is very easy', 'Có, rất dễ', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-011', 'B', 'No, it is not easy', 'Không, không dễ', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-011', 'C', 'Sometimes it is easy', 'Đôi khi dễ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-011', 'D', 'It is always fun', 'Luôn luôn vui', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-012', 'A', 'Betty', 'Betty', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-012', 'B', 'The baby', 'Em bé', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-012', 'C', 'Betty''s mother', 'Mẹ của Betty', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-012', 'D', 'Betty''s friend', 'Bạn của Betty', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-013', 'A', 'Every morning', 'Mỗi buổi sáng', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-013', 'B', 'Sometimes', 'Đôi khi', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-013', 'C', 'Every night', 'Mỗi tối', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-013', 'D', 'Never', 'Không bao giờ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-014', 'A', 'Hide and seek', 'Trốn tìm', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-014', 'B', 'Peek-a-boo', 'Ú òa', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-014', 'C', 'Basketball', 'Bóng rổ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-014', 'D', 'Football', 'Bóng đá', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-015', 'A', 'A feeding game', 'Trò chơi cho ăn', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-015', 'B', 'A hiding game with the face', 'Trò chơi che mặt', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-015', 'C', 'A walking game', 'Trò chơi tập đi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-015', 'D', 'A singing game', 'Trò chơi hát', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-016', 'A', 'Her ears', 'Tai của cô bé', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-016', 'B', 'Her mouth', 'Miệng của cô bé', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-016', 'C', 'Her eyes', 'Mắt của cô bé', 'Y', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-016', 'D', 'Her nose', 'Mũi của cô bé', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-017', 'A', 'She opens her eyes', 'Cô bé mở mắt', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-017', 'B', 'She closes the door', 'Cô bé đóng cửa', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-017', 'C', 'She feeds the baby', 'Cô bé cho em ăn', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-017', 'D', 'She goes outside', 'Cô bé đi ra ngoài', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-018', 'A', 'The baby cries', 'Em bé khóc', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-018', 'B', 'The baby laughs', 'Em bé cười', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-018', 'C', 'The baby sleeps', 'Em bé ngủ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-018', 'D', 'The baby runs', 'Em bé chạy', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-019', 'A', 'Yes, she does', 'Có', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-019', 'B', 'No, she does not', 'Không', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-019', 'C', 'Only at night', 'Chỉ vào ban đêm', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-019', 'D', 'Only in the morning', 'Chỉ vào buổi sáng', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-020', 'A', 'The baby laughs', 'Em bé cười', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-020', 'B', 'The baby cries', 'Em bé khóc', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-020', 'C', 'The baby sleeps', 'Em bé ngủ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-020', 'D', 'The baby walks away', 'Em bé đi chỗ khác', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-021', 'A', 'A caring sister', 'Một người chị biết quan tâm', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-021', 'B', 'A careless sister', 'Một người chị bất cẩn', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-021', 'C', 'A busy sister', 'Một người chị bận rộn', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-021', 'D', 'A strict sister', 'Một người chị nghiêm khắc', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-022', 'A', 'She takes care of the baby', 'Cô bé chăm sóc em bé', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-022', 'B', 'She sends the baby away', 'Cô bé đuổi em đi', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-022', 'C', 'She ignores the baby', 'Cô bé phớt lờ em', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-022', 'D', 'She asks the baby to leave', 'Cô bé bảo em rời đi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-023', 'A', 'One thing', 'Một điều', 'N', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-023', 'B', 'Two things', 'Hai điều', 'Y', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-023', 'C', 'Three things', 'Ba điều', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-023', 'D', 'Four things', 'Bốn điều', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-024', 'A', 'She changes it', 'Cô bé thay tã', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-024', 'B', 'She throws it at the baby', 'Cô bé ném tã vào em', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-024', 'C', 'She hides it', 'Cô bé giấu tã', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-024', 'D', 'She washes it', 'Cô bé giặt tã', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-025', 'A', 'She feeds her', 'Cô bé cho em ăn', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-025', 'B', 'She puts her to bed', 'Cô bé cho em đi ngủ', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-025', 'C', 'She takes her outside', 'Cô bé đưa em ra ngoài', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-025', 'D', 'She teaches her to walk', 'Cô bé dạy em đi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-026', 'A', 'Walking', 'Đi bộ', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-026', 'B', 'Swimming', 'Bơi', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-026', 'C', 'Running', 'Chạy', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-026', 'D', 'Cycling', 'Đạp xe', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-027', 'A', 'New words', 'Những từ mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-027', 'B', 'Numbers', 'Các con số', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-027', 'C', 'Songs', 'Các bài hát', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-027', 'D', 'Letters', 'Các chữ cái', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-028', 'A', 'She plays peek-a-boo with her', 'Cô bé chơi ú òa với em', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-028', 'B', 'She leaves the room', 'Cô bé rời khỏi phòng', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-028', 'C', 'She starts crying', 'Cô bé bắt đầu khóc', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-028', 'D', 'She goes to sleep', 'Cô bé đi ngủ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-029', 'A', 'Because Betty plays peek-a-boo', 'Vì Betty chơi trò ú òa', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-029', 'B', 'Because Betty feeds her', 'Vì Betty cho em ăn', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-029', 'C', 'Because Betty changes her diaper', 'Vì Betty thay tã cho em', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-029', 'D', 'Because Betty teaches her to walk', 'Vì Betty dạy em tập đi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-030', 'A', 'Betty takes care of and plays with her baby sister', 'Betty chăm sóc và chơi với em gái bé bỏng', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-030', 'B', 'Betty goes to school with her sister', 'Betty đi học cùng em gái', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-030', 'C', 'Betty teaches her sister to play basketball', 'Betty dạy em gái chơi bóng rổ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-23-030', 'D', 'Betty is afraid of her baby sister', 'Betty sợ em gái bé bỏng', 'N', 4, NULL, NULL, NULL, NULL);
	/* (UUID(),'esl-fast-beginner-1-24','Sometimes You Lose','Đôi khi bạn thua','BEGINNER_01_ESL_FAST_CHILDREN_024.mp3',NULL,'00:00:00.000','00:00:39.000','esl-fast-children-1','YES',24) */
	('Q-esl-fast-beginner-1-24-001','A','They won','Họ đã thắng','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-001','B','They lost','Họ đã thua','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-001','C','They canceled the game','Họ đã hủy trận đấu','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-001','D','They played another team','Họ đã đấu với một đội khác','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-002','A','Happy','Vui vẻ','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-002','B','Excited','Hào hứng','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-002','C','Upset','Buồn và thất vọng','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-002','D','Surprised','Ngạc nhiên','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-003','A','Happily','Vui vẻ','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-003','B','Sadly','Buồn bã','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-003','C','Quickly','Nhanh chóng','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-003','D','Angrily','Tức giận','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-004','A','On the bed','Trên giường','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-004','B','On the floor','Trên sàn nhà','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-004','C','On the couch','Trên ghế sofa','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-004','D','At the table','Ở bàn','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-005','A','Laughing','Cười','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-005','B','Crying','Khóc','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-005','C','Sleeping','Ngủ','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-005','D','Eating','Ăn','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-006','A','Her friend','Bạn của cô bé','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-006','B','Her coach','Huấn luyện viên của cô bé','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-006','C','Her mom','Mẹ của cô bé','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-006','D','Her sister','Chị/em gái của cô bé','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-007','A','She gives Sarah a hug','Mẹ ôm Sarah','Y',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-007','B','She leaves the house','Mẹ rời khỏi nhà','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-007','C','She calls Sarah''s coach','Mẹ gọi cho huấn luyện viên của Sarah','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-007','D','She gives Sarah a ball','Mẹ đưa cho Sarah một quả bóng','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-008','A','A cake','Một chiếc bánh ngọt','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-008','B','Some bread','Một ít bánh mì','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-008','C','Sarah''s favorite cookies','Bánh quy yêu thích của Sarah','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-008','D','A pizza','Một chiếc pizza','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-009','A','Her mom''s','Của mẹ cô bé','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-009','B','Sarah''s','Của Sarah','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-009','C','Her sister''s','Của chị/em gái cô bé','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-009','D','Her coach''s','Của huấn luyện viên cô bé','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-010','A','The basketball game','Trận đấu bóng rổ','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-010','B','Her mom''s hug','Cái ôm của mẹ','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-010','C','The warm cookies','Những chiếc bánh quy ấm áp','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-010','D','A basketball','Một quả bóng rổ','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-011','A','Her smile','Nụ cười của cô bé','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-011','B','Her tears','Những giọt nước mắt của cô bé','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-011','C','Her cookies','Những chiếc bánh quy của cô bé','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-011','D','Her clothes','Quần áo của cô bé','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-012','A','You always win','Bạn luôn luôn thắng','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-012','B','You should never lose','Bạn không bao giờ nên thua','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-012','C','Sometimes you win and sometimes you lose','Đôi khi bạn thắng và đôi khi bạn thua','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-012','D','Winning is the only important thing','Chiến thắng là điều duy nhất quan trọng','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-013','A','Very happy','Rất vui','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-013','B','Sad or unhappy','Buồn hoặc không vui','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-013','C','Very tired','Rất mệt','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-013','D','Very hungry','Rất đói','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-014','A','In a sad way','Một cách buồn bã','Y',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-014','B','In a fast way','Một cách nhanh chóng','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-014','C','In a happy way','Một cách vui vẻ','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-014','D','In a quiet way','Một cách yên lặng','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-015','A','A kiss','Một nụ hôn','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-015','B','A warm embrace','Một cái ôm ấm áp','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-015','C','A smile','Một nụ cười','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-015','D','A gift','Một món quà','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-016','A','Drops of water from the eyes','Những giọt nước mắt','Y',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-016','B','Drops of rain','Những giọt mưa','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-016','C','Drops of sweat','Những giọt mồ hôi','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-016','D','Drops of milk','Những giọt sữa','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-017','A','Her team lost the game','Đội của cô bé đã thua trận đấu','Y',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-017','B','She lost her cookies','Cô bé làm mất bánh quy','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-017','C','Her mom was angry','Mẹ của cô bé tức giận','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-017','D','She hurt her leg','Cô bé bị đau chân','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-018','A','She feels sadder','Cô bé cảm thấy buồn hơn','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-018','B','She feels happier','Cô bé cảm thấy vui hơn','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-018','C','She feels angry','Cô bé cảm thấy tức giận','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-018','D','She feels tired','Cô bé cảm thấy mệt','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-019','A','She cries again','Cô bé lại khóc','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-019','B','She wipes her tears away','Cô bé lau nước mắt','Y',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-019','C','She goes back to the game','Cô bé quay lại trận đấu','N',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-019','D','She goes to sleep','Cô bé đi ngủ','N',4,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-020','A','You should always win','Bạn luôn luôn phải thắng','N',1,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-020','B','You should never play sports','Bạn không bao giờ nên chơi thể thao','N',2,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-020','C','Sometimes you win and sometimes you lose','Đôi khi bạn thắng và đôi khi bạn thua','Y',3,NULL,NULL,NULL,NULL),
    ('Q-esl-fast-beginner-1-24-020','D','Losing means you should quit','Thua nghĩa là bạn nên bỏ cuộc','N',4,NULL,NULL,NULL,NULL),
	
	/* (UUID(),'esl-fast-beginner-1-25','A New Home','Ngôi nhà mới','BEGINNER_01_ESL_FAST_CHILDREN_025.mp3',NULL,'00:00:00.000','00:00:30.000','esl-fast-children-1','YES',25) */
    ('Q-esl-fast-beginner-1-25-001', 'A', 'A new city', 'Một thành phố mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-001', 'B', 'A new country', 'Một đất nước mới', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-001', 'C', 'A new school', 'Một ngôi trường mới', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-001', 'D', 'A small village', 'Một ngôi làng nhỏ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-002', 'A', 'A busy city', 'Một thành phố nhộn nhịp', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-002', 'B', 'A quiet farm', 'Một trang trại yên tĩnh', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-002', 'C', 'A small village', 'Một ngôi làng nhỏ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-002', 'D', 'A beach town', 'Một thị trấn ven biển', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-003', 'A', 'Buildings', 'Các tòa nhà', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-003', 'B', 'Trees', 'Cây cối', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-003', 'C', 'Houses', 'Những ngôi nhà', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-003', 'D', 'Parks', 'Công viên', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-004', 'A', 'Walking', 'Đi bộ', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-004', 'B', 'Running', 'Chạy', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-004', 'C', 'Driving', 'Lái xe', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-004', 'D', 'Sleeping', 'Ngủ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-005', 'A', 'Taxis', 'Xe taxi', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-005', 'B', 'Buses', 'Xe buýt', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-005', 'C', 'Trucks', 'Xe tải', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-005', 'D', 'Bikes', 'Xe đạp', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-006', 'A', 'Lonely', 'Cô đơn', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-006', 'B', 'Happy', 'Vui vẻ', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-006', 'C', 'Angry', 'Tức giận', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-006', 'D', 'Excited', 'Phấn khích', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-007', 'A', 'He is new there', 'Cậu bé là người mới ở đó', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-007', 'B', 'He has many friends', 'Cậu bé có nhiều bạn', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-007', 'C', 'He likes the city', 'Cậu bé thích thành phố', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-007', 'D', 'He knows everyone', 'Cậu bé biết mọi người', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-008', 'A', 'They act differently', 'Họ cư xử khác', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-008', 'B', 'They act the same', 'Họ cư xử giống nhau', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-008', 'C', 'They are angry', 'Họ tức giận', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-008', 'D', 'They are sleeping', 'Họ đang ngủ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-009', 'A', 'His new school', 'Ngôi trường mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-009', 'B', 'A park', 'Một công viên', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-009', 'C', 'A restaurant', 'Một nhà hàng', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-009', 'D', 'A store', 'Một cửa hàng', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-010', 'A', 'A friendly-looking person', 'Một người trông thân thiện', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-010', 'B', 'A teacher', 'Một giáo viên', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-010', 'C', 'A taxi driver', 'Một tài xế taxi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-010', 'D', 'A student sleeping', 'Một học sinh đang ngủ', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-011', 'A', 'Friendly', 'Thân thiện', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-011', 'B', 'Angry', 'Tức giận', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-011', 'C', 'Sad', 'Buồn', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-011', 'D', 'Unhappy', 'Không vui', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-012', 'A', 'A friendly-looking person', 'Một người trông thân thiện', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-012', 'B', 'A taxi driver', 'Một tài xế taxi', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-012', 'C', 'A shopkeeper', 'Một chủ cửa hàng', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-012', 'D', 'A teacher', 'Một giáo viên', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-013', 'A', 'To show him around', 'Dẫn cậu bé đi tham quan', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-013', 'B', 'To take him home', 'Đưa cậu bé về nhà', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-013', 'C', 'To buy him food', 'Mua đồ ăn cho cậu bé', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-013', 'D', 'To drive him to school', 'Chở cậu bé đến trường', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-014', 'A', 'No, he is new there', 'Không, cậu bé mới đến đó', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-014', 'B', 'Yes, very well', 'Có, rất rõ', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-014', 'C', 'Yes, he grew up there', 'Có, cậu bé lớn lên ở đó', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-014', 'D', 'Yes, he owns the city', 'Có, cậu bé sở hữu thành phố', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-015', 'A', 'Yes', 'Có', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-015', 'B', 'No', 'Không', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-015', 'C', 'Only at night', 'Chỉ vào ban đêm', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-015', 'D', 'Only at school', 'Chỉ ở trường', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-016', 'A', 'People act differently', 'Mọi người cư xử khác', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-016', 'B', 'There are no buildings', 'Không có tòa nhà nào', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-016', 'C', 'There are no people', 'Không có người nào', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-016', 'D', 'There are no taxis', 'Không có taxi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-017', 'A', 'Many buildings', 'Nhiều tòa nhà', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-017', 'B', 'Many farms', 'Nhiều trang trại', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-017', 'C', 'Many beaches', 'Nhiều bãi biển', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-017', 'D', 'Many mountains', 'Nhiều ngọn núi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-018', 'A', 'They act differently', 'Họ cư xử khác', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-018', 'B', 'They are all friendly', 'Tất cả họ đều thân thiện', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-018', 'C', 'They are all students', 'Tất cả họ đều là học sinh', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-018', 'D', 'They are all teachers', 'Tất cả họ đều là giáo viên', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-019', 'A', 'In the city', 'Trong thành phố', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-019', 'B', 'At home', 'Ở nhà', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-019', 'C', 'At the beach', 'Ở bãi biển', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-019', 'D', 'On a farm', 'Ở trang trại', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-020', 'A', 'Buildings, people, and taxis', 'Tòa nhà, người và taxi', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-020', 'B', 'Trees and farms', 'Cây cối và trang trại', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-020', 'C', 'Animals and birds', 'Động vật và chim', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-020', 'D', 'Rivers and mountains', 'Sông và núi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-021', 'A', 'He looks for someone to talk to', 'Cậu bé tìm người để nói chuyện', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-021', 'B', 'He goes home', 'Cậu bé về nhà', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-021', 'C', 'He takes a taxi', 'Cậu bé đi taxi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-021', 'D', 'He goes shopping', 'Cậu bé đi mua sắm', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-022', 'A', 'Yes', 'Có', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-022', 'B', 'No', 'Không', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-022', 'C', 'Only at home', 'Chỉ ở nhà', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-022', 'D', 'Only on the street', 'Chỉ trên đường', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-023', 'A', 'Friendly', 'Thân thiện', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-023', 'B', 'Angry', 'Tức giận', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-023', 'C', 'Sad', 'Buồn', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-023', 'D', 'Scared', 'Sợ hãi', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-024', 'A', 'Finding his way around', 'Tìm hiểu đường đi và xung quanh', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-024', 'B', 'Buying a new house', 'Mua một ngôi nhà mới', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-024', 'C', 'Finding a taxi', 'Tìm một chiếc taxi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-024', 'D', 'Finding food', 'Tìm đồ ăn', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-025', 'A', 'To take someone around a place', 'Dẫn ai đó đi tham quan một nơi', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-025', 'B', 'To take someone home', 'Đưa ai đó về nhà', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-025', 'C', 'To buy something', 'Mua thứ gì đó', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-025', 'D', 'To call someone', 'Gọi điện cho ai đó', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-026', 'A', 'He needs help in the new place', 'Cậu bé cần giúp đỡ ở nơi mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-026', 'B', 'He wants to buy a taxi', 'Cậu bé muốn mua một chiếc taxi', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-026', 'C', 'He wants to go home', 'Cậu bé muốn về nhà', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-026', 'D', 'He wants to leave school', 'Cậu bé muốn rời trường', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-027', 'A', 'Moving to a new city', 'Chuyển đến một thành phố mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-027', 'B', 'Starting a new job', 'Bắt đầu một công việc mới', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-027', 'C', 'Going on vacation', 'Đi nghỉ mát', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-027', 'D', 'Buying a new car', 'Mua một chiếc xe mới', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-028', 'A', 'He feels lonely', 'Cậu bé cảm thấy cô đơn', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-028', 'B', 'He buys a taxi', 'Cậu bé mua một chiếc taxi', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-028', 'C', 'He meets his old friends', 'Cậu bé gặp những người bạn cũ', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-028', 'D', 'He goes to the beach', 'Cậu bé đi biển', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-029', 'A', 'He asks someone to show him around', 'Cậu bé nhờ một người dẫn mình đi tham quan', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-029', 'B', 'He goes back home', 'Cậu bé trở về nhà', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-029', 'C', 'He takes a taxi', 'Cậu bé đi taxi', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-029', 'D', 'He leaves the city', 'Cậu bé rời khỏi thành phố', 'N', 4, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-030', 'A', 'A boy adjusts to life in a new city', 'Một cậu bé thích nghi với cuộc sống ở thành phố mới', 'Y', 1, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-030', 'B', 'A boy wins a competition', 'Một cậu bé thắng một cuộc thi', 'N', 2, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-030', 'C', 'A boy goes on a vacation', 'Một cậu bé đi nghỉ mát', 'N', 3, NULL, NULL, NULL, NULL),
    ('Q-esl-fast-beginner-1-25-030', 'D', 'A boy buys a new house', 'Một cậu bé mua một ngôi nhà mới', 'N', 4, NULL, NULL, NULL, NULL);