-- Child: 1.8. Sắp xếp các số
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_001', 'Cho các số 4, 1, 7, 3, 5. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_002', 'Cho các số 9, 2, 6, 4, 1. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_003', 'Cho các số 8, 3, 5, 1, 6. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_004', 'Cho các số 2, 9, 5, 7, 3. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_005', 'Cho các số 6, 2, 9, 4, 1. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_006', 'Cho các số 5, 8, 2, 7, 3. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_007', 'Cho các số 1, 6, 4, 9, 2. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_008', 'Cho các số 7, 3, 9, 1, 5. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_009', 'Cho các số 3, 8, 1, 6, 4. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_010', 'Cho các số 4, 9, 2, 6, 8. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_011', 'Cho các số 12, 5, 9, 2, 15, 7. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_012', 'Cho các số 8, 17, 4, 13, 6, 10. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_013', 'Cho các số 14, 3, 11, 7, 19, 5. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_014', 'Cho các số 6, 18, 9, 14, 2, 11. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_015', 'Cho các số 16, 4, 12, 8, 20, 5. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_016', 'Cho các số 7, 15, 3, 19, 11, 5. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_017', 'Cho các số 10, 2, 18, 6, 14, 4. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_018', 'Cho các số 13, 5, 20, 8, 16, 3. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_019', 'Cho các số 9, 17, 4, 12, 1, 15. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_020', 'Cho các số 19, 6, 14, 2, 11, 8. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_021', 'Cho các số 24, 7, 15, 3, 19, 11, 28. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_022', 'Cho các số 18, 30, 6, 25, 12, 21, 9. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_023', 'Cho các số 13, 27, 5, 20, 9, 16, 2. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_024', 'Cho các số 31, 8, 22, 14, 29, 5, 17. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_025', 'Cho các số 4, 26, 12, 35, 18, 7, 21. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_026', 'Cho các số 23, 9, 32, 15, 28, 6, 19. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_027', 'Cho các số 17, 3, 29, 11, 24, 8, 20. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_028', 'Cho các số 36, 14, 27, 5, 19, 31, 10. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_029', 'Cho các số 8, 33, 16, 25, 4, 21, 12. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_030', 'Cho các số 30, 7, 24, 13, 35, 18, 9. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_031', 'Cho các số 42, 15, 28, 6, 35, 19, 47, 11. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_032', 'Cho các số 38, 7, 45, 22, 14, 31, 9, 50. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_033', 'Cho các số 18, 39, 5, 27, 44, 12, 33, 21. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_034', 'Cho các số 49, 16, 32, 8, 41, 25, 13, 37. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_035', 'Cho các số 9, 46, 23, 35, 17, 50, 4, 29. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_036', 'Cho các số 34, 12, 48, 26, 7, 39, 21, 45. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_037', 'Cho các số 11, 43, 20, 5, 37, 28, 16, 49. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_038', 'Cho các số 47, 19, 36, 8, 24, 42, 15, 30. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_039', 'Cho các số 6, 29, 45, 18, 34, 11, 50, 22. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_040', 'Cho các số 40, 13, 27, 5, 48, 32, 17, 44. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL);

-- Child: 1.9. Tìm số ở giữa
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_001', 'Hãy liệt kê tất cả các số nằm giữa 3 và 7, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_002', 'Có bao nhiêu số tự nhiên nằm giữa 4 và 9?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_003', 'Hãy liệt kê tất cả các số chẵn nằm giữa 3 và 11, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_004', 'Có bao nhiêu số chẵn nằm giữa 2 và 10?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_005', 'Hãy liệt kê tất cả các số lẻ nằm giữa 4 và 12, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_006', 'Có bao nhiêu số lẻ nằm giữa 3 và 13?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_007', 'Hãy liệt kê tất cả các số nằm giữa 8 và 14, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_008', 'Có bao nhiêu số tự nhiên nằm giữa 5 và 11?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_009', 'Hãy liệt kê tất cả các số chẵn nằm giữa 6 và 16, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_010', 'Có bao nhiêu số chẵn nằm giữa 7 và 17?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_011', 'Hãy liệt kê tất cả các số lẻ nằm giữa 8 và 20, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_012', 'Có bao nhiêu số lẻ nằm giữa 9 và 23?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_013', 'Hãy liệt kê tất cả các số nằm giữa 11 và 20, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_014', 'Có bao nhiêu số tự nhiên nằm giữa 12 và 25?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_015', 'Hãy liệt kê tất cả các số chẵn nằm giữa 9 và 21, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_016', 'Có bao nhiêu số chẵn nằm giữa 10 và 26?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_017', 'Hãy liệt kê tất cả các số lẻ nằm giữa 13 và 28, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_018', 'Có bao nhiêu số lẻ nằm giữa 14 và 31?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_019', 'Hãy liệt kê tất cả các số nằm giữa 15 và 27, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_020', 'Có bao nhiêu số tự nhiên nằm giữa 16 và 30?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_021', 'Hãy liệt kê tất cả các số chẵn nằm giữa 21 và 39, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_022', 'Có bao nhiêu số chẵn nằm giữa 22 và 44?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_023', 'Hãy liệt kê tất cả các số lẻ nằm giữa 23 và 47, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_024', 'Có bao nhiêu số lẻ nằm giữa 24 và 49?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_025', 'Hãy liệt kê tất cả các số nằm giữa 25 và 40, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_026', 'Có bao nhiêu số tự nhiên nằm giữa 26 và 48?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_027', 'Hãy liệt kê tất cả các số chẵn nằm giữa 31 và 55, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_028', 'Có bao nhiêu số chẵn nằm giữa 32 và 58?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_029', 'Hãy liệt kê tất cả các số lẻ nằm giữa 33 và 59, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_030', 'Có bao nhiêu số lẻ nằm giữa 34 và 61?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_031', 'Hãy liệt kê tất cả các số nằm giữa 45 và 67, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_032', 'Có bao nhiêu số tự nhiên nằm giữa 48 và 75?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_033', 'Hãy liệt kê tất cả các số chẵn nằm giữa 51 và 79, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_034', 'Có bao nhiêu số chẵn nằm giữa 52 và 88?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_035', 'Hãy liệt kê tất cả các số lẻ nằm giữa 53 và 81, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_036', 'Có bao nhiêu số lẻ nằm giữa 54 và 89?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_037', 'Các số nằm giữa 62 và 77 gồm số chẵn và số lẻ. Đáp án nào phân loại đúng các số chẵn và số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_038', 'Các số nằm giữa 105 và 124 gồm số chẵn và số lẻ. Đáp án nào phân loại đúng các số chẵn và số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_039', 'Hãy liệt kê tất cả các số nằm giữa 73 và 96, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_040', 'Có bao nhiêu số tự nhiên nằm giữa 81 và 100?', 4, 'ACTIVE', NULL, NULL);

-- Child: 1.10. Số chẵn – số lẻ
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_001', 'Cho các số 2, 5, 8, 11, 14. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_002', 'Cho các số 3, 6, 9, 12, 15. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_003', 'Cho các số 4, 7, 10, 13, 16. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_004', 'Cho các số 1, 8, 11, 14, 17. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_005', 'Cho các số 6, 9, 12, 15, 18. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_006', 'Cho các số 2, 7, 10, 13, 16. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_007', 'Cho các số 5, 8, 11, 14, 19. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_008', 'Cho các số 4, 7, 12, 15, 18. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_009', 'Cho các số 1, 6, 9, 12, 17. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_010', 'Cho các số 3, 8, 11, 16, 19. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_011', 'Cho các số 2, 5, 8, 11, 14, 17. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_012', 'Cho các số 3, 6, 9, 12, 15, 18. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_013', 'Cho các số 4, 7, 10, 13, 16, 19. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_014', 'Cho các số 1, 6, 9, 12, 15, 20. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_015', 'Cho các số 2, 7, 10, 13, 16, 19. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_016', 'Cho các số 5, 8, 11, 14, 17, 20. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_017', 'Cho các số 4, 9, 12, 15, 18, 21. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_018', 'Cho các số 3, 8, 11, 14, 17, 22. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_019', 'Cho các số 6, 9, 12, 15, 18, 21. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_020', 'Cho các số 2, 5, 10, 13, 16, 19. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_021', 'Cho các số 7, 12, 15, 20, 23, 28, 31. Số chẵn lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_022', 'Cho các số 4, 9, 14, 17, 22, 25, 30. Số lẻ nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_023', 'Cho các số 6, 11, 18, 21, 26, 29, 34. Số chẵn nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_024', 'Cho các số 3, 8, 13, 16, 21, 24, 29. Số lẻ lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_025', 'Cho các số 5, 10, 17, 22, 27, 32, 35. Số chẵn lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_026', 'Cho các số 2, 7, 12, 19, 24, 31, 36. Số lẻ nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_027', 'Cho các số 9, 14, 17, 20, 25, 28, 33. Số chẵn nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_028', 'Cho các số 4, 11, 16, 23, 26, 31, 38. Số lẻ lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_029', 'Cho các số 8, 13, 18, 21, 26, 35, 40. Số chẵn lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_030', 'Cho các số 5, 12, 17, 22, 29, 34, 37. Số lẻ nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_031', 'Cho các số 4, 9, 12, 17, 22, 25, 30, 33. Có bao nhiêu số chẵn và bao nhiêu số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_032', 'Cho các số 6, 11, 14, 19, 24, 27, 32, 35. Số chẵn lớn nhất và số lẻ nhỏ nhất lần lượt là những số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_033', 'Cho các số 3, 8, 15, 18, 21, 26, 31, 34. Có bao nhiêu số chẵn và số chẵn lớn nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_034', 'Cho các số 5, 10, 13, 16, 21, 24, 29, 32. Có bao nhiêu số lẻ và số lẻ lớn nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_035', 'Cho các số 2, 7, 12, 17, 22, 27, 32, 37. Số chẵn nhỏ nhất và số lẻ lớn nhất lần lượt là những số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_036', 'Cho các số 4, 9, 14, 19, 24, 29, 34, 39. Có bao nhiêu số chẵn và bao nhiêu số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_037', 'Cho các số 8, 11, 16, 21, 26, 31, 36, 41. Số lẻ nhỏ nhất và số chẵn lớn nhất lần lượt là những số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_038', 'Cho các số 3, 6, 13, 18, 25, 28, 35, 40. Có bao nhiêu số chẵn và số lẻ lớn nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_039', 'Cho các số 7, 12, 15, 20, 23, 28, 31, 36. Có bao nhiêu số lẻ và số chẵn nhỏ nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_040', 'Cho các số 5, 10, 17, 22, 27, 32, 35, 40. Có bao nhiêu số chẵn và số lẻ nhỏ nhất là số nào?', 4, 'ACTIVE', NULL, NULL);

-- Child: 2.1. Dãy số tăng đều
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_001', '2, 3, 4, 5, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_002', '5, 6, 7, 8, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_003', '1, 2, 3, 4, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_004', '6, 7, 8, 9, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_005', '3, 4, 5, 6, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_006', '7, 8, 9, 10, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_007', '4, 5, 6, 7, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_008', '8, 9, 10, 11, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_009', '10, 11, 12, 13, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_010', '11, 12, 13, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_011', '2, 4, 6, 8, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_012', '1, 3, 5, 7, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_013', '5, 7, 9, 11, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_014', '3, 6, 9, 12, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_015', '4, 7, 10, 13, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_016', '6, 8, 10, 12, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_017', '10, 13, 16, 19, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_018', '7, 10, 13, 16, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_019', '8, 10, 12, 14, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_020', '9, 12, 15, 18, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_021', '2, 5, 8, 11, 14, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_022', '3, 7, 11, 15, 19, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_023', '4, 9, 14, 19, 24, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_024', '1, 5, 9, 13, 17, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_025', '6, 11, 16, 21, 26, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_026', '5, 8, 11, 14, 17, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_027', '7, 12, 17, 22, 27, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_028', '2, 6, 10, 14, 18, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_029', '8, 13, 18, 23, 28, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_030', '4, 8, 12, 16, 20, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_031', '?, 7, 12, 17, 22, 27. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_032', '?, 8, 14, 20, 26, 32. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_033', '?, 9, 16, 23, 30, 37. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_034', '?, 10, 18, 26, 34, 42. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_035', '?, 8, 15, 22, 29, 36. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_036', '?, 11, 19, 27, 35, 43. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_037', '?, 12, 21, 30, 39, 48. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_038', '?, 15, 24, 33, 42, 51. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_039', '?, 14, 24, 34, 44, 54. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ADD_EQUAL', 'NUMBER_PATTERN_ADD_EQUAL_040', '?, 13, 22, 31, 40, 49. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL);

-- Child: 2.2. Dãy số tăng
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_001', '1, 2, 4, 7, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_002', '2, 3, 5, 8, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_003', '3, 5, 8, 12, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_004', '1, 3, 6, 10, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_005', '4, 5, 7, 10, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_006', '2, 4, 7, 11, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_007', '5, 7, 10, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_008', '1, 4, 8, 13, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_009', '3, 4, 6, 9, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_010', '2, 5, 9, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_011', '4, 6, 9, 13, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_012', '3, 6, 10, 15, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_013', '5, 8, 12, 17, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_014', '2, 5, 9, 14, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_015', '6, 8, 11, 15, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_016', '1, 4, 8, 13, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_017', '3, 5, 8, 12, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_018', '2, 6, 11, 17, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_019', '5, 9, 14, 20, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_020', '4, 7, 11, 16, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_021', '2, 4, 7, 11, 16, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_022', '3, 6, 10, 15, 21, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_023', '1, 3, 6, 10, 15, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_024', '4, 7, 11, 16, 22, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_025', '5, 8, 12, 17, 23, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_026', '2, 5, 9, 14, 20, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_027', '1, 4, 8, 13, 19, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_028', '3, 7, 12, 18, 25, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_029', '4, 6, 9, 13, 18, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_030', '2, 5, 9, 14, 20, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_031', '1, 3, 6, 10, 15, 21, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_032', '2, 5, 9, 14, 20, 27, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_033', '3, 6, 10, 15, 21, 28, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_034', '1, 4, 8, 13, 19, 26, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_035', '2, 6, 11, 17, 24, 32, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_036', '3, 7, 12, 18, 25, 33, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_037', '4, 8, 13, 19, 26, 34, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_038', '1, 5, 10, 16, 23, 31, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_039', '2, 7, 13, 20, 28, 37, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_INCREASING', 'NUMBER_PATTERN_INCREASING_040', '3, 8, 14, 21, 29, 38, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL);
	
-- Child: 2.3. Dãy số giảm đều
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_001', '10, 9, 8, 7, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_002', '15, 14, 13, 12, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_003', '20, 19, 18, 17, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_004', '9, 8, 7, 6, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_005', '18, 17, 16, 15, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_006', '14, 13, 12, 11, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_007', '12, 11, 10, 9, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_008', '19, 18, 17, 16, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_009', '17, 16, 15, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_010', '13, 12, 11, 10, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_011', '20, 18, 16, 14, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_012', '19, 17, 15, 13, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_013', '18, 15, 12, 9, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_014', '20, 17, 14, 11, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_015', '16, 14, 12, 10, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_016', '18, 16, 14, 12, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_017', '19, 16, 13, 10, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_018', '17, 14, 11, 8, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_019', '20, 16, 12, 8, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_020', '15, 12, 9, 6, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_021', '30, 28, 25, 23, 20, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_022', '25, 22, 20, 17, 15, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_023', '40, 36, 33, 29, 26, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_024', '35, 32, 28, 25, 21, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_025', '30, 27, 25, 22, 20, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_026', '28, 24, 21, 17, 14, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_027', '40, 37, 33, 30, 26, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_028', '32, 29, 25, 22, 18, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_029', '35, 31, 28, 24, 21, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_030', '50, 46, 43, 39, 36, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_031', '?, 18, 16, 14, 12, 10. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_032', '?, 25, 22, 19, 16, 13. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_033', '?, 30, 26, 22, 18, 14. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_034', '?, 28, 25, 21, 18, 14. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_035', '?, 35, 31, 28, 24, 21. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_036', '50, ?, 44, 40, 37, 33. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_037', '45, 41, ?, 34, 31, 27. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_038', '60, 56, 53, ?, 47, 44. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_039', '55, 51, 48, 44, ?, 37. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_SUB_EQUAL', 'NUMBER_PATTERN_SUB_EQUAL_040', '70, 65, ?, 56, 52, 47. Số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL);
	
-- Child: 2.4. Dãy số giảm
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_001', '20, 19, 17, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_002', '25, 23, 20, 16, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_003', '18, 17, 15, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_004', '30, 28, 27, 24, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_005', '22, 21, 18, 16, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_006', '28, 25, 23, 22, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_007', '24, 23, 21, 19, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_008', '27, 25, 24, 22, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_009', '21, 20, 17, 16, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_010', '26, 24, 22, 19, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_011', '30, 29, 27, 24, 22, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_012', '35, 33, 30, 29, 27, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_013', '28, 26, 25, 22, 20, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_014', '32, 31, 28, 26, 23, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_015', '25, 24, 22, 19, 18, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_016', '40, 37, 35, 34, 32, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_017', '27, 25, 22, 20, 19, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_018', '36, 35, 32, 31, 29, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_019', '33, 31, 30, 28, 25, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_020', '29, 26, 25, 23, 21, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_021', '35, 33, 30, 29, 27, 24, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_022', '40, 37, 35, 34, 31, 29, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_023', '32, 31, 28, 26, 25, 22, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_024', '38, 36, 35, 32, 30, 29, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_025', '30, 27, 26, 24, 21, 20, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_026', '42, 40, 38, 37, 34, 32, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_027', '34, 33, 31, 28, 27, 25, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_028', '45, 42, 41, 39, 37, 36, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_029', '37, 35, 32, 30, 29, 26, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_030', '39, 38, 35, 34, 32, 30, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_031', '45, 44, 42, 39, 37, 36, 34, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_032', '48, 46, 45, 42, 40, 39, 37, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_033', '40, 37, 36, 34, 31, 30, 28, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_034', '50, 48, 45, 44, 42, 41, 39, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_035', '44, 43, 40, 38, 37, 34, 33, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_036', '46, 44, 43, 41, 38, 37, 35, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_037', '43, 40, 38, 37, 35, 32, 31, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_038', '47, 46, 44, 41, 40, 38, 37, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_039', '41, 39, 36, 35, 33, 30, 29, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_DECREASING', 'NUMBER_PATTERN_DECREASING_040', '49, 46, 45, 43, 42, 40, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL);

-- Child: 2.5. Dãy số tăng – giảm xen kẽ
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_001', '4, 6, 5, 7, 6, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_002', '6, 9, 8, 11, 10, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_003', '8, 10, 9, 11, 10, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_004', '10, 14, 13, 17, 16, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_005', '12, 15, 13, 16, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_006', '7, 9, 8, 10, 9, 11, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_007', '9, 12, 10, 13, 11, 14, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_008', '11, 15, 14, 18, 17, 21, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_009', '13, 15, 12, 14, 11, 13, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_010', '15, 18, 17, 20, 19, 22, ?, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_011', '5, 9, 7, 11, 9, 13, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_012', '8, 11, 9, 12, 10, 13, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_013', '10, 12, 11, 13, 12, 14, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_014', '14, 18, 16, 20, 18, 22, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_015', '16, 19, 17, 20, 18, 21, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_016', '6, 11, 9, 14, 12, 17, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_017', '9, 13, 12, 16, 15, 19, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_018', '12, 15, 13, 16, 14, 17, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_019', '15, 17, 14, 16, 13, 15, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_020', '18, 22, 21, 25, 24, 28, ?, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_021', '20, 23, 21, 24, 22, 25, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_022', '22, 26, 24, 28, 26, 30, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_023', '24, 27, 26, 29, 28, 31, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_024', '26, 28, 27, 29, 28, 30, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_025', '28, 31, 29, 32, 30, 33, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_026', '30, 34, 33, 37, 36, 40, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_027', '32, 35, 33, 36, 34, 37, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_028', '34, 36, 35, 37, 36, 38, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_029', '36, 40, 38, 42, 40, 44, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_030', '38, 41, 40, 43, 42, 45, ?, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_031', '40, 42, 41, 43, 42, 44, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_032', '42, 45, 43, 46, 44, 47, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_033', '44, 46, 45, 47, 46, 48, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_034', '45, 48, 46, 49, 47, 50, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_035', '43, 45, 44, 46, 45, 47, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_036', '18, 23, 21, 26, 24, 29, 27, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_037', '20, 24, 23, 27, 26, 30, 29, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_038', '25, 28, 26, 29, 27, 30, 28, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_039', '30, 34, 32, 36, 34, 38, 36, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_ALTERNATE', 'NUMBER_PATTERN_ALTERNATE_040', '35, 38, 37, 40, 39, 42, 41, ?, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL);

-- Child: 2.7. Tìm số còn thiếu
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_001', '1, 2, ?, 4, 5, số nào thích hợp điền vào dấu ?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_002', '5, 6, 7, ?, 9, số nào thích hợp điền vào dấu ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_003', '2, 3, ?, 5, 6, số nào thích hợp điền vào dấu ?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_004', '7, ?, 9, 10, 11, số nào thích hợp điền vào dấu ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_005', '10, 11, 12, ?, 14, số nào thích hợp điền vào dấu ?', 5, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_006', '15, ?, 17, 18, 19, số nào thích hợp điền vào dấu ?', 6, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_007', '20, 21, ?, 23, 24, số nào thích hợp điền vào dấu ?', 7, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_008', '25, 26, 27, ?, 29, số nào thích hợp điền vào dấu ?', 8, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_009', '30, ?, 32, 33, 34, số nào thích hợp điền vào dấu ?', 9, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_010', '35, 36, ?, 38, 39, số nào thích hợp điền vào dấu ?', 10, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_011', '2, 4, ?, 8, 10, số nào thích hợp điền vào dấu ?', 11, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_012', '3, 5, 7, ?, 11, số nào thích hợp điền vào dấu ?', 12, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_013', '10, 12, ?, 16, 18, số nào thích hợp điền vào dấu ?', 13, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_014', '1, 3, 5, ?, 9, số nào thích hợp điền vào dấu ?', 14, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_015', '4, 6, ?, 10, 12, số nào thích hợp điền vào dấu ?', 15, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_016', '5, 8, ?, 14, 17, số nào thích hợp điền vào dấu ?', 16, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_017', '10, 13, 16, ?, 22, số nào thích hợp điền vào dấu ?', 17, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_018', '20, 24, ?, 32, 36, số nào thích hợp điền vào dấu ?', 18, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_019', '2, 5, 8, ?, 14, số nào thích hợp điền vào dấu ?', 19, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_020', '6, 10, ?, 18, 22, số nào thích hợp điền vào dấu ?', 20, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_021', '1, ?, 3, ?, 5, số nào thích hợp điền vào hai dấu ?', 21, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_022', '2, ?, 4, ?, 6, số nào thích hợp điền vào hai dấu ?', 22, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_023', '5, ?, 7, ?, 9, số nào thích hợp điền vào hai dấu ?', 23, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_024', '10, ?, 12, ?, 14, số nào thích hợp điền vào hai dấu ?', 24, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_025', '15, ?, 17, ?, 19, số nào thích hợp điền vào hai dấu ?', 25, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_026', '20, ?, 22, ?, 24, số nào thích hợp điền vào hai dấu ?', 26, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_027', '2, ?, 6, ?, 10, số nào thích hợp điền vào hai dấu ?', 27, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_028', '4, ?, 8, ?, 12, số nào thích hợp điền vào hai dấu ?', 28, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_029', '6, ?, 10, ?, 14, số nào thích hợp điền vào hai dấu ?', 29, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_030', '8, ?, 12, ?, 16, số nào thích hợp điền vào hai dấu ?', 30, 'ACTIVE', NULL, NULL),

	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_031', '30, 27, ?, 21, 18, số nào thích hợp điền vào dấu ?', 31, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_032', '25, 23, ?, 19, 17, số nào thích hợp điền vào dấu ?', 32, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_033', '40, 36, ?, 28, 24, số nào thích hợp điền vào dấu ?', 33, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_034', '35, 30, ?, 20, 15, số nào thích hợp điền vào dấu ?', 34, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_035', '20, ?, 16, ?, 12, số nào thích hợp điền vào hai dấu ?', 35, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_036', '30, ?, 24, ?, 18, số nào thích hợp điền vào hai dấu ?', 36, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_037', '3, 7, 11, ?, 19, số nào thích hợp điền vào dấu ?', 37, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_038', '50, 45, ?, 35, 30, số nào thích hợp điền vào dấu ?', 38, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_039', '5, ?, 11, ?, 17, số nào thích hợp điền vào hai dấu ?', 39, 'ACTIVE', NULL, NULL),
	('NUMBER_PATTERN_MISSING', 'NUMBER_PATTERN_MISSING_040', '40, ?, 32, ?, 24, số nào thích hợp điền vào hai dấu ?', 40, 'ACTIVE', NULL, NULL);

-- Child: 6.1. Hai bước cộng
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_001', 'Nam có 2 quả táo. Mẹ cho Nam thêm 3 quả táo, sau đó bố cho thêm 1 quả nữa. Hỏi Nam có tất cả bao nhiêu quả táo?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_002', 'Lan có 4 bông hoa. Cô cho Lan thêm 2 bông, sau đó bạn Mai cho thêm 1 bông nữa. Hỏi Lan có tất cả bao nhiêu bông hoa?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_003', 'Bình có 3 viên bi. Bố cho Bình thêm 2 viên, rồi anh cho thêm 2 viên nữa. Hỏi Bình có tất cả bao nhiêu viên bi?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_004', 'Trong bể có 5 con cá. Mẹ thả thêm 1 con cá, sau đó thả thêm 2 con nữa. Hỏi trong bể có tất cả bao nhiêu con cá?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_005', 'Mai có 3 chiếc bút. Cô giáo cho Mai thêm 2 chiếc, rồi mẹ cho thêm 3 chiếc nữa. Hỏi Mai có tất cả bao nhiêu chiếc bút?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_006', 'Trong giỏ có 2 quả cam. Mẹ đặt thêm 4 quả cam vào giỏ, sau đó đặt thêm 1 quả nữa. Hỏi trong giỏ có tất cả bao nhiêu quả cam?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_007', 'An có 5 chiếc kẹo. Bà cho An thêm 2 chiếc, rồi mẹ cho thêm 1 chiếc nữa. Hỏi An có tất cả bao nhiêu chiếc kẹo?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_008', 'Trên cành có 3 con chim. Có thêm 3 con bay đến, sau đó thêm 1 con nữa. Hỏi trên cành có tất cả bao nhiêu con chim?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_009', 'Hoa có 4 quyển truyện. Chị cho Hoa thêm 2 quyển, rồi bố cho thêm 2 quyển nữa. Hỏi Hoa có tất cả bao nhiêu quyển truyện?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_010', 'Trong hộp có 1 chiếc xe đồ chơi. Nam đặt thêm 3 chiếc vào hộp, sau đó đặt thêm 2 chiếc nữa. Hỏi trong hộp có tất cả bao nhiêu chiếc xe đồ chơi?', 1, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_011', 'Trên bàn có 5 quyển vở. Buổi sáng cô đặt thêm 3 quyển, đến chiều cô đặt thêm 2 quyển nữa. Hỏi trên bàn có tất cả bao nhiêu quyển vở?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_012', 'Một giỏ có 4 quả táo. Mẹ đặt thêm 3 quả vào giỏ, sau đó bố đặt thêm 2 quả nữa. Hỏi trong giỏ có tất cả bao nhiêu quả táo?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_013', 'Minh có 6 chiếc tem. Bạn cho Minh thêm 2 chiếc tem, sau đó cô giáo cho thêm 3 chiếc nữa. Hỏi Minh có tất cả bao nhiêu chiếc tem?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_014', 'Trong sân có 5 quả bóng. Nam mang thêm 4 quả ra sân, sau đó Minh mang thêm 2 quả nữa. Hỏi trong sân có tất cả bao nhiêu quả bóng?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_015', 'Một lớp có 7 bạn đang chơi. Có thêm 2 bạn tham gia, sau đó thêm 3 bạn nữa. Hỏi lúc này có tất cả bao nhiêu bạn đang chơi?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_016', 'Trong tủ có 3 chiếc cốc. Mẹ đặt thêm 4 chiếc vào tủ, rồi bố đặt thêm 2 chiếc nữa. Hỏi trong tủ có tất cả bao nhiêu chiếc cốc?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_017', 'Có 6 con vịt dưới ao. Có thêm 3 con bơi đến, sau đó thêm 2 con nữa. Hỏi dưới ao có tất cả bao nhiêu con vịt?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_018', 'Một hộp có 5 viên phấn. Cô giáo cho thêm 4 viên, sau đó cho thêm 3 viên nữa. Hỏi trong hộp có tất cả bao nhiêu viên phấn?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_019', 'Nam có 4 chiếc ô tô đồ chơi. Sinh nhật Nam được tặng thêm 3 chiếc, sau đó bố mua thêm 4 chiếc nữa. Hỏi Nam có tất cả bao nhiêu chiếc ô tô đồ chơi?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_020', 'Trên giá có 6 quyển sách. Mẹ đặt thêm 4 quyển sách, sau đó bố đặt thêm 3 quyển nữa. Hỏi trên giá có tất cả bao nhiêu quyển sách?', 2, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_021', 'Một cửa hàng có 6 chiếc bánh. Buổi sáng cửa hàng nhập thêm 4 chiếc bánh. Đến chiều, cửa hàng nhập thêm 3 chiếc nữa. Hỏi sau hai lần nhập, cửa hàng có tất cả bao nhiêu chiếc bánh?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_022', 'Trong vườn có 7 bông hoa. Người làm vườn trồng thêm 3 bông vào buổi sáng, sau đó trồng thêm 4 bông vào buổi chiều. Hỏi trong vườn có tất cả bao nhiêu bông hoa?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_023', 'Một hộp có 8 chiếc bút màu. Cô giáo cho thêm 3 chiếc vào hộp, sau đó bạn Lan cho thêm 2 chiếc nữa. Hỏi trong hộp có tất cả bao nhiêu chiếc bút màu?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_024', 'Có 5 con chim trên cành. Lúc đầu có thêm 4 con bay đến, sau đó thêm 5 con nữa bay đến. Hỏi trên cành lúc này có tất cả bao nhiêu con chim?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_025', 'Một thư viện có 7 quyển truyện thiếu nhi. Buổi sáng thư viện nhận thêm 3 quyển, đến chiều nhận thêm 5 quyển nữa. Hỏi thư viện có tất cả bao nhiêu quyển truyện thiếu nhi?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_026', 'Trong bể có 6 con cá vàng. Bố thả thêm 5 con cá, sau đó mẹ thả thêm 3 con nữa. Hỏi trong bể có tất cả bao nhiêu con cá vàng?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_027', 'Một lớp có 8 chiếc hộp bút màu. Cô giáo mang thêm 2 chiếc hộp đến lớp, sau đó phụ huynh tặng thêm 4 chiếc nữa. Hỏi lớp có tất cả bao nhiêu chiếc hộp bút màu?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_028', 'Nam có 7 viên bi trong túi. Anh cho Nam thêm 4 viên, sau đó bố cho thêm 3 viên nữa. Hỏi trong túi Nam có tất cả bao nhiêu viên bi?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_029', 'Một cửa hàng có 5 chiếc xe đạp. Buổi sáng cửa hàng nhận thêm 5 chiếc, đến chiều nhận thêm 4 chiếc nữa. Hỏi cửa hàng có tất cả bao nhiêu chiếc xe đạp?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_030', 'Trên sân trường có 9 bạn đang chơi. Có thêm 2 bạn đến chơi, sau đó thêm 4 bạn nữa. Hỏi trên sân trường lúc này có tất cả bao nhiêu bạn?', 3, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_031', 'Trong giỏ có 7 quả cam. Buổi sáng mẹ đặt thêm 3 quả cam vào giỏ. Sau đó, bố đặt thêm 5 quả nữa. Hỏi sau cả hai lần thêm, trong giỏ có tất cả bao nhiêu quả cam?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_032', 'Một cửa hàng có 8 chiếc bánh. Cửa hàng nhập thêm 4 chiếc vào buổi sáng. Đến chiều, cửa hàng lại nhập thêm 3 chiếc nữa. Hỏi sau hai lần nhập hàng, cửa hàng có tất cả bao nhiêu chiếc bánh?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_033', 'Trên sân có 6 quả bóng. Nam mang thêm 5 quả bóng ra sân để chơi. Một lúc sau, Minh mang thêm 4 quả nữa. Hỏi sau hai lần mang bóng ra sân, trên sân có tất cả bao nhiêu quả bóng?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_034', 'Một giá sách có 7 quyển truyện. Mẹ đặt thêm 5 quyển vào giá. Sau đó bố đặt thêm 4 quyển nữa. Hỏi sau hai lần đặt thêm, giá sách có tất cả bao nhiêu quyển truyện?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_035', 'Trong vườn có 8 con bướm. Có 3 con bay đến vào buổi sáng. Một lúc sau, có thêm 5 con nữa bay đến. Hỏi trong vườn lúc này có tất cả bao nhiêu con bướm?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_036', 'Một hộp có 6 chiếc bút. Cô giáo cho thêm 5 chiếc bút vào hộp. Sau đó cô cho thêm 4 chiếc nữa. Hỏi sau hai lần thêm bút, trong hộp có tất cả bao nhiêu chiếc bút?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_037', 'Có 9 con chim trên cành. Buổi sáng có thêm 2 con bay đến. Sau đó có thêm 5 con nữa bay đến. Hỏi sau hai lần chim bay đến, trên cành có tất cả bao nhiêu con chim?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_038', 'Một giỏ có 7 quả táo. Mẹ đặt thêm 4 quả vào giỏ. Sau đó bố đặt thêm 5 quả nữa. Hỏi sau hai lần đặt thêm, trong giỏ có tất cả bao nhiêu quả táo?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_039', 'Nam có 8 chiếc xe đồ chơi. Anh cho Nam thêm 3 chiếc. Sau đó bố cho Nam thêm 5 chiếc nữa. Hỏi sau hai lần được cho thêm, Nam có tất cả bao nhiêu chiếc xe đồ chơi?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_040', 'Trong lớp có 6 hộp bút màu. Cô giáo mang thêm 5 hộp đến lớp. Sau đó phụ huynh tặng thêm 4 hộp nữa. Hỏi sau hai lần được thêm, lớp có tất cả bao nhiêu hộp bút màu?', 4, 'ACTIVE', NULL, NULL);

-- Child: 6.2. Hai bước trừ
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_001', 'Mai có 12 quả táo. Mai cho bạn 3 quả rồi ăn 2 quả. Hỏi Mai còn lại bao nhiêu quả táo?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_002', 'Nam có 15 viên bi. Nam cho em 4 viên rồi cho bạn 3 viên. Hỏi Nam còn lại bao nhiêu viên bi?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_003', 'Trong hộp có 14 chiếc bút. Lấy ra 2 chiếc để dùng rồi lấy thêm 4 chiếc cho các bạn. Hỏi trong hộp còn bao nhiêu chiếc bút?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_004', 'Lan có 16 cái kẹo. Lan cho em 5 cái rồi ăn 2 cái. Hỏi Lan còn bao nhiêu cái kẹo?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_005', 'Một giỏ có 18 quả cam. Mẹ lấy 6 quả rồi lấy thêm 3 quả. Hỏi giỏ còn lại bao nhiêu quả cam?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_006', 'Bình có 13 chiếc ô tô đồ chơi. Bình cho em 2 chiếc rồi cất đi 5 chiếc. Hỏi Bình còn lại bao nhiêu chiếc ô tô đồ chơi?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_007', 'Có 17 con cá trong bể. Người ta bắt ra 4 con rồi bắt thêm 2 con. Hỏi trong bể còn bao nhiêu con cá?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_008', 'Một rổ có 19 quả bóng. Lấy ra 7 quả rồi lấy thêm 3 quả. Hỏi trong rổ còn bao nhiêu quả bóng?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_009', 'Hoa có 20 nhãn vở. Hoa dùng 5 nhãn rồi cho bạn 4 nhãn. Hỏi Hoa còn bao nhiêu nhãn vở?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_010', 'Một hộp có 15 chiếc bánh. Bé ăn 3 chiếc rồi cho em 5 chiếc. Hỏi hộp còn lại bao nhiêu chiếc bánh?', 1, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_011', 'Một cửa hàng có 25 quả bóng. Buổi sáng bán 7 quả, buổi chiều bán thêm 5 quả. Hỏi cửa hàng còn lại bao nhiêu quả bóng?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_012', 'Thư viện có 30 quyển truyện. Các bạn mượn 8 quyển vào buổi sáng và 6 quyển vào buổi chiều. Hỏi thư viện còn bao nhiêu quyển truyện?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_013', 'Một giỏ có 28 quả táo. Mẹ lấy 9 quả để làm bánh rồi lấy thêm 4 quả để ăn. Hỏi giỏ còn bao nhiêu quả táo?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_014', 'Lớp 1A có 32 quyển vở dự phòng. Cô giáo phát 10 quyển cho học sinh rồi phát thêm 7 quyển. Hỏi còn lại bao nhiêu quyển vở?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_015', 'Một hộp có 27 chiếc bút màu. Nam lấy 6 chiếc để vẽ rồi cho bạn 8 chiếc. Hỏi hộp còn bao nhiêu chiếc bút màu?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_016', 'Cửa hàng có 35 chiếc bánh. Buổi sáng bán 12 chiếc, buổi chiều bán 9 chiếc. Hỏi cửa hàng còn lại bao nhiêu chiếc bánh?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_017', 'Một trang trại có 40 con gà. Người ta bán 15 con rồi bán thêm 8 con. Hỏi trang trại còn bao nhiêu con gà?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_018', 'Trong kho có 38 thùng sữa. Người ta chuyển đi 9 thùng rồi chuyển tiếp 11 thùng. Hỏi kho còn lại bao nhiêu thùng sữa?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_019', 'Một lớp có 36 chiếc bút chì. Cô phát 14 chiếc cho học sinh rồi phát thêm 7 chiếc. Hỏi còn lại bao nhiêu chiếc bút chì?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_020', 'Một cửa hàng có 45 quyển vở. Ngày thứ nhất bán 13 quyển, ngày thứ hai bán 12 quyển. Hỏi cửa hàng còn bao nhiêu quyển vở?', 2, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_021', 'Một thư viện có 52 quyển sách. Buổi sáng học sinh mượn 17 quyển, buổi chiều mượn thêm 13 quyển. Hỏi thư viện còn lại bao nhiêu quyển sách?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_022', 'Một cửa hàng có 60 chiếc bút. Ngày thứ nhất bán 18 chiếc, ngày thứ hai bán 15 chiếc. Hỏi cửa hàng còn lại bao nhiêu chiếc bút?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_023', 'Một kho có 55 hộp sữa. Người ta chuyển đi 16 hộp vào buổi sáng và 19 hộp vào buổi chiều. Hỏi kho còn bao nhiêu hộp sữa?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_024', 'Một trường có 70 quả bóng. Khối Một sử dụng 24 quả, sau đó khối Hai sử dụng thêm 18 quả. Hỏi trường còn lại bao nhiêu quả bóng?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_025', 'Một trang trại có 65 con vịt. Người ta bán 27 con rồi bán thêm 16 con. Hỏi trang trại còn lại bao nhiêu con vịt?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_026', 'Một cửa hàng có 72 chiếc bánh. Buổi sáng bán 25 chiếc, buổi chiều bán 17 chiếc. Hỏi cửa hàng còn lại bao nhiêu chiếc bánh?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_027', 'Một lớp có 68 quyển truyện. Các bạn mượn 29 quyển rồi trả lại 5 quyển. Hỏi lớp còn bao nhiêu quyển truyện?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_028', 'Một kho có 80 chiếc hộp. Người ta lấy 32 chiếc để đóng hàng rồi lấy thêm 18 chiếc. Hỏi kho còn bao nhiêu chiếc hộp?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_029', 'Một cửa hàng có 75 quyển sách. Buổi sáng bán 28 quyển, buổi chiều bán 21 quyển. Hỏi cửa hàng còn bao nhiêu quyển sách?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_030', 'Một trang trại có 90 quả trứng. Người ta bán 35 quả vào buổi sáng và 24 quả vào buổi chiều. Hỏi còn lại bao nhiêu quả trứng?', 3, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_031', 'Một thư viện có 96 quyển sách. Ngày thứ nhất học sinh mượn 28 quyển, ngày thứ hai mượn thêm 37 quyển. Hỏi thư viện còn lại bao nhiêu quyển sách?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_032', 'Một cửa hàng có 100 chiếc bút. Buổi sáng bán 36 chiếc, buổi chiều bán 29 chiếc. Hỏi cửa hàng còn lại bao nhiêu chiếc bút?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_033', 'Một kho có 85 hộp bánh. Người ta chuyển đi 27 hộp, sau đó chuyển tiếp 38 hộp. Hỏi kho còn lại bao nhiêu hộp bánh?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_034', 'Một trường có 98 quyển vở. Cô giáo phát 34 quyển cho học sinh lớp 1A rồi phát thêm 27 quyển cho lớp 1B. Hỏi còn lại bao nhiêu quyển vở?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_035', 'Một cửa hàng có 87 quả bóng. Ngày thứ nhất bán 29 quả, ngày thứ hai bán thêm 36 quả. Hỏi cửa hàng còn lại bao nhiêu quả bóng?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_036', 'Một trang trại có 100 con gà. Người ta bán 38 con vào buổi sáng và 27 con vào buổi chiều. Hỏi trang trại còn lại bao nhiêu con gà?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_037', 'Một kho có 92 thùng nước. Người ta chuyển đi 35 thùng, sau đó chuyển tiếp 28 thùng. Hỏi kho còn lại bao nhiêu thùng nước?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_038', 'Một cửa hàng có 94 chiếc áo. Buổi sáng bán 37 chiếc, buổi chiều bán thêm 26 chiếc. Hỏi cửa hàng còn lại bao nhiêu chiếc áo?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_039', 'Một thư viện có 88 quyển truyện. Các bạn mượn 39 quyển vào ngày thứ nhất và 24 quyển vào ngày thứ hai. Hỏi thư viện còn lại bao nhiêu quyển truyện?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_SUB_SUB', 'MULTI_STEP_SUB_SUB_040', 'Một cửa hàng có 100 chiếc bánh. Buổi sáng bán 42 chiếc, buổi chiều bán thêm 31 chiếc. Hỏi cửa hàng còn lại bao nhiêu chiếc bánh?', 4, 'ACTIVE', NULL, NULL);