-- Child: 1.8. Sắp xếp các số
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_001', 'Cho các số 4, 1, 7, 3, 5. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_002', 'Cho các số 9, 2, 6, 4, 1. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_003', 'Cho các số 8, 3, 5, 1, 6. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_004', 'Cho các số 2, 9, 5, 7, 3. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_005', 'Cho các số 6, 2, 9, 4, 1. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_006', 'Cho các số 5, 8, 2, 7, 3. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_007', 'Cho các số 1, 6, 4, 9, 2. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_008', 'Cho các số 7, 3, 9, 1, 5. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_009', 'Cho các số 3, 8, 1, 6, 4. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_010', 'Cho các số 4, 9, 2, 6, 8. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_011', 'Cho các số 12, 5, 9, 2, 15, 7. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_012', 'Cho các số 8, 17, 4, 13, 6, 10. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_013', 'Cho các số 14, 3, 11, 7, 19, 5. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_014', 'Cho các số 6, 18, 9, 14, 2, 11. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_015', 'Cho các số 16, 4, 12, 8, 20, 5. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_016', 'Cho các số 7, 15, 3, 19, 11, 5. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_017', 'Cho các số 10, 2, 18, 6, 14, 4. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_018', 'Cho các số 13, 5, 20, 8, 16, 3. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_019', 'Cho các số 9, 17, 4, 12, 1, 15. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_020', 'Cho các số 19, 6, 14, 2, 11, 8. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_021', 'Cho các số 24, 7, 15, 3, 19, 11, 28. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_022', 'Cho các số 18, 30, 6, 25, 12, 21, 9. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_023', 'Cho các số 13, 27, 5, 20, 9, 16, 2. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_024', 'Cho các số 31, 8, 22, 14, 29, 5, 17. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_025', 'Cho các số 4, 26, 12, 35, 18, 7, 21. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_026', 'Cho các số 23, 9, 32, 15, 28, 6, 19. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_027', 'Cho các số 17, 3, 29, 11, 24, 8, 20. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_028', 'Cho các số 36, 14, 27, 5, 19, 31, 10. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_029', 'Cho các số 8, 33, 16, 25, 4, 21, 12. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_030', 'Cho các số 30, 7, 24, 13, 35, 18, 9. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_031', 'Cho các số 42, 15, 28, 6, 35, 19, 47, 11. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_032', 'Cho các số 38, 7, 45, 22, 14, 31, 9, 50. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_033', 'Cho các số 18, 39, 5, 27, 44, 12, 33, 21. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_034', 'Cho các số 49, 16, 32, 8, 41, 25, 13, 37. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_035', 'Cho các số 9, 46, 23, 35, 17, 50, 4, 29. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_036', 'Cho các số 34, 12, 48, 26, 7, 39, 21, 45. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_037', 'Cho các số 11, 43, 20, 5, 37, 28, 16, 49. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_038', 'Cho các số 47, 19, 36, 8, 24, 42, 15, 30. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_039', 'Cho các số 6, 29, 45, 18, 34, 11, 50, 22. Sắp xếp các số theo thứ tự từ bé đến lớn. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_SORT', 'NUMBER_BASIC_SORT_040', 'Cho các số 40, 13, 27, 5, 48, 32, 17, 44. Sắp xếp các số theo thứ tự từ lớn đến bé. Thứ tự nào đúng?', 4, 'ACTIVE', NULL, NULL);

-- Child: 1.9. Tìm số ở giữa
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_001', 'Hãy liệt kê tất cả các số nằm giữa 3 và 7, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_002', 'Có bao nhiêu số tự nhiên nằm giữa 4 và 9?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_003', 'Hãy liệt kê tất cả các số chẵn nằm giữa 3 và 11, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_004', 'Có bao nhiêu số chẵn nằm giữa 2 và 10?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_005', 'Hãy liệt kê tất cả các số lẻ nằm giữa 4 và 12, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_006', 'Có bao nhiêu số lẻ nằm giữa 3 và 13?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_007', 'Hãy liệt kê tất cả các số nằm giữa 8 và 14, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_008', 'Có bao nhiêu số tự nhiên nằm giữa 5 và 11?', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_009', 'Hãy liệt kê tất cả các số chẵn nằm giữa 6 và 16, theo thứ tự từ bé đến lớn.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_010', 'Có bao nhiêu số chẵn nằm giữa 7 và 17?', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_011', 'Hãy liệt kê tất cả các số lẻ nằm giữa 8 và 20, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_012', 'Có bao nhiêu số lẻ nằm giữa 9 và 23?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_013', 'Hãy liệt kê tất cả các số nằm giữa 11 và 20, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_014', 'Có bao nhiêu số tự nhiên nằm giữa 12 và 25?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_015', 'Hãy liệt kê tất cả các số chẵn nằm giữa 9 và 21, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_016', 'Có bao nhiêu số chẵn nằm giữa 10 và 26?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_017', 'Hãy liệt kê tất cả các số lẻ nằm giữa 13 và 28, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_018', 'Có bao nhiêu số lẻ nằm giữa 14 và 31?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_019', 'Hãy liệt kê tất cả các số nằm giữa 15 và 27, theo thứ tự từ bé đến lớn.', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_020', 'Có bao nhiêu số tự nhiên nằm giữa 16 và 30?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_021', 'Hãy liệt kê tất cả các số chẵn nằm giữa 21 và 39, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_022', 'Có bao nhiêu số chẵn nằm giữa 22 và 44?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_023', 'Hãy liệt kê tất cả các số lẻ nằm giữa 23 và 47, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_024', 'Có bao nhiêu số lẻ nằm giữa 24 và 49?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_025', 'Hãy liệt kê tất cả các số nằm giữa 25 và 40, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_026', 'Có bao nhiêu số tự nhiên nằm giữa 26 và 48?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_027', 'Hãy liệt kê tất cả các số chẵn nằm giữa 31 và 55, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_028', 'Có bao nhiêu số chẵn nằm giữa 32 và 58?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_029', 'Hãy liệt kê tất cả các số lẻ nằm giữa 33 và 59, theo thứ tự từ bé đến lớn.', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_030', 'Có bao nhiêu số lẻ nằm giữa 34 và 61?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_031', 'Hãy liệt kê tất cả các số nằm giữa 45 và 67, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_032', 'Có bao nhiêu số tự nhiên nằm giữa 48 và 75?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_033', 'Hãy liệt kê tất cả các số chẵn nằm giữa 51 và 79, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_034', 'Có bao nhiêu số chẵn nằm giữa 52 và 88?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_035', 'Hãy liệt kê tất cả các số lẻ nằm giữa 53 và 81, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_036', 'Có bao nhiêu số lẻ nằm giữa 54 và 89?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_037', 'Các số nằm giữa 62 và 77 gồm số chẵn và số lẻ. Đáp án nào phân loại đúng các số chẵn và số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_038', 'Các số nằm giữa 105 và 124 gồm số chẵn và số lẻ. Đáp án nào phân loại đúng các số chẵn và số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_039', 'Hãy liệt kê tất cả các số nằm giữa 73 và 96, theo thứ tự từ bé đến lớn.', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_MIDDLE', 'NUMBER_BASIC_MIDDLE_040', 'Có bao nhiêu số tự nhiên nằm giữa 81 và 100?', 4, 'ACTIVE', NULL, NULL);

-- Child: 1.10. Số chẵn – số lẻ
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_001', 'Cho các số 2, 5, 8, 11, 14. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_002', 'Cho các số 3, 6, 9, 12, 15. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_003', 'Cho các số 4, 7, 10, 13, 16. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_004', 'Cho các số 1, 8, 11, 14, 17. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_005', 'Cho các số 6, 9, 12, 15, 18. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_006', 'Cho các số 2, 7, 10, 13, 16. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_007', 'Cho các số 5, 8, 11, 14, 19. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_008', 'Cho các số 4, 7, 12, 15, 18. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_009', 'Cho các số 1, 6, 9, 12, 17. Hãy liệt kê tất cả các số chẵn trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_010', 'Cho các số 3, 8, 11, 16, 19. Hãy liệt kê tất cả các số lẻ trong các số đã cho.', 1, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_011', 'Cho các số 2, 5, 8, 11, 14, 17. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_012', 'Cho các số 3, 6, 9, 12, 15, 18. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_013', 'Cho các số 4, 7, 10, 13, 16, 19. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_014', 'Cho các số 1, 6, 9, 12, 15, 20. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_015', 'Cho các số 2, 7, 10, 13, 16, 19. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_016', 'Cho các số 5, 8, 11, 14, 17, 20. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_017', 'Cho các số 4, 9, 12, 15, 18, 21. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_018', 'Cho các số 3, 8, 11, 14, 17, 22. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_019', 'Cho các số 6, 9, 12, 15, 18, 21. Có tất cả bao nhiêu số chẵn?', 2, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_020', 'Cho các số 2, 5, 10, 13, 16, 19. Có tất cả bao nhiêu số lẻ?', 2, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_021', 'Cho các số 7, 12, 15, 20, 23, 28, 31. Số chẵn lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_022', 'Cho các số 4, 9, 14, 17, 22, 25, 30. Số lẻ nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_023', 'Cho các số 6, 11, 18, 21, 26, 29, 34. Số chẵn nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_024', 'Cho các số 3, 8, 13, 16, 21, 24, 29. Số lẻ lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_025', 'Cho các số 5, 10, 17, 22, 27, 32, 35. Số chẵn lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_026', 'Cho các số 2, 7, 12, 19, 24, 31, 36. Số lẻ nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_027', 'Cho các số 9, 14, 17, 20, 25, 28, 33. Số chẵn nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_028', 'Cho các số 4, 11, 16, 23, 26, 31, 38. Số lẻ lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_029', 'Cho các số 8, 13, 18, 21, 26, 35, 40. Số chẵn lớn nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_030', 'Cho các số 5, 12, 17, 22, 29, 34, 37. Số lẻ nhỏ nhất trong các số đã cho là số nào?', 3, 'ACTIVE', NULL, NULL),

	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_031', 'Cho các số 4, 9, 12, 17, 22, 25, 30, 33. Có bao nhiêu số chẵn và bao nhiêu số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_032', 'Cho các số 6, 11, 14, 19, 24, 27, 32, 35. Số chẵn lớn nhất và số lẻ nhỏ nhất lần lượt là những số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_033', 'Cho các số 3, 8, 15, 18, 21, 26, 31, 34. Có bao nhiêu số chẵn và số chẵn lớn nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_034', 'Cho các số 5, 10, 13, 16, 21, 24, 29, 32. Có bao nhiêu số lẻ và số lẻ lớn nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_035', 'Cho các số 2, 7, 12, 17, 22, 27, 32, 37. Số chẵn nhỏ nhất và số lẻ lớn nhất lần lượt là những số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_036', 'Cho các số 4, 9, 14, 19, 24, 29, 34, 39. Có bao nhiêu số chẵn và bao nhiêu số lẻ?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_037', 'Cho các số 8, 11, 16, 21, 26, 31, 36, 41. Số lẻ nhỏ nhất và số chẵn lớn nhất lần lượt là những số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_038', 'Cho các số 3, 6, 13, 18, 25, 28, 35, 40. Có bao nhiêu số chẵn và số lẻ lớn nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_039', 'Cho các số 7, 12, 15, 20, 23, 28, 31, 36. Có bao nhiêu số lẻ và số chẵn nhỏ nhất là số nào?', 4, 'ACTIVE', NULL, NULL),
	('NUMBER_BASIC_EVEN_ODD', 'NUMBER_BASIC_EVEN_ODD_040', 'Cho các số 5, 10, 17, 22, 27, 32, 35, 40. Có bao nhiêu số chẵn và số lẻ nhỏ nhất là số nào?', 4, 'ACTIVE', NULL, NULL);

-- =========================================================
-- 6.1. Hai bước cộng
-- MULTI_STEP_ADD_ADD
-- 40 câu: 10 Dễ, 10 Trung bình, 10 Khó, 10 Rất khó
-- =========================================================
INSERT INTO MATH_QUESTIONS (CATEGORY_CODE, QUESTION_CODE, QUESTION_TEXT, DIFFICULTY, STATUS, CREATED_AT, UPDATED_AT) VALUES
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_001', 'Nam có 2 quả táo. Mẹ cho Nam thêm 3 quả táo, sau đó bố cho thêm 1 quả nữa. Hỏi Nam có tất cả bao nhiêu quả táo?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_002', 'Lan có 4 bông hoa. Cô cho Lan thêm 2 bông, sau đó bạn Mai cho thêm 1 bông nữa. Hỏi Lan có tất cả bao nhiêu bông hoa?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_003', 'Bình có 3 viên bi. Bố cho Bình thêm 2 viên, rồi anh cho thêm 2 viên nữa. Hỏi Bình có tất cả bao nhiêu viên bi?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_004', 'Trong bể có 5 con cá. Mẹ thả thêm 1 con cá, sau đó thả thêm 2 con nữa. Hỏi trong bể có tất cả bao nhiêu con cá?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_005', 'Mai có 3 chiếc bút. Cô giáo cho Mai thêm 2 chiếc, rồi mẹ cho thêm 3 chiếc nữa. Hỏi Mai có tất cả bao nhiêu chiếc bút?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_006', 'Trong giỏ có 2 quả cam. Mẹ đặt thêm 4 quả cam vào giỏ, sau đó đặt thêm 1 quả nữa. Hỏi trong giỏ có tất cả bao nhiêu quả cam?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_007', 'An có 5 chiếc kẹo. Bà cho An thêm 2 chiếc, rồi mẹ cho thêm 1 chiếc nữa. Hỏi An có tất cả bao nhiêu chiếc kẹo?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_008', 'Trên cành có 3 con chim. Có thêm 3 con bay đến, sau đó thêm 1 con nữa. Hỏi trên cành có tất cả bao nhiêu con chim?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_009', 'Hoa có 4 quyển truyện. Chị cho Hoa thêm 2 quyển, rồi bố cho thêm 2 quyển nữa. Hỏi Hoa có tất cả bao nhiêu quyển truyện?', 1, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_010', 'Trong hộp có 1 chiếc xe đồ chơi. Nam đặt thêm 3 chiếc vào hộp, sau đó đặt thêm 2 chiếc nữa. Hỏi trong hộp có tất cả bao nhiêu chiếc xe đồ chơi?', 1, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_011', 'Trên bàn có 5 quyển vở. Buổi sáng cô đặt thêm 3 quyển, đến chiều cô đặt thêm 2 quyển nữa. Hỏi trên bàn có tất cả bao nhiêu quyển vở?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_012', 'Một giỏ có 4 quả táo. Mẹ đặt thêm 3 quả vào giỏ, sau đó bố đặt thêm 2 quả nữa. Hỏi trong giỏ có tất cả bao nhiêu quả táo?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_013', 'Minh có 6 chiếc tem. Bạn cho Minh thêm 2 chiếc tem, sau đó cô giáo cho thêm 3 chiếc nữa. Hỏi Minh có tất cả bao nhiêu chiếc tem?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_014', 'Trong sân có 5 quả bóng. Nam mang thêm 4 quả ra sân, sau đó Minh mang thêm 2 quả nữa. Hỏi trong sân có tất cả bao nhiêu quả bóng?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_015', 'Một lớp có 7 bạn đang chơi. Có thêm 2 bạn tham gia, sau đó thêm 3 bạn nữa. Hỏi lúc này có tất cả bao nhiêu bạn đang chơi?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_016', 'Trong tủ có 3 chiếc cốc. Mẹ đặt thêm 4 chiếc vào tủ, rồi bố đặt thêm 2 chiếc nữa. Hỏi trong tủ có tất cả bao nhiêu chiếc cốc?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_017', 'Có 6 con vịt dưới ao. Có thêm 3 con bơi đến, sau đó thêm 2 con nữa. Hỏi dưới ao có tất cả bao nhiêu con vịt?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_018', 'Một hộp có 5 viên phấn. Cô giáo cho thêm 4 viên, sau đó cho thêm 3 viên nữa. Hỏi trong hộp có tất cả bao nhiêu viên phấn?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_019', 'Nam có 4 chiếc ô tô đồ chơi. Sinh nhật Nam được tặng thêm 3 chiếc, sau đó bố mua thêm 4 chiếc nữa. Hỏi Nam có tất cả bao nhiêu chiếc ô tô đồ chơi?', 2, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_020', 'Trên giá có 6 quyển sách. Mẹ đặt thêm 4 quyển sách, sau đó bố đặt thêm 3 quyển nữa. Hỏi trên giá có tất cả bao nhiêu quyển sách?', 2, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_021', 'Một cửa hàng có 6 chiếc bánh. Buổi sáng cửa hàng nhập thêm 4 chiếc bánh. Đến chiều, cửa hàng nhập thêm 3 chiếc nữa. Hỏi sau hai lần nhập, cửa hàng có tất cả bao nhiêu chiếc bánh?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_022', 'Trong vườn có 7 bông hoa. Người làm vườn trồng thêm 3 bông vào buổi sáng, sau đó trồng thêm 4 bông vào buổi chiều. Hỏi trong vườn có tất cả bao nhiêu bông hoa?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_023', 'Một hộp có 8 chiếc bút màu. Cô giáo cho thêm 3 chiếc vào hộp, sau đó bạn Lan cho thêm 2 chiếc nữa. Hỏi trong hộp có tất cả bao nhiêu chiếc bút màu?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_024', 'Có 5 con chim trên cành. Lúc đầu có thêm 4 con bay đến, sau đó thêm 5 con nữa bay đến. Hỏi trên cành lúc này có tất cả bao nhiêu con chim?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_025', 'Một thư viện có 7 quyển truyện thiếu nhi. Buổi sáng thư viện nhận thêm 3 quyển, đến chiều nhận thêm 5 quyển nữa. Hỏi thư viện có tất cả bao nhiêu quyển truyện thiếu nhi?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_026', 'Trong bể có 6 con cá vàng. Bố thả thêm 5 con cá, sau đó mẹ thả thêm 3 con nữa. Hỏi trong bể có tất cả bao nhiêu con cá vàng?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_027', 'Một lớp có 8 chiếc hộp bút màu. Cô giáo mang thêm 2 chiếc hộp đến lớp, sau đó phụ huynh tặng thêm 4 chiếc nữa. Hỏi lớp có tất cả bao nhiêu chiếc hộp bút màu?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_028', 'Nam có 7 viên bi trong túi. Anh cho Nam thêm 4 viên, sau đó bố cho thêm 3 viên nữa. Hỏi trong túi Nam có tất cả bao nhiêu viên bi?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_029', 'Một cửa hàng có 5 chiếc xe đạp. Buổi sáng cửa hàng nhận thêm 5 chiếc, đến chiều nhận thêm 4 chiếc nữa. Hỏi cửa hàng có tất cả bao nhiêu chiếc xe đạp?', 3, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_030', 'Trên sân trường có 9 bạn đang chơi. Có thêm 2 bạn đến chơi, sau đó thêm 4 bạn nữa. Hỏi trên sân trường lúc này có tất cả bao nhiêu bạn?', 3, 'ACTIVE', NULL, NULL),

	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_031', 'Trong giỏ có 7 quả cam. Buổi sáng mẹ đặt thêm 3 quả cam vào giỏ. Sau đó, bố đặt thêm 5 quả nữa. Hỏi sau cả hai lần thêm, trong giỏ có tất cả bao nhiêu quả cam?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_032', 'Một cửa hàng có 8 chiếc bánh. Cửa hàng nhập thêm 4 chiếc vào buổi sáng. Đến chiều, cửa hàng lại nhập thêm 3 chiếc nữa. Hỏi sau hai lần nhập hàng, cửa hàng có tất cả bao nhiêu chiếc bánh?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_033', 'Trên sân có 6 quả bóng. Nam mang thêm 5 quả bóng ra sân để chơi. Một lúc sau, Minh mang thêm 4 quả nữa. Hỏi sau hai lần mang bóng ra sân, trên sân có tất cả bao nhiêu quả bóng?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_034', 'Một giá sách có 7 quyển truyện. Mẹ đặt thêm 5 quyển vào giá. Sau đó bố đặt thêm 4 quyển nữa. Hỏi sau hai lần đặt thêm, giá sách có tất cả bao nhiêu quyển truyện?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_035', 'Trong vườn có 8 con bướm. Có 3 con bay đến vào buổi sáng. Một lúc sau, có thêm 5 con nữa bay đến. Hỏi trong vườn lúc này có tất cả bao nhiêu con bướm?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_036', 'Một hộp có 6 chiếc bút. Cô giáo cho thêm 5 chiếc bút vào hộp. Sau đó cô cho thêm 4 chiếc nữa. Hỏi sau hai lần thêm bút, trong hộp có tất cả bao nhiêu chiếc bút?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_037', 'Có 9 con chim trên cành. Buổi sáng có thêm 2 con bay đến. Sau đó có thêm 5 con nữa bay đến. Hỏi sau hai lần chim bay đến, trên cành có tất cả bao nhiêu con chim?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_038', 'Một giỏ có 7 quả táo. Mẹ đặt thêm 4 quả vào giỏ. Sau đó bố đặt thêm 5 quả nữa. Hỏi sau hai lần đặt thêm, trong giỏ có tất cả bao nhiêu quả táo?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_039', 'Nam có 8 chiếc xe đồ chơi. Anh cho Nam thêm 3 chiếc. Sau đó bố cho Nam thêm 5 chiếc nữa. Hỏi sau hai lần được cho thêm, Nam có tất cả bao nhiêu chiếc xe đồ chơi?', 4, 'ACTIVE', NULL, NULL),
	('MULTI_STEP_ADD_ADD', 'MULTI_STEP_ADD_ADD_040', 'Trong lớp có 6 hộp bút màu. Cô giáo mang thêm 5 hộp đến lớp. Sau đó phụ huynh tặng thêm 4 hộp nữa. Hỏi sau hai lần được thêm, lớp có tất cả bao nhiêu hộp bút màu?', 4, 'ACTIVE', NULL, NULL);
