DROP TABLE IF EXISTS `WORDS2`;
CREATE TABLE `WORDS2` (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENG VARCHAR(200) NOT NULL,
    VI VARCHAR(200) NOT NULL,
    CREATED_AT DATETIME(6) NULL DEFAULT NULL,
    UPDATED_AT DATETIME(6) NULL DEFAULT NULL,
	INDEX `IDX_WORD_ENG`(`ENG`) USING BTREE,
	INDEX `IDX_WORD_VI`(`VI`) USING BTREE
);

INSERT INTO WORDS2(ENG,VI)
SELECT ENG,VI FROM words ORDER BY ENG ASC;
TRUNCATE TABLE WORDS;
INSERT INTO WORDS(ENG,VI)
SELECT ENG,VI FROM WORDS2 ORDER BY ENG ASC;